### PR TITLE
feat(b-calendar, b-form-datepicker): new components `b-calendar` and `b-form-datepicker` (closes #3676, #1428)

### LINKED ISSUE #1428: [feature] calendar & datepicker component
It would be great if bootstrap-vue included the separate calendar component. It can be is useful in lots of apps. There are several implementations from different authors [https://github.com/vuejs/awesome-vue](url), but there is no a configurable and bootstrap stylized solution. 

Are there any plans to implement this component in library?

### LINKED ISSUE #3676: [Component] Datepicker
### Describe the solution you'd like

Would be great to DatePicker component. Usually always need to use third libs or create own for work with Dates on bootstrap.

What you think about it? Do you already have that kind of component in mind?

### PR DESCRIPTION
**Pull request by tmorehouse**
### Describe the PR

New components:

-  `<b-calendar>` calendar widget component
-  ` <b-form-datepicker>` date picker form input component (based on `<b-calendar>` and `<b-dropdown>`)

Calendar supports internationalization via `Intl.DateTimeFormat`, but requires aria labels to be manually internationalized.

Components are WAI-ARIA compliant. Both components are minimalistic by design for ARIA simplicity (i.e. no date range selection).

`<b-calendar>` and `<b-form-datepicker>` require minor custom CSS.

**BCalendar:**

https://deploy-preview-4712--bootstrap-vue.netlify.com/docs/components/calendar/

image

**BFormDatepicker (collapsed state):**

https://deploy-preview-4712--bootstrap-vue.netlify.com/docs/components/form-datepicker/

image

Closes #3676
Closes #1428

Screen reader tests manually performed with ChromeVox and NVDA

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Enhancement
- [x] ARIA accessibility
- [ ] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [x] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [x] Includes any needed TypeScript declaration file updates
- [x] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] CodeCov for patch has met target
- [x] The changes have not impacted the functionality of other components or directives
- [x] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by medioseureka** [comment]
Finally, these are great news, @tmorehouse thanks for the awesome work

**Comment by tmorehouse** [comment]
While working on the `b-date-picker` component validation states, I discovered a bug in Bootstrap v4.4 CSS regarding input-group sizing and form-control validation states: https://github.com/twbs/bootstrap/issues/30131

**Comment by Hiws** [comment]
Currently the `Current Month` button (round one in the middle of navigation arrows) goes to whichever month the selected date is in. 
Which of course could be any given month, and not the current one.

Is this by design or an error?

At first glance i expected the button to be a `back to today` kind of button. 
If it's design maybe `Selected Month` could be better or something along that?

Other than that the component is looking really nice, and is a very welcome addition.

**Comment by tmorehouse** [comment]
@Hiws the "Current month" will either go to the "selected" date' month, or today's month if no selected value. I was struggling to determine the best method of getting back to the selected date easily, without crowding the interface with too many nav buttons.  Perhaps it should only go to today's date?

**Comment by tmorehouse** [comment]
@Hiws I've changed the current month button to always go to today.  We may add an option in the future to make this date configurable.

**Pull request merged**
