### PR TITLE
fix(build): fix docs generation and cleanup devDependencies

### PR DESCRIPTION
**Pull request by jackmu95**
## Description of Pull Request:

This PR is a followup to #2590 and removes `@babel/plugin-transform-runtime` and `@babel/runtime`.

## PR checklist:

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Enhancement to an existing feature
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e.
      `fixes #xxxx[,#xxxx]`, where "xxxx" is the issue number)
- [x] The PR should address only one issue or feature. If adding multiple features or fixing a bug
      and adding a new feature, break them into separate PRs if at all possible.
- [x] PR titles should following the
      [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e.
      "fix(alert): not alerting during SSR render", "docs(badge): Updated pill examples, fix typos",
      "chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` is generated
      from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and
      event changes)
- [ ] New/updated tests are included and passing (if required)
- [ ] Existing test suites are passing
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (does it affect screen reader users or
      keyboard only users? clickable items should be in the tab index, etc)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a
      suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by pi0** [comment]
Other babel plugins including `babel/plugin-proposal-object-rest-spread`, `babel/plugin-external-helpers` and standalone are _unused_ too

**Comment by jackmu95** [comment]
> Other babel plugins including `babel/plugin-proposal-object-rest-spread`, `babel/plugin-external-helpers` and standalone are _unused_ too

Didn't we need `@babel/plugin-proposal-object-rest-spread` anymore?
We are also not including `@babel/plugin-transform-modules-commonjs` in devDependencies currently.

**Comment by pi0** [comment]
> Didn't we need `@babel/plugin-proposal-object-rest-spread` anymore?

Babel 7 should not require it

**Comment by jackmu95** [comment]
@pi0 The docs need `@babel/standalone` to run. Removing it throws this error:
```bash
This dependency was not found:

* @babel/standalone in ./docs/utils/compile-js.js

To install it, you can run: npm install --save @babel/standalone
```

**Comment by tmorehouse** [comment]
Yeah, standalone is conditionally required for docs (play and v-play) for older browsers.

**Comment by jackmu95** [comment]
The "regeneratorRuntime" error is caused by something else.

**Comment by tmorehouse** [comment]
Gonna try this in IE 11 and see if there are any issues.

**Comment by tmorehouse** [comment]
Hmmm docs are not building correctly.  getting a Nuxt error page:

image

**Comment by jackmu95** [comment]
@pi0 @tmorehouse: I've fixed the docs build by creating a new `docs` environment and adding `@babel/plugin-transform-runtime` back.

**Pull request merged**
