### PR TITLE
Tabs refactoring

### PR DESCRIPTION
**Pull request by mosinve**
Hi @pi0, there is my refactor attempt of Tabs. Please check code b4 merge :) I've tested already,  but just for sure :)

### CODE REVIEW

**Comment by pi0** [comment]
@mosinve Thnks :) Preparing docs. If ESLint fails i'll fix it too

**Comment by pi0** [comment]
Change list : 
- docs page
- updated example
- fix bug when we initially set tab to something not 0
- changed fade to no-fade for easier usage
- cards integration ability

@mosinve Would you please check changes and also what is your idea changing `navStyle` to just a `pills` prop? Is it intended for special usages or we may have only two possible values for that?

**Comment by mosinve** [comment]
About navstyle,  I left it as it was. In bootstrap there're 2 options: tabs or pills. So this prop intended to handle this. 
Quickly looked at changes from phone ,  and don't understand about cards... Check this today later from pc.

**Comment by mosinve** [comment]
Figured about cards - cool feature :)
One little notation: "card?'card-header':null" -  {'card-header': card} looks better IMHO, and according Vue's guide it's the same ;)

**Comment by pi0** [comment]
@mosinve I was just used to `card?` syntax :)) Yep object style is much better. 
`v-show` may help a little. But a real case: we have a blogging platform (like instagram) with 3 tabs editor, preview and comments. All of them are heavy enough ckeditor needs a big js chunk, comments are heavy and if we just use v-show we can't lazy load tabs. We may combine both methods with a `lazy` prop on each tab-item : 
```html 
<tab-item v-if="localshow || !lazy" v-show="localshow || lazy">```

**Comment by mosinve** [comment]
I like lazy variant - it's more flexible. 
Pills prop - i think about it too, so i agree ))

And one more thing, when i tested tabs on local playground, i catch a bug with parent/child assigment. Because of it i moved tabs init from tab (this.$parent) to tabs (this.$slots) -  in playground all components are childen of this.vm, but in real life - tab are child of tabs so old version worked well, but gave an error in playground.

**Comment by pi0** [comment]
@mosinve  I didn't get your meaning about $slots . Do you mean it won't work outside of playground?

**Comment by mosinve** [comment]
slots work everywhere
$parent/$child - not work in playground

**Comment by pi0** [comment]
I think i got it :)) @mosinve Would you please commit final fixes for that? so we merge & release it sooner :)

**Comment by mosinve** [comment]
I'll do

**Comment by mosinve** [comment]
funny thing:
if I write in tab item 
`v-if="localActive" v-show="localActive"`
transition begin to work smooth ))) even without lazy prop....

**Comment by pi0** [comment]
😂 It seems being related to <transition> wrapper.

**Comment by pi0** [comment]
@mosinve Merge it when done :) We can be ready for next release

**Comment by pi0** [comment]
поздравления :)

**Comment by mosinve** [comment]
متشکرم ;) Hope google trans make it correct)))))

**Pull request merged**
