### PR TITLE
feat(b-img-lazy): switch IntersectionObserver to use private `v-b-visible` directive

### PR DESCRIPTION
**Pull request by tmorehouse**
### Describe the PR

Rather than using `IntersectionObserver` directly, switch to the private `v-b-visible` directive

If we assume the user has added a polyfill for `IntersectionObserver` we can further reduce the size of the code by removing all the fallback window scroll/transition listeners.

If `IntersectionObserver` is not found, we just always force show the image (always non-lazy)

To Do:

- [x] Update docs
- [x] Update tests (Intersection Observer is not supported in JSDOM, so need a mock implementation)

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Enhancement
- [ ] ARIA accessibility
- [ ] Documentation update
- [x] Other (please describe) code refactor

**Does this PR introduce a breaking change?** (check one)

- [ ] No
- [x] Yes (please describe)

If `IntersectionObserver` support is not found (either natively or via polyfill), then the image will always be shown (non-lazy, and regardless of the show prop state)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [x] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] Includes any needed TypeScript declaration file updates
- [x] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by jackmu95** [comment]
@tmorehouse Yeah, I'am for the removing of the fallback code.

**Comment by tmorehouse** [comment]
@jackmu95 should we make it so that if IntersectionObserver is not found, then always show the image?

**Comment by jackmu95** [comment]
@tmorehouse Yeah.

**Comment by tmorehouse** [comment]
It appears that Vue-test-utils doesn't unbind a directive if the directive is conditionally removed from the element.  Although Vue itself does properly unbind a directive if it is removed from the render.

**Pull request merged**
