### PR TITLE
feat(types): create more typescript typings, and simplify component/directive/plugin imports.

### LINKED ISSUE #1976: Typescript imports don't find `index.d.ts` when importing individual components
- Version of Bootstrap-Vue that you are using
2.0.0-rc.11

```js
import bContainer from 'bootstrap-vue/es/components/layout/container';
```

```
69:24 Could not find a declaration file for module 'bootstrap-vue/es/components/layout/container'. 
'/node_modules/bootstrap-vue/es/components/layout/container.js' implicitly has an 'any' type.
  Try `npm install @types/bootstrap-vue` if it exists or add a new declaration (.d.ts) file containing `declare module 'bootst
rap-vue';`
  > 69 | import bContainer from 'bootstrap-vue/es/components/layout/container';
       |                        ^
```

I'm not sure if TypeScript has a way to specify the type declarations. From what I've looked into it doesn't. So to support imports like this a TypeScript definition would need to be made in every component directory.

### LINKED ISSUE #2554: Add `BvEvent` and `BvModalEvent` TypeScript definitions
I'm using bootstrap-vue together with TypeScript, and `BvEvent` is missing from the type declarations. This is required for example in modal `ok` events:

```javascript
ok(evt: BvModalEvent): void {
  evt.vueTarget ...
}
```

### LINKED ISSUE #2914: Why are Bootstrap-Vue types so bad?
The typings file at `src/index.d.ts` is out of date and only includes types for methods, but not properties, computed properties, etc. Since there is no `@types/bootstrap-vue`, wouldn't it make sense to improve the typings file included in the source?

### PR DESCRIPTION
**Pull request by tmorehouse**
### Describe the PR

Create more TypeScript typings, in a dedicated `/types` directory, and added a `typings` entry in `package.json` that points to the `types` directory.

Closes #2554
Closes #1976
Closes #2914

This PR also makes it easier to import individual components and directives via the use of named exports _(while still being backwards compatible to the current way)_. `/src/components.js` now exports a plugin as the default export, and provides named exports for all the individual components and component plugins. Similarly updated for `/src/directives.js` Example imports can bee seen at https://deploy-preview-3209--bootstrap-vue.netlify.com/docs/components/collapse

Added in option to import individual components and directives via the Nuxt.js Plugin.

#### Discussion/thoughts on typings:

- Should the individual component types/etc be defined in the component's directory? With a `<component>.d.ts` file for each component, and an `index.d.ts` for the plugin group? (that way the type definitions are in close proximity to the component/plugin code).

- Do we actually need types for every component? https://github.com/bootstrap-vue/bootstrap-vue/tree/types/types

- **Assistance with TypeScript testing would be greatly appreciated.** I looked at a few other component libraries for inspiration on creating the types (as I have no experience using TypeScript), and each one defined their types in a completely different fashion... some didn't even define types for components. so I had to make some _not-so-very-educated_ guesses.

- ~Should we comment out the Table `fields` definition temporarily until VeeValidate fixes their conflicting typings?~ veeValidate will have this fixed in next release (fixed in `v2.2.6`)

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Enhancement
- [ ] ARIA accessibility
- [x] Documentation update
- [x] Other (please describe) Types

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [x] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [x] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by pi0** [comment]
Mixing default export and named export, 
potentially breaks CJS users. Better to be double tested against external project before release and mentioned in docs about using `.default` in case of problems.

**Comment by tmorehouse** [comment]
Yeah, which is why I didnt bring the named experts into the main /src/index.js file. No one directly imports from /src/components/index.js, and we have had named plus default exports in many of the individual component files for close to two years.

**Comment by tmorehouse** [comment]
@pi0 do you have any experience with creating typescript declaration files?

**Comment by pi0** [comment]
@tmorehouse Regarding named exports, people use component plugins default export. Nuxt production mode directly uses `src/` so I suggested testing :) 

Regarding typescript, there is a trade off and depends on how we plan to maintain them. Keeping everything into separate `types/` allows easier usage. We may use `bootstrap-vue-helper-json` or a similar approach to auto-generate this typings.

**Comment by tmorehouse** [comment]
The docs website uses `/src` :wink:  (but it imports the full bootstrap Vue plugin )

**Pull request merged**
