### PR TITLE
[popover] [tooltip] mixin

### PR DESCRIPTION
**Pull request by tmorehouse**
Moved common functionality + tether into popover.js mixin.

This will help auto documentation so that only applicable props are shown in each component's docs.

Currently `b-tooltip` docs list a lot of props that are only applicable to `b-popover`, so this will help prevent some usage confusion such as issue #467 (https://github.com/bootstrap-vue/bootstrap-vue/issues/467#issuecomment-304533075)

This PR replaces outdated PR #470, so that it incorporates changes from PR #485 which addressed issue #484

### CODE REVIEW

**Comment by tmorehouse** [comment]
Yep...  using a mixin will hep with the auto-documentation generation of supported props on both tooltip and popover.

**Comment by alexsasharegan** [comment]
It looks like you also try to structure the order of template props (I've been on a mission to make my own ordering consistent). I wonder if there is a style guide for this yet. I've been working in this order more or less:
- `v-directive`
- id, class, other std html attrs (with bound attrs coming second)
- event handlers

I imagine that's something the Vue community will eventually settle on. That and little things like closing the opening markup tag on the same line or a new line.

**Comment by tmorehouse** [comment]
Yeah, I find having the events last makes things easier to see, and bound stuff near the first.  The closing markup tag on a newline helps show the end of attributes/bindings/events as sometimes they line up with the next child element

**Comment by alexsasharegan** [comment]
We could probably use a standard set of Vetur formatting settings to keep things consistent. What editor do you use when working with Vue code?

**Comment by tmorehouse** [comment]
I'm _old school_ and use either the github web interface, or or larger changes I edit in notepad++ :P

**Comment by alexsasharegan** [comment]
image

**Comment by tmorehouse** [comment]
I use vim as well ;-)

**Comment by alexsasharegan** [comment]
I've managed to get as far as learning how to quit vim—and I feel accomplished there!

**Comment by tmorehouse** [comment]
Any objections to this PR being merged?

**Comment by alexsasharegan** [comment]
None from this guy. Onward!

**Pull request merged**
