### PR TITLE
Fix: Issue 307

### PR DESCRIPTION
**Pull request by alexsasharegan**
Fixing the `toLowerCase` call on default value null. Reference issue #307

### CODE REVIEW

**Comment by mosinve** [comment]
Just curious, why just don't leave `''` ? As for me you do the same thing but from another side... ;) and with more code...

**Comment by alexsasharegan** [comment]
@mosinve I was using an empty string by default before, but it seems that @pi0 has a preference for empty defaults being `null`. I see you already PRed this, so we don't need to use this PR. I'll let @pi0  decide what fits the lib best—I just wanted to respond to the breaking change.

**Comment by tmorehouse** [comment]
As well, For attributes, using null actually will remove the attribute from the element, where as empty string `''` will leave the attribute on a node but without a value.

**Comment by alexsasharegan** [comment]
Interesting, @tmorehouse . With the object syntax in class bindings, any falsy value will be omitted. Looks like you can nest style objects in the array as well though.

**Comment by mosinve** [comment]
I didn't know this :) okay now i know ))))

**Pull request closed without merging**
