### PR TITLE
chore(docs): Remove inconsistencies

### PR DESCRIPTION
**Pull request by jackmu95**
## Description of Pull Request:

This PR fixes some docs inconsistencies:
- `Webpack` -> `webpack`
- `Rollup` -> `rollup.js`
-  `Bootstrap-Vue`, `Bootstrap Vue` -> `BootstrapVue` 
- `vue-cli` -> `Vue CLI`
- `Change Log`, `ChangeLog` -> `Changelog`
- Code indentation and trailing semicolons
- Use `scss` code highlighting where needed
- Some other minor tweaks

## PR checklist:

**What kind of change does this PR introduce?** (check at least one)
- [ ] Bugfix
- [ ] Feature
- [ ] Enhancement to an existing feature
- [ ] ARIA accessibility
- [x] Documentation update
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)
- [ ] Yes
- [x] No

If yes, please describe the impact:

**The PR fulfills these requirements:**
- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `fixes #xxxx[,#xxxx]`, where "xxxx" is the issue number)
- [x] The PR should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] PR titles should following the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. "fix(alert): not alerting during SSR render", "docs(badge): Updated pill examples, fix typos", "chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**
- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] New/updated tests are included and passing (if required)
- [ ] Existing test suites are passing
- [ ] The changes have not impacted the functionality of other components or directives 
- [ ] ARIA Accessibility has been taken into consideration (does it affect screen reader users or keyboard only users? clickable items should be in the tab index, etc)

**If adding a new feature, or changing the functionality of an existing feature, the PR's description above includes:**
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by jackmu95** [comment]
@tmorehouse Are the Change Log and Contributed pages generated from the `CHANGELOG.md` and `CONTRIBUTING.md` files or are they just synced at the moment?

**Comment by jackmu95** [comment]
@tmorehouse I'am also thinking for a wile now about adding `prettier` formatting for the docs.

I'am using it for some internal projects and I like it a lot because it takes away all the table formatting stuff and also helps a lot with code example indentation and consistency in spacing overall.

Any interest in a PR?

**Comment by tmorehouse** [comment]
CHANGELOG.md is auto generated via conventional-version when we prep a release  (and then manually tweaked to fix heading levels and formats)

CONTRIBUTING is is a dynamic SVG image that is pulled in via a URL (as are the images for backers, etc).

**Comment by tmorehouse** [comment]
@jackmu95 Sure, if you want to make a PR for prettier, we can take a look at it to see what it does.

**Comment by jackmu95** [comment]
I'am done here for now. Let ne know when something needs changes or feel free to apply you tweaks.

**Comment by tmorehouse** [comment]
I'm wondering about the Vue CLI 3 stuff.. I think we should add in the new `vue.config.js` stuff for the `transformAssetUrls`

```js
// vue.config.js
module.exports = {
  chainWebpack: config => {
    config.module
      .rule('vue')
      .use('vue-loader')
      .loader('vue-loader')
      .options({
        transformAssetUrls: {
          video: ['src', 'poster'],
          source: 'src',
          img: 'src',
          image: 'xlink:href',
          // BootstrapVue components
          'b-img': 'src',
          'b-img-lazy': ['src', 'blank-src'],
          'b-card': 'img-src',
          'b-card-img': 'img-src',
          'b-carousel-slide': 'img-src',
          'b-embed': 'src'
        }
      })
  }
}
```

**Comment by tmorehouse** [comment]
For the `vue.config.js` info for Vue CLI 3, we can create a separate PR

**Pull request merged**
