### PR TITLE
chore(lodash): Use `lodash-es` imports to improve users bundle size (Closes #2466)

### LINKED ISSUE #2466: Use full lodash(-es) dependency (and not lodash.<method>)
Currently bootstrap-vue has dependencies on lodash.get and lodash.startcase. After distribution these dependencies are only needed when using the es build, as for umd and cjs they are included in the dist. When I bundle bootstrap-vue in my (nuxt) project, then according to webpack bundle analyzer these are both ~20KB in stat size and ~4KB in parsed size.

A side-effect of using lodash.get is that if someone already uses lodash in their project, then lodash.get (and mostly its internal dependencies) becomes duplicated. If I hack bootstrap-vue locally to use `from lodash/startCase` and `from lodash/get` instead, my vendors bundle size becomes 8KB smaller according to webpack.

By depending on the full lodash build we can rely on tree-shaking to only pick the parts of lodash we need for the whole project, without the need of duplicating internal lodash functions.

Btw, following this same logic I predict the bootstrap-vue dist sizes for umd and cjs builds will become ~4KB smaller as well if we do this.

Before:
image

After:
image

### PR DESCRIPTION
**Pull request by jackmu95**
## Description of Pull Request:

This PR uses `lodash-es` imports in combination with `babel-plugin-lodash` to save users of BootstrapVue some bundle size if they use `lodash` anyway.

| File                            | Size (before) | Size (after) |
| ------------------------------- | ------------- | ------------ |
| bootstrap-vue.common.js         | 548K          | 550K         |
| bootstrap-vue.common.js.map     | 996K          | 1,0M         |
| bootstrap-vue.common.min.js     | 235K          | 237K         |
| bootstrap-vue.common.min.js.map | 830K          | 843K         |
| bootstrap-vue.esm.js            | 421K          | 464K         |
| bootstrap-vue.esm.js.map        | 789K          | 869K         |
| bootstrap-vue.esm.min.js        | 198K          | 212K         |
| bootstrap-vue.esm.min.js.map    | 650K          | 721K         |
| bootstrap-vue.js                | 583K          | 585K         |
| bootstrap-vue.js.map            | 1,0M          | 1,1M         |
| bootstrap-vue.min.js            | 208K          | 209K         |
| bootstrap-vue.min.js.map        | 841K          | 853K         |

Closes #2466.

## PR checklist:

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Enhancement to an existing feature
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e.
      `fixes #xxxx[,#xxxx]`, where "xxxx" is the issue number)
- [x] The PR should address only one issue or feature. If adding multiple features or fixing a bug
      and adding a new feature, break them into separate PRs if at all possible.
- [x] PR titles should following the
      [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e.
      "fix(alert): not alerting during SSR render", "docs(badge): Updated pill examples, fix typos",
      "chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` is generated
      from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and
      event changes)
- [ ] New/updated tests are included and passing (if required)
- [ ] Existing test suites are passing
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (does it affect screen reader users or
      keyboard only users? clickable items should be in the tab index, etc)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a
      suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by mosinve** [comment]
According to what `babel-plugin-lodash` does, this PR makes no sense.

**Comment by jackmu95** [comment]
@mosinve Yeah, we can remove it to save some build time.

**Comment by mosinve** [comment]
Even so, this PR doesn't add any improvements, beside renaming of some imported methods and changing the order of imports.

**Comment by pi0** [comment]
Instead, i suggest using esm build of lodash. (`lodash-es`)

**Comment by mosinve** [comment]
@jackmu95 Man, you again use that plugin, why?

**Comment by pi0** [comment]
according to packagephobia, install size of `lodash-es`([install size](https://packagephobia.now.sh/result?p=lodash-es)) is bigger than `lodash.get`([install size](https://packagephobia.now.sh/result?p=lodash.get)) + `lodash.startcase`([install size](https://packagephobia.now.sh/result?p=lodash.startcase))

Also as @mosinve said, the behavior of babel-plugin does not impact bundle size.

Still, we have to consider inlining get and startCase utils to prevent mentioned `2Kb` overhead.

**Comment by pi0** [comment]
@jackmu95 You made a big attempt for this discovery. I've addressed this in #2523. Sorry for closing this PR. I try to keep your contribution credits on merge.

**Pull request closed without merging**
