### PR TITLE
Add clickable table row

### PR DESCRIPTION
**Pull request by tithamane**
We wanted to have the ability to redirect when clicking a row instead of using a button. We opted to go with passing a function to the component and have that function execute when the row is clicked in which we redirect.

Using a function will give us some flexibility in the case that we might want to do something else.

If there is a builtin/easier way to do this then we'd like to know about and forget about this pull request.

### CODE REVIEW

**Comment by pi0** [comment]
@tithamane Thanks for PR. I was thinking of adding this option too. However, i think using events would be a better idea instead of passing a function and then calling it. `this.$emit('rowClicked',item, index);`

**Comment by tithamane** [comment]
@pi0 I like the idea. So rowClicked would be a boolean?

**Comment by pi0** [comment]
@tithamane We can then remove that property :) Usage is like normal events `<b-table @row-clicked="myFunction">`

**Comment by tithamane** [comment]
Is the current change fine?

**Comment by pi0** [comment]
Yep :) Thanks

**Pull request merged**
