### PR TITLE
feat(utils): wrap-up as ES6 module

### PR DESCRIPTION
**Pull request by mosinve**

### CODE REVIEW

**Comment by tmorehouse** [comment]
Great idea, especially for the utils.

**Comment by alexsasharegan** [comment]
Very nice! I was just working on the same thing, but just for utils. Trying to get some polyfill magic going, but with a transpiler friendly twist.

**Comment by alexsasharegan** [comment]
I want this merged so I can merge my work into it: https://github.com/alexsasharegan/bootstrap-vue/compare/master...alexsasharegan:refactor/utils

**Comment by mosinve** [comment]
merged

**Pull request merged**
