### PR TITLE
[pagination] align with Bootstrap v4

### PR DESCRIPTION
**Pull request by tmorehouse**
This PR changes the `button`s into `li.page-item > a.page-link` elements, aligning with Bootstrap V4 alpha 6

Note that BS V4 pagination doesn't support button variants (contextual classes), and as such they have been removed.

Supported optional pagination sizes are `sm` and `lg`

Addresses issue #443

**Note:** I haven't had a chance to fully test this yet.

### CODE REVIEW

**Comment by pi0** [comment]
Thanks Troy for your Awesome contributions every day :)

**Comment by tmorehouse** [comment]
Hopefully it works as expected ;-)

**Comment by tmorehouse** [comment]
I'll update the documentation later (if needed).

The example fiddle will need to be updated to remove the second variant...

**Comment by alexsasharegan** [comment]
Agreed! You're a maniac! 
image

**Comment by tmorehouse** [comment]
Hehe, don't forget to pat yourselves on the back too!   You guys are also doing awesome work!

**Pull request merged**
