### PR TITLE
feat(table): Add row-unhovered event

### PR DESCRIPTION
**Pull request by gaaf**
Some users might want to know not only when the mouse is hovering a row,
but also when the mouse leaves the row.

For example for dynamically showing (and hiding) some row content based
on mouse hovering.

### CODE REVIEW

**Comment by mosinve** [comment]
There's a `::hover` css pseudo-class, and b-table has a `tbody-tr-class` prop. Combining both, in most cases could help, i think

**Comment by mosinve** [comment]
b-table is already over-customizable.

**Comment by gaaf** [comment]
@mosinve Thanks for the hint. That indeed works for showing/hiding stuff in the same row (column with action buttons in my case). But this won't solve the general case.

This PR is to make the API more coherent as it is asymmetric now. There is an event for handling mouseenter (row-hovered), but there is no way to handle mouseleave (row-unhovered).

**Comment by tmorehouse** [comment]
@gaaf could you add in a test for the unhovered event?

**Comment by tmorehouse** [comment]
For testing, I am not sure how to test (i.e. simulate) a mouse over/out event JSDOM.  So I guess we skip that (as we currently do not test for the current `row-hovered` event).

**Pull request merged**
