### PR TITLE
feat(): add a extra-toggle-classes prop to nav-item-dropdown.js with …

### PR DESCRIPTION
**Pull request by ghenry**
…tests and docs. Refs #1550

### CODE REVIEW

**Comment by pi0** [comment]
Hey. Thanks for this PR. What's your idea if we simplify prop name `extra-toggle-classes` into `toggle-class`?

**Comment by ghenry** [comment]
Hi!

Sounds good, but it sounds more like an override rather than an additional
class. Ideally I'd like to have a common prop available for every type of
component like this. I only spent last night and this morning looking
around the project design to do enough to get this to work.

I know I'll need more of these migrating my static bs4 theme to bs vue.

Thanks.

**Comment by pi0** [comment]
Seems reasonable for naming. Thanks again for PR. Will be available soon in `2.0.0-rc`.

**Comment by pi0** [comment]
Update: it is available with both `v1.5.0` and `v2.0.0-rc.0` now :)

**Comment by ghenry** [comment]
I have a doc correction:

> that by default has the classes 

should be

> that by default have the classes 

best way to fix? Another PR?

**Comment by pi0** [comment]
Ah fixed. Thanks for notifing :)

**Comment by ghenry** [comment]
Have now upgraded and working perfectly. Thanks for building such a great
project.

**Pull request merged**
