### PR TITLE
fix(b-modal): handle enforce focus case where tinyMCE editor inside modal (fixes #4537)

### LINKED ISSUE #4537: Tinymce-vue dialog unable to edit in bootstrap-vue modal.
See https://codesandbox.io/s/tinymce-vue-bootstrap-vue-modal-focusin-zxfjn

Use [official workaround](https://www.tiny.cloud/docs/integrations/bootstrap/#usingtinymceinabootstrapdialog) for bootstrap-vue modal not works. The Tinymce dialog are not editable.

```js
// Prevent Bootstrap dialog from blocking focusin
$(document).on('focusin', function(e) {
  if ($(e.target).closest(".tox-tinymce-aux, .moxman-window, .tam-assetmanager-root").length) {
    e.stopImmediatePropagation();
  }
});
```

Seems works with native Bootstrap 4 https://codesandbox.io/s/bootstrap-tinymce-mxi9f

The issue also post at https://github.com/tinymce/tinymce-vue/issues/116

### PR DESCRIPTION
**Pull request by tmorehouse**
### Describe the PR

Handle enforce focus case when tinyMCE editor is inside a modal.

fixes #4537

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Enhancement
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] CodeCov for patch has met target
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by jackmu95** [comment]
@tmorehouse Not sure if we should add something that only effects a fraction of users that are using tinyMCE.

**Comment by tmorehouse** [comment]
@jackmu95 yeah... it is mainly an issue with embedded `iframe`s in the modal (tinyMCE uses an `<iframe>`).

Although there is a way to get TinyMCE to not use an iframe, and instead use a content editable container, although I can't remember how that is set.

**Comment by asika32764** [comment]
Maybe we can consider add a hook to let developer decide how to stop the focus event, otherwise it has no any way to stop this event now.

**Comment by tmorehouse** [comment]
@asika32764  You can set the prop `no-enforce-focus` on the modal to disable the enforce-focus routine, which would be an interim workaround.

**Comment by asika32764** [comment]
Seems works for my project. Can this prop caused any side-effects?

**Comment by tmorehouse** [comment]
@asika32764 the downside is that if you press tab several times, then the focus will move to an element behind the modal, which can make it hard for keyboard only users to get back into the modal.

And other option you could try is to put the editor inside a DIV that prevents bubbling of the focusin/out events (so that they do not reach the focus management listener in the modal):

```html
<b-modal .... >
  <div @focusin.stop @focusout.stop>
    <!-- place MCE editor component here -->
  </div>
</b-modal>
```

**Comment by jackmu95** [comment]
Closed in favor of #4702.

**Pull request closed without merging**
