### PR TITLE
Remove explicit Tether dependency

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This is trivial PR:
Tether.js is always installed as part of BS 4 dependency:
https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.6/package.json\#L49
This RP removes some noise from configuration.
Thanks!

### CODE REVIEW

**Comment by tmorehouse** [comment]
Bootstrap-vue doesn't require bootstraps Java script code, so this would cause popovers and tooltips to stop working.

**Comment by peterblazejewicz** [comment]
> Bootstrap-vue doesn't require bootstraps Java script code, so this would cause popovers and tooltips to stop working.

Hm, this was not about client code, but tooling configuration. The Tether package is always installed alongside Bootstrap package

**Comment by pi0** [comment]
I think that would be better kept until we fully remove tether dependency. Seems bootstrap project is going to plan same thing, so keeping that won't make any breaking changes. Anyway feel free marge or merge not :))

**Comment by pi0** [comment]
Will apply better patch when migrated. Thanks for PR :)

**Pull request closed without merging**
