### PR TITLE
[Issue #400] Modal Dead Code removal

### PR DESCRIPTION
**Pull request by alexsasharegan**
If this is, in fact, dead code, here is a removal PR.

### CODE REVIEW

**Comment by pi0** [comment]
@alexsasharegan `visible` is not a dead code! It is used to sync visiblity and user can toggle modals with changing `visible` model ;)

**Comment by alexsasharegan** [comment]
Touché. I've been hunting down why the modal sometimes doesn't get the 'show' class added to the main `.model` element, and I couldn't figure out where this was used. Is there any Vue.js documentation on writing components that implement `v-model`? I looked, but came up 404.

**Comment by alexsasharegan** [comment]
There's really no example on how to use v-model to show the modal. I'm hacking away, but no luck.

**Comment by pi0** [comment]
https://vuejs.org/v2/guide/forms.html

**Comment by alexsasharegan** [comment]
Yeah, I've looked that over. I'm not convinced this is implemented correctly. The example from the docs here looks very different: https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events

**Comment by alexsasharegan** [comment]
Is there any chance I could get a working example in a fiddle or something? I can't get this to work for the life of me. I use the crap out of v-model too!

**Comment by alexsasharegan** [comment]
I've even tried watching the change event to check out how this works (since the model is set to emit a change event). @tmorehouse, maybe you can show me an example forked from the docs fiddle? I'm not sure if it's me, or the v-model feature isn't correct.

**Pull request closed without merging**
