### PR TITLE
feat(dropdown): support anchortag as trigger element

### PR DESCRIPTION
**Pull request by lnufnu**
Added support for anchor tags. Takes prop `elementType`, which is set to `button` by default and `anchor` for anchor elements.

### CODE REVIEW

**Comment by tmorehouse** [comment]
Rather than `elementType`, wouldn't it be more consistent with other component to use a `tag` prop?

**Comment by jackmu95** [comment]
This PR conflicts with the changes made in #1929. It added the support for defining a custom tag for `<b-button>` by using the `tag` prop and made it also possible to change the `<b-dropdown>`'s toggle tag with the `toggleTag` prop.

So it is already possible to use a anchor tag for `<b-dropdown>`'s toggle:
```vue
<b-dropdown text="Dropdown Button" toggle-tag="a">
  <b-dropdown-item>First Action</b-dropdown-item>
  <b-dropdown-item>Second Action</b-dropdown-item>
  <b-dropdown-item>Third Action</b-dropdown-item>
</b-dropdown>
```

**Comment by tmorehouse** [comment]
@jackmu95 has the docs been updated to mention that?

**Comment by jackmu95** [comment]
@tmorehouse #1929 added docs for the new `toggle-tag` prop but because there was no new RC sine it was merged it isn't in the docs currently online.

**Comment by tmorehouse** [comment]
Closing as redundant via  #1929

**Pull request closed without merging**
