### PR TITLE
[links] rel and target attributes

### PR DESCRIPTION
**Pull request by tmorehouse**
Adds `target` and `rel` attributes to all link-based components.

If `target === '_blank'` and `rel` is `null` then default `rel` to `'noopener'`

Addresses #413

### CODE REVIEW

**Comment by tmorehouse** [comment]
Does the `computedRel` logic look OK to you @pi0 ?

**Comment by pi0** [comment]
Yep it seems nice :)

**Comment by alexsasharegan** [comment]
I think the `this.target === '_blank'` condition could be eliminated. It doesn't matter which target, you don't want to grant another domain context to your page, right? Or does it not matter because the window will be closed?

**Comment by pi0** [comment]
Sorry i was merged fast :)) So you mean adding `noopener` even to internal links?

**Comment by tmorehouse** [comment]
I didn't apply the rel/target to `breadcrumb` as typically breadcrumbs are in-domain (plus it would mean adding rel and target properties to each item in the list of items

**Comment by tmorehouse** [comment]
The only think I would be timid of, is if someone does want the opener property not set to `noopener` (which they can override by specifying an empty string for `rel`).

Just concerned that it could break some user use cases.

**Comment by alexsasharegan** [comment]
This would allow for any falsey value to drop the rel attribute, but it would probably break anyone depending on that communication as they will be forced to specify that prop now. But how many people use it that way?

```
props: {
        target: {
            type: String,
            default: null
        },
        rel: {
            type: String,
            default: 'noopener noreferrer'
        },
},
computed: {
    computedRel() {
        return this.target ? this.rel : null;
    }
}
```

**Comment by tmorehouse** [comment]
Maybe it should be up to the page author to specify any values, leaving security up to them?

**Comment by alexsasharegan** [comment]
So, I tested the `window.opener` prop on a link opened in the same window, and it is `null`. That makes sense because you just blew away the window by navigating to that link.

**Comment by alexsasharegan** [comment]
So maybe that means your computedRel is perfect the way it is?

**Comment by tmorehouse** [comment]
Note I defaulted `target` to `_self` as well.

**Comment by alexsasharegan** [comment]
As it is now, if I use the conventional `_blank`, I get the `noopener`. If I specify a `rel` prop, I get my rel. If I use a non-standard target, I have to specify the rel to get the security. All seems like reasonable to me.

**Comment by alexsasharegan** [comment]
Ship it! @pi0, you weren't premature on the merge after all.

**Comment by tmorehouse** [comment]
Should `nofollow` also be added (for firefox)?

**Comment by alexsasharegan** [comment]
Hmm... that's primarily an SEO concern, right? Now that we have a `rel` attribute, people have the ability to specify that at least.

**Comment by tmorehouse** [comment]
@alexsasharegan Oops, I meant `noreferrer` not `nofollow`

https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
> Update: FF does not support "noopener" so add this.
> ```js
> rel="noopener noreferrer"
> ```

**Comment by alexsasharegan** [comment]
I know that article makes it sound necessary, but when I look at the MDN page for an anchor tag, that attribute doesn't seem necessary. It just wipes your url from the referrer header on the request. Not sure how that is a security risk.

**Comment by tmorehouse** [comment]
True.  So we'll leave it as is for now :)

**Pull request merged**
