### PR TITLE
[button-group] Toolbar keynav fixes

### PR DESCRIPTION
**Pull request by tmorehouse**
A couple of capslock typo fixes.

### CODE REVIEW

**Comment by tmorehouse** [comment]
I am wondering if the toolbar feature should be moved into it's own component, since it is really a wrapper for groups of button-groups?

See BS V4 example:
http://v4-alpha.getbootstrap.com/components/button-group/#button-toolbar

**Comment by pi0** [comment]
Do you mean for accessibility features?

**Comment by tmorehouse** [comment]
Somewhat.

A toolbar will never have buttons as direct descendants. It will always have aa child button group(s) and maybe input group(s)

**Comment by tmorehouse** [comment]
maybe a `b-button-toolbar` component, or `b-toolbar` component.

**Comment by pi0** [comment]
Never personally needed that but this is a official Bootstrap component and It would be useful :)

**Comment by tmorehouse** [comment]
Yeah.  It is part of the `button-group` documentation of BS V4, but really it is is't own wrapper/component that would have button-group and input-group's as children components.  And then remove the 'toolbar' prop option from the `button-group`

**Comment by tmorehouse** [comment]
I think the component wrapper should be `b-button-toolbar`, to follow the BS4 class of `.btn-toolbar`

**Comment by tmorehouse** [comment]
I can whip up a new component in a few minutes.

**Pull request merged**
