### PR TITLE
fix(b-dropdown): click handling on close (closes #5982)

### LINKED ISSUE #5982: Navbar : Unclickable specific b-nav-item(s).
### Describe the bug

When I use a basic **navbar menu** comporting let's say, four items, including a dropdown :

```
<b-collapse id="nav-collapse" is-nav>
      <b-navbar-nav>
        <b-nav-item href="https://bootstrap-vue.org/">Link-1</b-nav-item>
        <b-nav-item href="https://bootstrap-vue.org/">Link-2</b-nav-item>
        <b-nav-item-dropdown text="Dropdown" right>
            <b-dropdown-item href="https://bootstrap-vue.org/">Sublink-1</b-dropdown-item>
            <b-dropdown-item href="https://bootstrap-vue.org/">Sublink-2</b-dropdown-item>
            <b-dropdown-item href="https://bootstrap-vue.org/">Sublink-3</b-dropdown-item>
        </b-nav-item-dropdown>
        <b-nav-item href="https://bootstrap-vue.org/">Link-3</b-nav-item>
        
      </b-navbar-nav>
    </b-collapse>
```
Any subsequent link (nav-item) to an **opened dropdown** is getting non-fonctional.

### Steps to reproduce the bug
1. Open the dropdown menu item
2. Move to the next link (nav-item) located outside of opened dropdown (here Link-3).
3. Click item.
4. Watch the dropdown close (like a normal click outside behavior) but, link is getting nowhere.

### Expected behavior

Expected to work like other nav-items located **before** an opened dropdown (Link-1, Link-2).

### Versions

**Libraries:**

- BootstrapVue: 2.18+
- Bootstrap: 4
- Vue: 2

**Environment:**

All mobile devices + Chrome Dev mobile emulation. Menu works fine on desktop while not in collapsed mode (burger menu).

### Visual info:

image

### PR DESCRIPTION
**Pull request by jackmu95**
### Describe the PR

This PR ensures that any click handling can happen before a dropdown closes.
It is a follow-up to #4426 and #4329.

Closes #5982.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix (fixes a boo-boo in the code) - `fix(...)`, requires a patch version update
- [ ] Feature (adds a new feature to BootstrapVue) - `feat(...)`, requires a minor version update
- [ ] Enhancement (augments an existing feature) - `feat(...)`, requires a minor version update
- [ ] ARIA accessibility (fixes or improves ARIA accessibility) - `fix(...)`, requires a patch or minor version update
- [ ] Documentation update (improves documentation or typo fixes) - `chore(docs)`, requires a patch version update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe since breaking changes require a minor version update)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc.). **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type (patch or minor).**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates
- [ ] Includes component package.json meta section updates (prop, slot and event changes/updates)
- [ ] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (required for new features and enhancements)
- [ ] Existing test suites are passing
- [ ] CodeCov for patch has met target (all changes/updates have been tested)
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by jackmu95** [comment]
@Hiws @simonalarie Please check out this CodeSanbox to confirm the issue is fixed:
https://codesandbox.io/s/bootstrapvue-starter-project-forked-d13yf?file=/App.vue

**Comment by Hiws** [comment]
It's still not possible to click the link underneath while the dropdown is open, but it's possible to click the link above it.

QjHtEwL6ba

**Comment by simonalarie** [comment]
Hello Jacob,

Still the same. Link-3 is not functional while dropdown is opened.

Thanks

Sent from my iPhone

On Nov 4, 2020, at 5:28 AM, Jacob Müller <notifications@github.com<mailto:notifications@github.com>> wrote:


@Hiws<https://github.com/Hiws> @simonalarie<https://github.com/simonalarie> Please check out this CodeSanbox to confirm the issue is fixed:
https://codesandbox.io/s/bootstrapvue-starter-project-forked-d13yf?file=/App.vue

**Comment by simonalarie** [comment]
Exactely.

Sent from my iPhone

On Nov 4, 2020, at 10:50 AM, Hiws <notifications@github.com<mailto:notifications@github.com>> wrote:


It's still not possible to click the link underneath while the dropdown is open, but it's possible to click the link above it.

[QjHtEwL6ba]<https://user-images.githubusercontent.com/7057431/98133299-b6d50c80-1ebd-11eb-951d-b2c5b9b557a9.gif>

**Comment by jackmu95** [comment]
@Hiws @simonalarie Please check out this CodeSanbox to confirm the issue is fixed:
https://codesandbox.io/s/bootstrapvue-starter-project-forked-qum94?file=/App.vue

**Comment by simonalarie** [comment]
Bingo Jacob!

Many thanks for the update, I'm impressed ; ).

I guess it will be available on v2.19?

Have a good day.

Simon A.,
Montreal

________________________________

**Review by Hiws — APPROVED** [review]

**Pull request merged**
