### PR TITLE
feat(docs): live demo

### PR DESCRIPTION
**Pull request by pi0**
I've tried to move all examples from JSFiddle here. Please give your feedback :)

### CODE REVIEW

**Comment by alexsasharegan** [comment]
I should be able to git checkout, run `docs-dev`, and play with this myself, right?

**Comment by pi0** [comment]
@alexsasharegan Yep! :)

**Comment by alexsasharegan** [comment]
Maybe this sounds silly, but the double-click to edit note doesn't advertise this well enough. Maybe that could at least be bigger and bolder?

**Comment by tmorehouse** [comment]
Looks cool!  so can we do multiple examples per page too?

**Comment by alexsasharegan** [comment]
You beat me to the typos!

**Comment by pi0** [comment]
@alexsasharegan I've just copy-paste styles from vue.js docs :D Feel free making it bigger

**Comment by pi0** [comment]
@tmorehouse Yes. We also can use simpler syntax for inline examples.(Like badges docs without template and script!)

**Comment by alexsasharegan** [comment]
Would I edit directly in the `/docs/nuxt/assets/css/styles.css`? Or is that pulled from somewhere else?

**Comment by pi0** [comment]
Yes we can edit that file

**Comment by alexsasharegan** [comment]
I'm no designer, so feel free to smooth out the rough edges of my attempts to grab attention to the content-editable.

**Comment by tmorehouse** [comment]
Make it `400px` font-size :stuck_out_tongue_winking_eye:

**Comment by tmorehouse** [comment]
Once this is merged in, I could add/edit a few examples.

**Comment by alexsasharegan** [comment]
Just curious, does this playground pose any security threat to the host?

**Comment by pi0** [comment]
I hope it can't. `<script>` part should be evalouated if CURRENT USERS double clicks and edits that section. So if such code creares security threat how JSFiddle works more secure?

**Comment by tmorehouse** [comment]
jsFiddle uses sandboxed iframes I think

**Comment by tmorehouse** [comment]
I suppose it would be the same as if someone used dev tools console to add their own `<script>` tags

**Comment by pi0** [comment]
(It is a `feat`, so should be added for minor bump)

**Comment by tmorehouse** [comment]
So ar we going to skip[ 0.17.2 and go straight to 0.18.0?

**Comment by pi0** [comment]
I think we should :)

**Comment by tmorehouse** [comment]
OK cool... :+1:

**Comment by pi0** [comment]
Hope bootstrap4 rcs come sooner than we reach 0.99.0 :D

**Comment by tmorehouse** [comment]
Are there any other things we want to put in vor v0.18.0?

**Comment by pi0** [comment]
@tmorehouse You decide. We have some open PRs do you think can be landed in 0.18.0 ?

**Comment by tmorehouse** [comment]
@alexsasharegan has a doc update for async modal cancelling, but no PR yet... that could wait until later.

I was going to add `aria-invalid="true"` support on some of the form-inputs, but there is no big rush for that.

**Comment by tmorehouse** [comment]
And also moving some non-common props in the form mixin to the components (issue #542 )

But that can wait as well..  I'm kinda eager to see the new docs live :-)

**Comment by mosinve** [comment]
I have an error with multiple roots in componentdoc.vue

**Comment by tmorehouse** [comment]
@mosinve is that on v0.18.0 or master?

**Comment by mosinve** [comment]
master

**Comment by mosinve** [comment]
i moved last b-card into root div and it works

**Comment by mosinve** [comment]
and there is a typo  `Vue.js docuementation`

**Comment by tmorehouse** [comment]
Yeah... I just moved that from `componentdoc.vue` over to `_component.vue`, which should fix the issue.

**Comment by tmorehouse** [comment]
There are a few typo's (troy-o's) in the docs.

**Comment by mosinve** [comment]
they should stay as easter eggs, or may be fixed?

**Comment by tmorehouse** [comment]
Yeah, they should be fixed probably.

We could create a new temp branch for editing the docs.

**Pull request merged**
