### PR TITLE
fix(docs): Fix console errors and improve `play` directive

### PR DESCRIPTION
**Pull request by jackmu95**
## Description of Pull Request:

This PR addresses several console errors in the docs and improves the `play` directive.
The example name defined in markdown is now omitted for the live example on the docs page.

## PR checklist:

**What kind of change does this PR introduce?** (check at least one)
- [x] Bugfix
- [ ] Feature
- [x] Enhancement to an existing feature
- [ ] ARIA accessibility
- [x] Documentation update
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)
- [ ] Yes
- [x] No

If yes, please describe the impact:

**The PR fulfills these requirements:**
- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `fixes #xxxx[,#xxxx]`, where "xxxx" is the issue number)
- [ ] The PR should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] PR titles should following the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. "fix(alert): not alerting during SSR render", "docs(badge): Updated pill examples, fix typos", "chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**
- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] New/updated tests are included and passing (if required)
- [ ] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives 
- [ ] ARIA Accessibility has been taken into consideration (does it affect screen reader users or keyboard only users? clickable items should be in the tab index, etc)

**If adding a new feature, or changing the functionality of an existing feature, the PR's description above includes:**
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by tmorehouse** [comment]
Looks awesome!

I wonder if we should maybe give the editor a red outline if there is an error during compilation, or maybe show an error in the rendered live example (or below the render)?  Maybe just a simple error like javascript compile error, or template compile error?

Or would that be too cumbersome?

Overall this is a great fix!

**Comment by jackmu95** [comment]
An error indicator or even output would be an awesome addition. I will look into that later on.

The Playground definitely needs some love. I'am going to take a further look into it after this PR has shipped.

**Comment by tmorehouse** [comment]
Excellent...

just taking a boo at the playground now... I can see one simple improvement (updating the localstorage after compilation, rather than before)

**Comment by jackmu95** [comment]
I've added a super simple error indication but I'am quite happy with it :)

**Comment by tmorehouse** [comment]
Looks good!  all ready to merge?

**Comment by jackmu95** [comment]
Yes, looks good to me.

**Pull request merged**
