### PR TITLE
new b-form-input-static component

### PR DESCRIPTION
**Pull request by tmorehouse**
Added a standalone `<b-form-input-static>` component, and refactored `<b-form-input>` to use the new component when `static` prop is `true`

### CODE REVIEW

**Comment by pi0** [comment]
I think now it is safe to remove `staticValue`  and just allow using `value` prop. Also we can add a default slot inside `<p>` like this: `><slot></slot></p>` so users have ability to more customizations

**Comment by tmorehouse** [comment]
The formatter wouldn't get called on the static-input though, so the raw value would be shown.   But maybe it isn't needed in the static-input?

**Comment by tmorehouse** [comment]
@pio, Just realized I was missing the `.vue` extension on the bFormInputStatic component import in form-input.vue

**Comment by tmorehouse** [comment]
PR #293 fixes missing component extension

**Pull request merged**
