### PR TITLE
Add default b_UID to dropdown

### PR DESCRIPTION
**Pull request by tmorehouse**
Assigns a default `b_UID` to the dropdown if `id` not specified in props.

### CODE REVIEW

**Comment by SirLamer** [comment]
Solid suggestion, I will add the same to Popover

**Comment by tmorehouse** [comment]
I wonder if most components should have a default b_UID added to the outer container element?

**Comment by SirLamer** [comment]
Yeah I agree, this is a really clean solution, however Popover specifically is my pet. ;-)

**Comment by tmorehouse** [comment]
@pi0,  what do you think about adding default `b_UID`s (if no ID provided) to all components?

**Comment by tmorehouse** [comment]
Regarding default b_UIDs, I have created issue #281 for discussion.

**Comment by tmorehouse** [comment]
I'm going to switch how the IDs are assigned in this, to make sure they are rendered after mounted/updated.

**Comment by tmorehouse** [comment]
I will close this and refactor when in the lifecycle the ID is assigned

**Pull request closed without merging**
