### PR TITLE
feat(b-form-group): add `content-cols` props and scoped `default` slot (closes #6095, #6118)

### LINKED ISSUE #6095: Description on form radio button group not accessible to screen reader
### Describe the bug

The description for a b-form-group containing a b-form-radio-group is not accessible to the ChromeVox screen reader.

### Steps to reproduce the bug

1. Activate ChromeVox (Ctrl+Alt+Z)
2. Go to https://jsfiddle.net/qw394szo/1/
3. Use the tab key to select the radio button group
4. ChromeVox reads "option a, radio button unselected; 1 of 2; Radio button group; Label; Form;"

### Expected behavior

ChromeVox should have read "option a, radio button unselected; 1 of 2; Radio button group; Label; Form; **Description**"

### Versions

**Libraries:**

- BootstrapVue: 2.19.0
- Bootstrap: 4.5.3
- Vue: 2.6.12

**Environment:**

- Device: Chromebook
- OS: ChromeOS
- Browser: Chrome
- Version: 86

### Demo link

https://jsfiddle.net/qw394szo/1/

### Additional context

Similar to https://github.com/bootstrap-vue/bootstrap-vue/issues/5918#issuecomment-734434869

### LINKED ISSUE #6118: Allow setting "control-cols" on horizontal form group
### Is your feature request related to a problem? Please describe...

I'm creating forms using the `<b-form-group>` element wrapper. While the label width is adjustable via the `label-cols` parameter, there is no parameter for the control element width. Setting the control element width via e.g. `class="col-3"` results in two nested divs with class `col` and thus unwanted padding left/right.

### Describe the solution you'd like

Make the control element width adjustable on the `<b-form-group>` via `control-cols`.

### Describe alternatives you've considered

- Adding `class="col-3 px-0"` to the control element
- Using utility classes on the control element `w-50`
- Setting the width [via inline-styles](https://github.com/bootstrap-vue/bootstrap-vue/issues/4324#issuecomment-548038526)

### PR DESCRIPTION
**Pull request by jackmu95**
### Describe the PR

This PR adds support for `content-cols` props to `<b-form-group>`.
They behave similar to `label-cols` props.

The `default` slot is now also scoped with `{ ariaDescribedby, descriptionId, id, labelId }`.
A `aria-describedby` attribute with the value of `ariaDescribedby` should be assigned to all form controls in the `<b-form-group>` when there are multiple.

Assigning `aria-describedby` to the form controls directly is the most supported way by screenreaders:
https://russmaxdesign.github.io/accessible-error-fieldset/

Closes #6095.
Closes #6118.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix (fixes a boo-boo in the code) - `fix(...)`, requires a patch version update
- [x] Feature (adds a new feature to BootstrapVue) - `feat(...)`, requires a minor version update
- [x] Enhancement (augments an existing feature) - `feat(...)`, requires a minor version update
- [ ] ARIA accessibility (fixes or improves ARIA accessibility) - `fix(...)`, requires a patch or minor version update
- [ ] Documentation update (improves documentation or typo fixes) - `chore(docs)`, requires a patch version update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe since breaking changes require a minor version update)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc.). **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type (patch or minor).**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates
- [ ] Includes component package.json meta section updates (prop, slot and event changes/updates)
- [ ] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (required for new features and enhancements)
- [ ] Existing test suites are passing
- [ ] CodeCov for patch has met target (all changes/updates have been tested)
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by jackmu95** [comment]
@ccsaposs Can you take a look at the deployment preview and check out if the `<b-form-group>`'s with multiple form controls behave not like the should with ChomeFox.

**Comment by jackmu95** [comment]
@ccsaposs Just use the Playground or edit one of the examples on the Form Radio documentation page by double-clicking on the code and edit a description.

Please make also sure the label is correctly announced.

**Comment by ccsaposs** [comment]
When I use ChromeVox, it reads the label but it does not read the description.  Tested on both the playground & by editing one of the examples.

**Comment by jackmu95** [comment]
@ccsaposs Can you please test this example:
https://russmaxdesign.github.io/accessible-error-fieldset/method4.html

When this doesn't work either I don't know how to make ist work with ChromeVox.

**Comment by ccsaposs** [comment]
I tried testing the bootstrap deploy preview again and ran into this behavior:
The first time I entered the radio button group, it read the description and then the label.  When moving around between options in the radio group, it would only read the description and not the label.

I ran into the same behavior when testing the example you linked.

I believe the expected behavior for ChromeVox is to only read the label and description when first entering the fieldset.  I was able to get this behavior by moving the aria-describedby attribute to the fieldset instead of the individual radios.

**Comment by jackmu95** [comment]
@ccsaposs Thanks for the investigation!

Based on this results, the current implementation ist the one that works best for most of the screen readers:
https://russmaxdesign.github.io/accessible-error-fieldset/index.html

**Comment by ccsaposs** [comment]
> @ccsaposs Thanks for the investigation!
> 
> Based on this results, the current implementation ist the one that works best for most of the screen readers:
> https://russmaxdesign.github.io/accessible-error-fieldset/index.html

Got it, thank you for sharing that resource.

I would like to point out that the tests in that resource aren't complete.  Specifically, they don't account for the confusing behavior that comes from reading the description but not the label when navigating between items in a radio group.  It seems to me like that behavior is not what screen reader users would expect.  Based on that logic, method 4 should not be given a "pass".

However, I have very little experience with screen readers, so take that with a grain of salt.

**Comment by jackmu95** [comment]
@ccsaposs I think I will leave this as if for now.

We can always improve this if we have more information on how to do it.

**Pull request merged**
