### PR TITLE
Refactoring, fix element rendering as invisible when hidden

### PR DESCRIPTION
**Pull request by SirLamer**
Per https://github.com/bootstrap-vue/bootstrap-vue/issues/271

### CODE REVIEW

**Comment by SirLamer** [comment]
@pi0 Can you please check the test failure? That looks like something external to this PR. I am not merging yet.

**Comment by pi0** [comment]
@SirLamer unfortunately this is happening during some package installation which fails as it downloads from github in build step. Will try to upgrade yarn to see if problem happens or not.

**Comment by pi0** [comment]
Not merging. Merge when you where ready :)

**Comment by SirLamer** [comment]
OK it passes now.

**Pull request merged**
