### PR TITLE
feat: added support for custom transition (closes #5415)

### LINKED ISSUE #5415: Ability to add custom transitions to components
### Is your feature request related to a problem? Please describe...

Bootstrap is in our life for so long. Due to it's customizability we are still using it through modify CSS. However, transitions are still the same old fade-in fade-out.

### Describe the solution you'd like

Giving option to wrap transition tag  around a component or any other way to integrate custom transition(Where using CSS is not possible)

### Describe alternatives you've considered

Currently, I am using a directive to add a custom transition to alert component but it's not enough for all components and not ideal for complex animations.

### Additional context

None

### PR DESCRIPTION
**Pull request by jd-0001**
### Describe the PR

This PR provides prop `transition` from which we can add custom transition besides default fading transition.

This is because as I described in my issue https://github.com/bootstrap-vue/bootstrap-vue/issues/5415 we wanted new transitions for BSV and for this I am just submitting transition support for an only single component. If this is how we should provide custom transitions then I will be adding custom transitions in more possible components.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix (fixes a boo-boo in the code) - `fix(...)`, requires a patch version update
- [x] Feature (adds a new feature to BootstrapVue) - `feat(...)`, requires a minor version update
- [ ] Enhancement (augments an existing feature) - `feat(...)`, requires a minor version update
- [ ] ARIA accessibility (fixes or improves ARIA accessibility) - `fix(...)`, requires a patch or minor version update
- [ ] Documentation update (improves documentation or typo fixes) - `chore(docs)`, requires a patch version update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe since breaking changes require a minor version update)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type (patch or minor).**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates
- [x] Includes component package.json meta section updates (prop, slot and event changes/updates)
- [ ] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (required for new features and enhancements)
- [ ] Existing test suites are passing
- [ ] CodeCov for patch has met target (all changes/updates have been tested)
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by jd-0001** [comment]
Hi @jackmu95 If this is the correct approach to provide custom transition, I would like to add custom transition support in other components as well. I just added this to a single component for review.

If this is valid please let me know if I can add this feather to other components?

**Comment by jackmu95** [comment]
@jd-0001 The `BVTransition` component supports a `transProps` property which is meant for user-provided custom transition properties. You should use this prop instead of overwriting the entire component.

**Comment by jd-0001** [comment]
Hi @jackmu95,
I updated the PR. Is this what you were trying to suggest?

Awaiting your response.

**Comment by jackmu95** [comment]
I've looked a bit further into this and the problem ist that until https://github.com/vuejs/vue/issues/9986 is resolved or we find a way to work around it, we can't support components like `<b-modal>` and `<b-sidebar>` for custom transitions.

Enabling this for some and not all components is kinda a deal-breaker for me.

**Comment by jd-0001** [comment]
Hi @jackmu95,

Thanks for reviewing. Will this get resolved in Vue3 support of this framework?

Should close this or keep it open?

Awaiting your response.

Regards.

**Comment by jackmu95** [comment]
@jd-0001 Let's leave it open.
I will investigate a bit more after the next release.

**Pull request closed without merging**
