### PR TITLE
chore(table): break out code into helper modules and add additional tests

### PR DESCRIPTION
**Pull request by tmorehouse**
## Description of Pull Request:

Breaking out helper functions into modules to make `<b-table>` a bit easier to maintain, and test individual helper functionality.

Also always adds ARIA roles to all elements rendered (not just in stacked mode), in case user overrides CSS semantics (i.e. via `display: grid`).

TO DO (in a future PR):
- Test stacked layout
- Test basic styling classes
- Test responsive layout
- Test filtering (including filter functions)
- Migrate filtering into mixin
- Migrate pagination into mixin
- Migrate items into mixn

## PR checklist:

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Enhancement to an existing feature
- [x] ARIA accessibility
- [ ] Documentation update
- [x] Other, please describe: code organization

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (i.e.
      `fixes #xxxx[,#xxxx]`, where "xxxx" is the issue number)
- [x] The PR should address only one issue or feature. If adding multiple features or fixing a bug
      and adding a new feature, break them into separate PRs if at all possible.
- [x] PR titles should following the
      [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e.
      "fix(alert): not alerting during SSR render", "docs(badge): Updated pill examples, fix typos",
      "chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` is generated
      from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and
      event changes)
- [x] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives
- [x] ARIA Accessibility has been taken into consideration (does it affect screen reader users or
      keyboard only users? clickable items should be in the tab index, etc)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a
      suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by tmorehouse** [comment]
Going to be adding a few more tests on sunday.

**Comment by tmorehouse** [comment]
TODO: Could separate provider function stuff into a separate module, as well as filter function stuff.

**Comment by lianee** [comment]
[commenting](https://github.com/bootstrap-vue/bootstrap-vue/pull/2805/commits/ab4f073877b4707d3ab7ac955685b096384d1bf3) `user-select: none;` in _table.css breaks selectable feature, and since it only applies to tables in selectable state (especially range mode), it shouldn't cause issue with the newly added #2801

**Comment by tmorehouse** [comment]
Hmmm... but user select disables the ability to select text.  Maybe this class should only be applied if there is at least one row selected first? and removed when no rows are selected?

**Comment by lianee** [comment]
Yes, it is the desired behavior of user-select.
I'm not sure of the usability of text selecting, when a table is in selectable state. This state makes the table an active UI object, like a button or a link, something probably not suitable for text selection.
Anyway, while it doesn't matter for single or multi modes, the lack of it in range mode disables shift-click because the recent 'text selected' abort of row-clicked, then making it impossible to do a shift-click range selection.
If you prefer to disable user-select only for range mode, then perhaps we could add a selector indicating the select-mode, so we could use a more specific CSS selector.

**Comment by tmorehouse** [comment]
@lianee maybe a new class should be added to `b-table` `table` element, only when at least one row has been selected (i.e. b-table-selecting') which applies the `user-select: none;` (or a dynamic style added to all TRs)

```js
 computed: {
    isSelecting() {
      return this.selectable &&
        this.selectMode === 'range' &&
        this.selectedRows &&
        this.selectedRows.some(v => v)
    }
 }
```

And if `this.isSelecting` returns true, then the class `b-table-selecting` is added to the table element.

**Comment by lianee** [comment]
I guess the 2 classes (selecting and mode) should be added, making it more versatile, then users could override the default behavior just with CSS.

**Comment by tmorehouse** [comment]
@lianee check out PR https://github.com/bootstrap-vue/bootstrap-vue/pull/2865

**Comment by lianee** [comment]
@tmorehouse You were too fast for me ;)
I would have decoupled the two things with a b-table-selecting and a b-table-select-{mode} classes, but I'm ok with your solution, thank you.

**Comment by tmorehouse** [comment]
We could stilldo so.ethjng similar forthe other two modes (adding classes when section is active).. just no user-select none.

And maybe add classes to say which mode is in use.

**Comment by lianee** [comment]
I don't know how to suggest changes to your PR, but what I was thinking is:
table.js:
```
'b-table-selecting': this.isSelecting,
[`b-table-select-${this.selectMode}`]: true
```
mixin-selectable.js:
```
    isSelecting() {
      return (
        this.selectable &&
        this.selectedRows &&
        this.selectedRows.some(Boolean)
      )
    }
```
_table.scss:
```
  &.b-table-selecting.b-table-select-range {
    > tbody > tr {
      user-select: none;
    }
  }

```
leaving the user the choice to apply user-select in any mode he wants, whether or not there is a selection in process.

But as I said, your solution works ok, range mode is now working as it should.

**Comment by tmorehouse** [comment]
Could you put thisas a comment on the PR? 

I can add it in later today.

**Pull request merged**
