### PR TITLE
fix (form input) input reactivity

### LINKED ISSUE #817: b-form-input does not update reactively after first input
Hi. My problem is as follows. I have this in my template:

```html
<b-form-input type="text" v-model="someField"></b-form-input>
<b-button @click="add">Add<b-button>
```
And a method:
```js
add () {
    this.someField = 'someValue'
}
```
`this.someField` is initially set to `''` in `data`.

What happens: if i click on "Add" before inputing anything to the field, field starts to display "someValue". But if I input anything there and then click the button, field continues to display what I've entered. Vue Devtools inspector shows that `this.someField` is in fact updated to contain `'someValue'`, but `$0.value` in Chrome Devtools shows that actual DOM element still contains the value I've entered, _not_ the one I've set programatically.

If I use raw `<input v-model="someField"/>` in my template, everything works as expected.

Is this a bug in bootstrap-vue or I'm just doing something wrong?

See demonstration in fiddle: https://jsfiddle.net/nz23f2kg/

### PR DESCRIPTION
**Pull request by mosinve**
Supposed to fix #817

### CODE REVIEW

**Comment by alexsasharegan** [comment]
Would you be open to trying a refactor with v-model? From what I hear about watchers, it would be a more efficient solution.

**Comment by mosinve** [comment]
v-model is just a sugar for :value/@input combination

**Comment by alexsasharegan** [comment]
Agreed, but it's clear that using that works on a native input element. I'm really just looking to see if it's possible to avoid a watcher.

**Comment by mosinve** [comment]
I'll try locally, but watcher is really working solution currently

**Comment by mosinve** [comment]
```
> - <input :type="isTextArea ? null : type" v-model="localValue">:
> v-model does not support dynamic input types. Use v-if branches instead.
```

**Comment by alexsasharegan** [comment]
That should be a `component` tag then. `<component :is="isTextArea ? 'textarea' : 'input' />`

**Comment by tmorehouse** [comment]
Users can make input either a text area, or input with types (text, number, date, password, etc).

So I think it is complaining about input with a dynamic `type` attribute

**Comment by tmorehouse** [comment]
So I think the watcher is the easiest solution for now.

**Comment by alexsasharegan** [comment]
Agreed!

**Comment by mosinve** [comment]
This works at earlier versions somehow... somewhat changes breaks and i dnt get what changes... and why `:value=value` doesn't work in internal input

**Comment by mosinve** [comment]
with this watcher we even can remove `:value=value` from template. It still will work

**Comment by alexsasharegan** [comment]
Well, thanks for giving it a shot, @mosinve! I learned something new about v-model in the process.

**Comment by tmorehouse** [comment]
I'll merge in your changes to the 1.x branch as well.

**Pull request merged**
