### PR TITLE
fix: properly handle HTML props render order (closes #5363)

### LINKED ISSUE #5363: &nbsp; not interpreted in Jumbotron lead-html
The following does not render the `&nbsp;` as a non-breaking space, despite being in the `-html` attribute.

    <b-jumbotron header="test" 
                 lead-html="non&nbsp;breaking">
     </b-jumbotron>

- BootstrapVue: 2.14.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

Demo link: https://codepen.io/jezmck/pen/gOajeGL

### PR DESCRIPTION
**Pull request by jackmu95**
### Describe the PR

This PR fixes that the `head-html` and `lead-html` props for `<b-breadcrumb>` work properly.

It also ensures the following rendering order for all components:

1. slots
2. html prop
3. text prop

Closes #5363.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix (fixes a boo-boo in the code) - `fix(...)`, requires a patch version update
- [ ] Feature (adds a new feature to BootstrapVue) - `feat(...)`, requires a minor version update
- [ ] Enhancement (augments an existing feature) - `feat(...)`, requires a minor version update
- [ ] ARIA accessibility (fixes or improves ARIA accessibility) - `fix(...)`, requires a patch or minor version update
- [ ] Documentation update (improves documentation or typo fixes) - `chore(docs)`, requires a patch version update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe since breaking changes require a minor version update)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type (patch or minor).**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates
- [ ] Includes component package.json meta section updates (prop, slot and event changes/updates)
- [ ] Includes any needed TypeScript declaration file updates
- [x] New/updated tests are included and passing (required for new features and enhancements)
- [x] Existing test suites are passing
- [x] CodeCov for patch has met target (all changes/updates have been tested)
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by jackmu95** [comment]
@tmorehouse I think we have to look at some other components with HTML props an apply the same logic. With that logic in place, we don't need the `stripTags()` util which is a nice side-effect.

**Comment by tmorehouse** [comment]
Not sure if we should change the order of what takes precedence...  I think slots should take precedence over html/text props (if the slot is present), Otherwise it could be construed as a breaking change.  So component docs mention if the slot takes precedence over the props (or vice versa).

Also, when using DOM props, we would avoid placing them on components that are not functional (or functional components that render a full component as their child).

**Comment by jackmu95** [comment]
> Not sure if we should change the order of what takes precedence... I think slots should take precedence over html/text props (if the slot is present), Otherwise it could be construed as a breaking change. So component docs mention if the slot takes precedence over the props (or vice versa).
> 
> Also, when using DOM props, we would avoid placing them on components that are not functional (or functional components that render a full component as their child).

I got that wrong in the description. This PR ensures that order and avoids some hacks we did before (render additional `<span>` etc.).

**Comment by jackmu95** [comment]
I will make sure that we don't use `domProps` on regular components.

**Pull request merged**
