### PR TITLE
[docs] components - show if prop is required

### PR DESCRIPTION
**Pull request by tmorehouse**
Some components have props that are flagged as required.

This PR adds an extra column to props table to show if property is marked as required

Shows `true` is required, otherwise blank (to not clutter table output)

### CODE REVIEW

**Comment by tmorehouse** [comment]
Option: Could show the word 'Yes' instead of `True` for `Required`

**Comment by alexsasharegan** [comment]
Hmm... either is clear, but I think I lean towards "Yes".

**Comment by tmorehouse** [comment]
And should we show 'No' if not required or just a blank?

**Comment by alexsasharegan** [comment]
I like the no clutter approach, but I suppose having the table column empty would look silly. It would be ideal if the column only appears if there is a required prop (then it would show Yes/No).

**Comment by tmorehouse** [comment]
There is the 'invisible' field prop now for `b-table`, which just hides the content of the column (but leaves the space of the column there).

Could get the fields to check if there are any `required`s and set the `invisible` property to `true`

**Comment by alexsasharegan** [comment]
That sounds like cleanest, easiest to understand way.

**Comment by tmorehouse** [comment]
Also switched from word `True` to word `Yes`

**Comment by alexsasharegan** [comment]
Wait, is that... never mind! You just changed it!

**Comment by alexsasharegan** [comment]
I'm gonna say you caught that before committing an official Troy-o

**Comment by tmorehouse** [comment]
LOL

**Comment by tmorehouse** [comment]
Hmmm. Now I am wondering if it might be better to just remove the `required` field from the list of fields rather than just making it invisible and have it take up blank space.

**Comment by tmorehouse** [comment]
The `Required` column will only be rendered if the component has a prop that has a truthy `required`.  And if a prop is required it will show the word 'Yes', otherwise it will be blank.

**Pull request merged**
