### PR TITLE
fix(carousel): uncaught typeerror on empty slides.

### PR DESCRIPTION
**Pull request by bharathvaj1995**
Add extra validation for slides Uncaught TypeError: Cannot set property 'tabIndex' of undefined in pause() function

### CODE REVIEW

**Comment by tmorehouse** [comment]
Could you provide a code sample which causes your issue?

**Comment by bharathvaj1995** [comment]
` <template v-for="slide in slides">
        <b-carousel-slide :caption="slide.title" :key="slide.id"
                  :text="slide.tagline"
                  :img-src="slide.cover_image"
        ></b-carousel-slide>
      </template>
<script>
export default {
    data() {
        return {
            slides: []
        };
    },
    created() {
        this.loadSliders();
    },
    methods: {
        loadSliders() {
           // code to fetch slides from the server
            });
        }
    }
};
</script>
`

**Comment by tmorehouse** [comment]
You should probably be using the `mounted()` hook instead of the `created ()` hook in this case, as the carousel has not been mounted in the DOM at `created()`

**Comment by bharathvaj1995** [comment]
It gives me the same error. 
err

**Pull request merged**
