### PR TITLE
Shamus03 patch 1

### PR DESCRIPTION
**Pull request by Shamus03**
### Describe the PR

Add a default value of `false` for the `centered` prop.  I find myself almost always setting this to `true`, so it would be nice to have the ability to set it as a default in my projects, but I cannot without a default value in `config-defaults.js`.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Enhancement
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (if required)
- [ ] Existing test suites are passing
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by tmorehouse** [comment]
The only concern I have with this, is that if someone uses a 3rd party component that makes use of modal, users now need to explicitly use the `v-bind` method to make `centered` false (i.e. `:centered="false"`), as this is a Boolean prop (not one that accepts a string or numeric value). Centered modals have issues with overflowing content on short screens.

Config was mainly meant for things like variants, default labels, etc, and not really for boolean props (which now loose there meaning - i.e. `no-this` or `that`).

Also note that each prop that uses a function as a default slows down the instantiation of the component due to the function overhead processing.

An easier way to achieve what you want would be to create your own extended b-modal component and override the prop:

```js
import { BModal } from 'bootstrap-vue'
export default {
  name: 'MyModal',
  extends: BModal,
  props: {
    centered: {
      type: Boolean,
      default: true
    }
  }
}
```

**Comment by Shamus03** [comment]
Good point.  I was even going to ask why not just make every prop part of the config, but given your concerns I think the drawbacks outweigh the benefits.

I had considered forcing all modals to be centered via css to enforce stylistic consistency, but I hadn’t considered just making an extended component.  I’ll do that instead.

**Comment by Shamus03** [comment]
Unfortunately extending the component doesn't work for the `$bvModal.msgBoxOk` and `$bvModal.msgBoxConfirm` helpers.  That was the main reason I wanted a default!  Any suggestions for how to apply a default to that helper?

**Comment by tmorehouse** [comment]
One could create a default msgBox config object that could be imported into your components, and then merged with any new options:

A file to contain the defaults:
```js
export const msgBoxDefaults = {
  centered: true,
  size: 'lg'
}
```

And in your component:
```js
import { msgBoxDefaults } from 'path/to/defaults'

export default {
  // ...
  methods: {
    showMsgBoxOk() {
      return this.$bvModal.msgBoxOk('Message', {
        ...msgBoxDefaults,
        title: 'MsgBox Title',
      })
    }
  }
}
```

Or you could create a helper method that does the merging for you.

Or create a [Vue.mixin](https://vuejs.org/v2/api/#Vue-mixin) that adds your own instance method:

```js
import Vue from 'vue'

Vue.mixin({
  methods: {
    $myMsgBoxOk(message = '', options = {}) {
       return this.$bvModal.msgBoxOk(message, {
        ...msgBoxDefaults,
        ...options
      })     
    }
  }
})
```
And do this in the main entrypoint of your app. this will add a new $myMsgBoOk method to every Vue instance in your app.

**Pull request closed without merging**
