### PR TITLE
feat(b-drodpown-item-button, b-drodpown-item-button): add `button-class` and `link-class` prop

### PR DESCRIPTION
**Pull request by pburdette**
### Describe the PR

**Reason for this PR:** It would be nice to use utility classes on this button without having to introduce new CSS into a codebase. 

- Adds the `button-class` prop to the `b-dropdown-item-button` component. 
- Adds the `link-class` prop to the `b-dropdown-item` component. 
- Updates `dropdown-item-button.spec.js` with a new test
- Updates `dropdown-item.spec.js` with a new test

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Enhancement
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [x] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] Includes any needed TypeScript declaration file updates
- [x] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] CodeCov for patch has met target
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by beardedpayton** [comment]
@tmorehouse does this seem like a prop that would be okay to add? Wanted to get your opinion before I move onto finishing the rest of the checklist. 🙇

**Comment by tmorehouse** [comment]
@beardedpayton just made a few tweaks, and updated the package.json component meta data to indicate the version the prop was added, as well as description for it.  And added a similar prop for `<b-dropdown-item>`

**Comment by beardedpayton** [comment]
@tmorehouse thanks! I just added a test for the `linkClass` prop as well 👍 

Does this PR need anymore attention?

**Comment by tmorehouse** [comment]
I think it is good as is now :+1:

**Comment by jackmu95** [comment]
Thanks @pburdette!

**Comment by pburdette** [comment]
Thanks @jackmu95 and @tmorehouse 🎉

**Comment by tmorehouse** [comment]
@pburdette BootstrapVue v2.9.0 has been released.

**Pull request merged**
