### PR TITLE
[collapse] Add Accordion support, ARIA, and test suite

### PR DESCRIPTION
**Pull request by tmorehouse**
Adds Accordion support to `b-collapse`.

Collapses can be turned into an accordion by setting the prop `accordion` on the collapse components to a common group identifier name. Uses event `accordion::toggle` emitted on $root to signal other collapses in the group to close

Adds ARIA compliance support to directive `v-b-toggle`

Addresses issue #513 

Includes updated documentation and a test suite

Working example: https://jsfiddle.net/ya15m7dv/

### CODE REVIEW

**Comment by kylemh** [comment]
Does this implementation of an Accordion support nested items? Can I create an Accordion within `<b-card>` components? I tried doing so, but am failing miserably without documentation.

**Comment by mosinve** [comment]
Is this fiddle covers your question? 
https://jsfiddle.net/cihkem/n5rgjvfj/3/

**Comment by kylemh** [comment]
You're the man!

**Comment by mosinve** [comment]
Second example was not saved... Now all ok.

**Pull request merged**
