### PR TITLE
feat(microdata): add html5 microdata 

### PR DESCRIPTION
**Pull request by pimlie**
This is a possible solution for #624. I believe using the `json+ld` variant instead of adding the itemscope attributes is preferable as its less intrusive. 

That said, I was looking at other components who could benefit from microdata but I couldnt find any actually. And as the `json+ld` variant can also be easily implemented by the users themselves, maybe bootstrap-vue does not need to support microdata after all?

### CODE REVIEW

**Comment by tmorehouse** [comment]
What about a generic component that generates a json-ld script tag, which takes an object, or arrays of objects? Which could be used anywhere in the document, rather than making a niche use case on breadcrumb?

**Comment by pimlie** [comment]
Sounds allright with me, _if_ that component can do a bit more then just printing out a json-ld script tag. E.g. see [jsonld](https://github.com/digitalbazaar/jsonld.js) for a nodejs lib that supports converting to different formats etc. Also supporting [signatures](https://github.com/digitalbazaar/jsonld-signatures) would be a nice feature.

Maybe at a later stage we could add integration support in other components like the breadcrump or e.g. a blogpost through a mixin? Those components could define a context which together with the current document results in a valid json+ld doc.

Also see the examples [here](https://json-ld.org/playground/)

**Comment by tmorehouse** [comment]
Another option, since the `b-breadcrumb` component is basically a short'n'sweet generator, would be to simply create your own breadcrumb markup with all the required micro-data on the li's (and content, possibly using the meta tag method).

**Comment by alexsasharegan** [comment]
You can also take a look at the way I've broken out breadcrumbs in the PR branch for functional components as the component may change in v1.0.0: https://github.com/alexsasharegan/bootstrap-vue/tree/feat/functional-components/lib/components

I would like to break up our components like this as much as possible since functional components are cheap. Even non-stateless components like `table` might be able to use functional components for the `thead`, `tbody`, and `tfoot` plus row components.

**Comment by tmorehouse** [comment]
Closing this PR branch as it is stale ad may better be suited to being created as a directive which can be passed an object for configuration/sub-element targetting.

**Pull request closed without merging**
