### PR TITLE
[modal] boolean prop handling

### PR DESCRIPTION
**Pull request by tmorehouse**
Changed `closeOn...` to `noCloseOn...` and `fade` to `noFade` (all defaulting to `false`) for better boolean prop handling *(this is a braking change compared to current usage)*

Tweaked computed ID's to align with other components

Addresses usage issue #423

### CODE REVIEW

**Comment by tmorehouse** [comment]
We can reduce footprint a bit more by removing default of `false` from Boolean props, but would need patch to docs generation to handle showing `false` default for Booleans that have no default (i.e. `null`)

**Comment by tmorehouse** [comment]
Is there a way to include a note in the release info about usage/breaking changes? i.e. that props have been changed?

**Comment by pi0** [comment]
@tmorehouse After release i think you can edit release notes :) If not just provide me the notes.

**Comment by tmorehouse** [comment]
OK Cool, will try that.

**Pull request merged**
