### PR TITLE
feat(b-table): allow field definition properties `filterByFormatted` and `sortByFormatted` accept a formatter function reference (closes #3892)

### LINKED ISSUE #3892: B-Table: Possibility to provide a sort value per field
### Is your feature request related to a problem? Please describe...
I use the BTable component for displaying some data and I have a lot of use cases, where my data items contain a field with a non user friendly internal name. 

```
items: [
    { "internalName" : "internalValue" }
]
```

For displaying the field in the table, I use a formatter function. 

```
fields: [
    {
       key:  "internalName",
       label: 'Label',
       formatter: (value, key, item) => this.dataMap[value].displayName
    }
]
```

I also want to make this field sortable. But sorting this value should be done by a related position/priority field in `this.dataMap[value].position`. This is currently only possible with workarounds that required boilerplate code.

### Describe the solution you'd like
Possibility to provide a sorting value, similiar to the formatter:
```
fields:[ 
 { 
    key: 'internalName',
    label: 'Label',
    sortable: true,
    formatter: (value, key, item) => this.dataMap[value].displayName,
    sortBy: (value, key, item) => this.dataMap[value].position
 }
]
```

### Describe alternatives you've considered

I know that I can provide my own sorting routine via the `sort-compare` option for the table. But this is a big overhead. Because I want the default behaviour with just another value to be used for sorting.

What I currently do is: Formatter function returns sorting value, `sortByFormatted` is set to true. And for displaying the value, I use the corresponding field slot, that translates the internal name to the display name. 
But this way, I always have to define a slot and in general it looks like a dirty solution.

### PR DESCRIPTION
**Pull request by tmorehouse**
### Describe the PR

Allow user to pass a function to field definition properties `filterByFormatted` and `sortByFormatted`

Properties can now be a Boolean (existing functionality) to use field's formatter or not, or a function ref that will format specifically for filtering or sorting.

Closes #3892

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [x] Enhancement
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [x] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [x] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by mschlitz-trux** [comment]
I've been unsuccessful in using this `filterByFormatted` property as a function on a field. If I use a function and add a console.log or debugger, it just never fires.

**Comment by tmorehouse** [comment]
@mschlitz-trux make sure you are using the latest version of BootstrapVue

**Comment by mschlitz-trux** [comment]
@tmorehouse Yes, currently using `"bootstrap-vue": "^2.0.4",`

**Comment by tmorehouse** [comment]
@mschlitz-trux is your method trying to access anything in the `this` context?

**Comment by tmorehouse** [comment]
@mschlitz-trux Could you provide a simple sample of the formatter function you are trying to use in `filterByFormatted`?

**Comment by mschlitz-trux** [comment]
@tmorehouse here's a fiddle:
https://jsfiddle.net/fex4sdvm/

Note that I tried both `filterByFormatted: this.filterUserId,` as well as `filterByFormatted: 'filterUserId',`. Am I doing something wrong?

**Comment by tmorehouse** [comment]
`this` context is not available in `data` if data is not a function.

filterBuFormatted only accepts a boolean (true/false) or a reference to a function (not a function name).

See this fiddle: https://jsfiddle.net/r17nujvo/

**Comment by mschlitz-trux** [comment]
Thank you @tmorehouse I think I'm good now. My jsfiddle just didn't have the proper data format:
```
  data() {
    return {
```

And I just wasn't referencing `this.functionName` directly. I think my original comment I was using it in "string" format, just because that's how the `formatter` was. I know the docs specifically mentions **by reference** but I think it was easier to miss because of how `formatter` worked. 

Thanks for your help! Sorry to muck up this old merged PR. A working in example in the Wiki may help a future user!

**Comment by mschlitz-trux** [comment]
So, just to bump this again, and point out a thing that stumped me at first.

Let's say you have an array of objects that looks like this:

```
[
{ id: 0, firstName: 'Jane', lastName: 'Doe' },
{ id: 1, firstName: 'John', lastName: 'Doe' },
]
```

If you try to setup a field with `key: 'name'`, then your customer `formatter` will work, but it will never trigger your `filterByFormatted`. It seems as-if this relies on matching with a key name on the object itself. If you change to using `key: 'firstName'` and then adjust your code references as needed, it seems to work okay. However, this seems like a workaround.

Thoughts?

**Pull request merged**
