### PR TITLE
feat(b-tooltip, b-popover): allow global `delay` customization

### PR DESCRIPTION
**Pull request by nfriend**
### Describe the PR

Allows the show and hide delay of `b-tooltip` and `b-popover`s to be customized globally.

For example:

```js
import Vue from 'vue';
import BVConfig from 'bootstrap-vue/es/bv-config';
import BootstrapVue from 'bootstrap-vue';

Vue.use(BVConfig, {
  BTooltip: {
    delay: {
      show: 400,
      hide: 100,
    },
  },
  BPopover: {
    delay: 1000,
  },
});

Vue.use(BootstrapVue);
```

These global settings apply to both the directive and component version of `b-tooltip` and `b-popover`.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Enhancement
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [X] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch, **not** the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [X] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [X] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] New/updated tests are included and passing (if required)
- [X] Existing test suites are passing
- [X] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [X] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by tmorehouse** [comment]
Thanks, we just prepared v2.0.0-rc.22 for release, so this will need to wait for the net release (which shouldn't be too far off).

**Comment by tmorehouse** [comment]
@nfriend just realized your not that far from me.  I'm in Saint John, NB.

**Comment by tmorehouse** [comment]
I haven't merged the changelog updates yet, so maybe I can squeeze this PR in before publishing.

**Comment by nfriend** [comment]
> @nfriend just realized your not that far from me. I'm in Saint John, NB.

@tmorehouse Nice!  It's not too often that I run across others from the Maritimes 😄

**Comment by tmorehouse** [comment]
Version 2.0.0-rc.22 has been released.

**Pull request merged**
