### PR TITLE
New component b-button-toolbar

### PR DESCRIPTION
**Pull request by tmorehouse**
Wrapper component for creating toolbars comprised of button-groups and/or input-groups.

Direct children elements should be `b-button-group` and `b-input-group` components.

Allows for optional keyboard navigation by setting prop `keyNav` to `true` (defaults to `false`)

### CODE REVIEW

**Comment by tmorehouse** [comment]
Should I remove the keyboard navigation and toolbar option from b-button-group?

**Comment by pi0** [comment]
I think so. As button-group is just a helper for styling. Also it would be great if you can provide some docs. (Simply copy paste docs/components/button-group as a starting point)

**Comment by tmorehouse** [comment]
Will do.

I'll remove the toolbar option from the `b-button-group`, and all the extra fluff code for key-nav.

**Comment by tmorehouse** [comment]
I've removed the toolbar features of `button-group`.  It should merge OK once the other lint bugs have been resolved.

**Pull request merged**
