### PR TITLE
support for vue router link

### PR DESCRIPTION
**Pull request by qwexvf**
Hi i modified the onclick method to use router with.

this.$emit('click', this.link)

is this for debugging?

### CODE REVIEW

**Comment by pi0** [comment]
@qwexvf Thanks for your contribution :)
I totally agree with that is needed. But we cannot consider every user has and wants using `vue-router`, maybe we can add something like `useRouter` prop to let user enable/disable this feature. Also please note that if we don't use `<router-link>` tags we are missing lot's of things like adding `active` class to current route. Isn't it better to conditionally use `<router-link>` on update when `useRouter` is active ?

**Comment by qwexvf** [comment]
@pi0 thank you!
i agree that we need to use <router-link> tag i totally forgot about it. i think we don't need that change! sorry about this :(

**Comment by pi0** [comment]
@qwexvf  Thanks you back dude :) I'll keep this PR so we can make further works on that.

**Comment by pi0** [comment]
@qwexvf support for vue router link is now partially available. i'll close this PR for housekeeping. Really thanks for your contributions and idea.

**Pull request closed without merging**
