### PR TITLE
chore(docs): dynamic links to alpha or dev branch source files 🔗

### PR DESCRIPTION
**Pull request by alexsasharegan**
Links to the appropriate source file branch based on client url.

### CODE REVIEW

**Comment by alexsasharegan** [comment]
I guess I would need to PR this to alpha too, wouldn't I?

**Comment by tmorehouse** [comment]
Yeah, probably so...  Or just hardcode the link base URL in each branch.

**Comment by alexsasharegan** [comment]
I don't suppose there's any way to read the version tag dynamically and reference an exact commit hash. Then you could see the version source code and not bleeding edge code.

**Comment by tmorehouse** [comment]
Hmmm not sure.

**Comment by tmorehouse** [comment]
Added in detection of component source extension (`.js` or `.vue`)

**Comment by pi0** [comment]
Alpha docs has a completely different structure from the current state. So I think it would be better adding multi-version docs for next releases.

**Pull request closed without merging**
