### PR TITLE
feat(b-button-close): add `content` prop (closes #4527)

### LINKED ISSUE #4527: It is possible to config globally bootstrap-modal close button to be without any content inside?
Hi.
It is possible to config globally bootstrap-modal close button to be without any content inside?
I want to use bootstrap-modal plugin for modals and message info-boxes on my site widget-app.
Site uses bootstrap.
Vue app uses your bundle.
On my site I get used customized layout for modals, and for close buttons I will used font icon version applied with pseudo-selector with css. For this case I removed any content inside close button (just used custom button with data-dismiss="modal").
Demo: https://keenthemes.com/metronic/preview/demo1/components/base/modal.html

My app used same styles, but I don't know how to remove content of close buttons globally on my Vue app.
image
Thanks for any ideas.

### PR DESCRIPTION
**Pull request by jackmu95**
### Describe the PR

This PR adds a `content` prop to the `<b-button-close>` component.
It also adds the prop to the `BButtonClose` settings to make it globally configurable.

A `headerCloseContent` property is also added to the `<b-modal>` component and the `BModal` settings to be able to change the close button content by modal or for all modals globally.

Closes #4527.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Enhancement
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (if required)
- [ ] Existing test suites are passing
- [ ] CodeCov for patch has met target
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by tmorehouse** [comment]
One thing to note is that we used to have SSR mismatch errors when using `&times;` from a prop for some reason (there was a related Vue issue for that, which might be fixed).

When using HTML entities that maps to UTF8 characters (the browser would convert the inner HTML/text to the UTF8 character, and the rehydration process would complain that `×` does not equal `&times;`, even though they are)

**Comment by jackmu95** [comment]
@tmorehouse I currently don't see any SSR mismatch errors.

**Comment by tmorehouse** [comment]
@jackmu95 OK cool... Vue must have fixed the issue with the rehydration process.

**Comment by tmorehouse** [comment]
I might add in an option for passing vNode Array via the message box methods for the button content (via a separate PR)

**Pull request merged**
