### PR TITLE
[WIP] feat(modal): Support multiple modals open at once

### LINKED ISSUE #1513: How to show Modal over a Modal at the same time
**bootstrap-vue** is explicitly checking if any modal is open before opening any modal. If it's found already one open modal then it closes first and then triggers secondary modal to show. 

**How can I show both modals at the same time?** 

I am having the requirement to open modal over a modal. For that, I have defined two `b-modal` with `modal` and `subModal` ref respectively. 

But when I open subModal from modal, it hides the first modal and then opens subModal. Is there any way I can change that behavior and show both modals at the same time?

### LINKED ISSUE #1842: can not open a modal on a modal
Hi,
firstly I click the button A to open first modal 1, on this modal there is another button B,   click button B open another modal 2, but  modal 1 is closed, is that possible, keep modal 1 show than hide. as I hope I can see some information from modal 1 when I do something in modal 2.

- windows 7
- Chrome  66.0.3359.139（release） （32 位）
- v2.0.0-rc.10
Thanks 
William

Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/bootstrap-vue/bootstrap-vue/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/CONTRIBUTING.md)

When asking general "how to" questions:

- Please avoid opening an issue here
- Instead, ask for help on StackOverflow, IRC, or [Slack](https://bootstrap-vue.now.sh/), and also check out the [online documentation](https://bootstrap-vue.js.org)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Version of Bootstrap-Vue that you are using
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/), [JS Bin](https://jsbin.com/), or [JsFiddle](https://jsfiddle.net/) (You can export markup from the [online playground](https://bootstrap-vue.js.org/play) to JS Fiddle)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

Love bootstrap-vue? Please consider supporting our collective:
👉  https://opencollective.com/bootstrap-vue/donate

### LINKED ISSUE #1869: Open modal from modal
Is there any way to open another modal with button in already opened modal.

New modal should be opened over already opened modal.

Example:
There is a button on the page. That button opens modal. Modal has button that opens another modal.

Now when second modal is opened previous one is closed.

```html
<div>
  <b-btn v-b-modal.modal1>Launch demo modal</b-btn>

  <!-- Modal 1 Component -->
  <b-modal id="modal1" title="Bootstrap-Vue">
    <p class="my-4">Hello from modal!</p>
    <b-btn v-b-modal.modal2>Launch demo modal 2</b-btn>
  </b-modal>

  <!-- Modal 2 Component -->
  <b-modal id="modal2" title="Bootstrap-Vue">
    <p class="my-4">Hello from modal!</p>
  </b-modal>
</div>
```

### LINKED ISSUE #1997: Launching a modal inside a modal closes the parent
Simple enough. I'm trying to open a modal inside a modal. You could probably argue against the UI ramifications against this but in our use-case, it's worked well in the past under standard Bootstrap. 

When trying the following little test harness you'll click the button and whole thing closes.

```
let v = new Vue({
	template: `
	<b-modal id="visible_modal" title="visible modal" visible>
		<b-btn v-b-modal.modal1>Launch sub modal</b-btn>

		<b-modal id="modal1" title="Sub-modal!">
			<p class="my-4">Hello from sub-modal!</p>
		</b-modal>
	</b-modal>
	`,
})
v.$mount()
document.body.appendChild(v.$el)
```

This probably something to do with the events because if you set the child to be visible from the start, it displays fine.

```
let v = new Vue({
	template: `
	<b-modal id="visible_modal" title="visible modal" visible>
		<b-btn v-b-modal.modal1>Launch sub modal</b-btn>

		<b-modal id="modal1" title="Sub-modal!" visible>
			<p class="my-4">Hello from sub-modal!</p>
		</b-modal>
	</b-modal>
	`,
})
v.$mount()
document.body.appendChild(v.$el)
```

I've tried hooking on a almost every option to try and see if that fixes it but I just don't know enough about the event chains here to what what they're doing (or why).

### PR DESCRIPTION
**Pull request by tmorehouse**
## Description of Pull Request:

Support multiple modals being opened onscreen at the same time.

Keeps track of the number of modals currently opened to determine if scrollBar adjustments need to be done.

Fixes #1997
Fixes #1869
Fixes #1842
Fixes #1513

_While not officially supported in Bootstrap V4 native_, it has been a popular feature request for Bootstrap-Vue

It requires that the outer div container (containing .modal and .modal-backdrop) have CSS `position: relative` and a z-index of multiples of 2000 (starting at 2000) to ensure proper stacking of the opened modals. This may cause weird layout issues depending on the overflow and positioning settings of the parent container (which is similar to current behaviour).  It is always best to place your `b-modal` outside of constrained elements/components.

## PR checklist:

**What kind of change does this PR introduce?** (check at least one)
- [ ] Bugfix
- [x] Feature
- [x] Enhancement to an existing feature
- [ ] ARIA accessibility
- [x] Documentation update
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)
- [ ] Yes
- [x] No

**The PR fulfills these requirements:**
- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `fixes #xxxx[,#xxxx]`, where "xxxx" is the issue number)
- [x] The PR should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] PR titles should following the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. "fix(alert): not alerting during SSR render", "docs(badge): Updated pill examples, fix typos", "chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**
- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives 
- [x] ARIA Accessibility has been taken into consideration (does it affect screen reader users or keyboard only users? clickable items should be in the tab index, etc)

### CODE REVIEW

**Comment by glmaster123** [comment]
Is this feature ready to use on the dev branch yet? I tried installing like 

> npm install git://github.com/bootstrap-vue/bootstrap-vue.git#dev

but I had no luck. Help?

**Comment by igasparetto** [comment]
It doesn't seem to be in NPM yet.
Please drop a line here when you manage to push it up.
Thanks

**Comment by funkatron** [comment]
Looking to a release for this!

**Comment by tmorehouse** [comment]
Hopefully soon.

**Pull request merged**
