### PR TITLE
chore(docs): inform where a file should be dropped

### PR DESCRIPTION
**Pull request by TitanFighter**
### Describe the PR

Explicitly inform user about the area where a file should be dropped.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Enhancement
- [ ] ARIA accessibility
- [x] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [x] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by tmorehouse** [comment]
PR #3674 is revamping the file input some.  This might be better suited as part of that PR, maybe added as a configuration.

Also not that some browsers do not support dropping files, and the placeholder will change if users drag file(s) over the file input.

**Comment by TitanFighter** [comment]
I just wanted to highlight it in the docs where the drop area is, because for some users it could be unclear. So if they do not know where to drop a file they do not have a chance to see the changed placeholder :) I'm just trying to improve informativity side, not functionality.

**Comment by tmorehouse** [comment]
The placeholder would need a bit of additional work (logic), as users can disable drop functionality (with the `no-drop` prop).  So changing the main placeholder (by default) to include `drop here` would be incorrect if `no-drop` is set.

**Comment by tmorehouse** [comment]
Ah, I just realized that you are just altering the example in the docs (Monday morning here)... not the component itself.

**Pull request merged**
