### PR TITLE
<b-list-group-item> "to" prop should accept [String, Object]

### PR DESCRIPTION
**Pull request by elb**
https://github.com/bootstrap-vue/bootstrap-vue/issues/516

### CODE REVIEW

**Comment by alexsasharegan** [comment]
I feel like we can further abstract some of these link props to be more centralized and reuseable. Thoughts, @tmorehouse ? You recently added the `rel` attribute support. You probably went around hunting for all the components that proxy those link attrs to add that in. Wouldn't it save some Kb and sanity if we pull those into a mixin? Then we can spread those props out in the link mixin itself. Something like `baseLinkProps`.

**Comment by tmorehouse** [comment]
@alexsasharegan Yeah, that might be a good option... link-extras.js mixing maybe?

**Comment by alexsasharegan** [comment]
That sounds good! I feel like that could be a separate PR. This one is a slam dunk, and who knows who will get to this mixin extras idea first.

**Comment by pi0** [comment]
Why not using link mixin?

**Comment by tmorehouse** [comment]
@pi0 `b-list-group-item` currently doesn't use link mixin (as I think because `b-list-group-item` supports more content types than just links).  But it might be an option to move them there.

**Comment by alexsasharegan** [comment]
@pi0 Link mixin contains a lot of extra props that can't be dumped blindly to other components that proxy props down to `bLink`. Currently, you would have to pluck the desired props off the link mixin by name. That's still an improvement as seen with this little bug, but not as much bang for your buck.

**Comment by tmorehouse** [comment]
@alexsasharegan True, when importing the mixin, it could be selective for plucking, although the merge strategy would have to me manual

**Comment by alexsasharegan** [comment]
Although, who knows, maybe all the props can be stuffed into components like this. Ultimately, I was hoping to do this:

```js
import { props as linkProps } from "../mixins/link-extras"

{
  props: {
    ...linkProps,
    // component props
  }
}
```

**Comment by tmorehouse** [comment]
That might be an option for props... but computed props, and other stuff that depend on `this` from other parts of  the mixin would be more difficult to handle.

**Comment by alexsasharegan** [comment]
https://github.com/alexsasharegan/bootstrap-vue/tree/issue/516

**Pull request merged**
