### PR TITLE
[popover] Fix potential private props collision, and init Tether on mounted [Issue #484]

### PR DESCRIPTION
**Pull request by alexsasharegan**
Fix for issue #484 .

As mentioned in the above issue, assigning data props to a vue instance using private notation _(underscore prefix)_ is prohibited by Vue to avoid potential collisions with Vue mechanics. All data props assigned after instantiation are now part of the initial data object and are referenced properly with `this.$data[prop]`.

Tether is now instantiated in the mounted hook to allow transform calculations to be run. This avoids the _"fly-in"_ effect previously experienced due to the popover/tooltip being transformed from `0,0` to its final position.

### CODE REVIEW

**Comment by tmorehouse** [comment]
@alexsasharegan 

what I can do with this is to merge your changes first, and then re-jig my tooltip/popover mixin to use your code.

**Comment by alexsasharegan** [comment]
That sounds fine to me! I feel good about the changes with regards to private pros here, but I'm not sure initializing the tether element in the mounted hook fixes the weird fly-in effect.

**Comment by tmorehouse** [comment]
I'm not completely sure how tether works, but what you have done makes sense, as once it is mounted it should be able to determine the location of the main element.

**Comment by alexsasharegan** [comment]
Exactly. Now :fingers_crossed:

**Comment by tmorehouse** [comment]
Merged :)

**Comment by tmorehouse** [comment]
I've created  new PR #527 that breaks out the common parts to a mixin. Check it out when you get a chance.

**Pull request merged**
