### PR TITLE
[carousel] Fixed this arg in forEach

### PR DESCRIPTION
**Pull request by tmorehouse**
Should address issue #396

### CODE REVIEW

**Comment by pi0** [comment]
foreach is calling inside an arrow function so why we need this ? :))

**Comment by tmorehouse** [comment]
Hmm, this is the only spot I could figure that the error "couldn't get property of Id from undefined" might be coming from.

**Comment by pi0** [comment]
I think function should bound to this. But if this work around works feel free merging it  :)

**Comment by tmorehouse** [comment]
Ah, I found root cause I believe. `querySelectorAll` returns a nodelist, which is not a true array (so it doesn't have all the nice sugar of an Array)

**Pull request merged**
