### PR TITLE
fix: replace sass division with multiplication (fixes #6830)

### LINKED ISSUE #6830: Replace Sass division with multiplication and custom divide() function
### Describe the bug

For sass versions greater 1.32.13 [this breaking change](https://sass-lang.com/documentation/breaking-changes/slash-div) applies to some bootstrap-vue .scss files.

This results in deprecation warnings blocking compilation when using sass > 1.32.13.

[This PR](https://github.com/twbs/bootstrap/pull/34571) resolves the issues in bootstrap v.4.6.1, released a couple of days ago. Do you plan to fix this for bootstrap-vue as well?

### PR DESCRIPTION
**Pull request by z1m1n**
### Describe the PR

Replace Sass division with multiplication (required for sass versions greater than 1.32.13) (fixes #6830)

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix (fixes a boo-boo in the code) - `fix(...)`, requires a patch version update
- [ ] Feature (adds a new feature to BootstrapVue) - `feat(...)`, requires a minor version update
- [ ] Enhancement (augments an existing feature) - `feat(...)`, requires a minor version update
- [ ] ARIA accessibility (fixes or improves ARIA accessibility) - `fix(...)`, requires a patch or minor version update
- [ ] Documentation update (improves documentation or typo fixes) - `chore(docs)`, requires a patch version update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [x] No
- [ ] Yes

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc.). **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type (patch or minor).**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates
- [ ] Includes component package.json meta section updates (prop, slot and event changes/updates)
- [ ] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (required for new features and enhancements)
- [x] Existing test suites are passing
- [x] CodeCov for patch has met target (all changes/updates have been tested)
- [x] The changes have not impacted the functionality of other components or directives
- [x] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

### CODE REVIEW

**Comment by z1m1n** [comment]
@jacobmllr95 Please take a look

**Comment by AdamGaskins** [comment]
I triumphantly updated my bootstrap version to v4.6.1 before realizing bootstrap-vue had sass division too. Came here to make a PR but @z1m1n beat me too it! Thank you 👏🏻

**Comment by jonybekov** [comment]
Can we please merge this PR?

**Comment by sebsonjura** [comment]
get this merged asap please ;)

**Comment by xanf** [comment]
I'm going to merge this today :) Just need to filter-out extra white-space changes :)

**Comment by xanf** [comment]
@z1m1n thank you for your contribution! I'm happy to merge it :rocket:

**Pull request merged**
