### PR TITLE
fix: Remove usage of es2015 Array.prototype.includes

### PR DESCRIPTION
**Pull request by alexsasharegan**
Resolves issue #587

### CODE REVIEW

**Comment by alexsasharegan** [comment]
Darn es2015 is part of my regular language already!

**Comment by tmorehouse** [comment]
Heheh.

**Comment by mosinve** [comment]
maybe better use polyfill suggested at MDN?
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**Comment by alexsasharegan** [comment]
We don't currently have a place for polyfills to be injected, otherwise I'm a polyfill first kind of guy.

**Comment by alexsasharegan** [comment]
And, unfortunately, they can be larger than just using utility methods.

**Pull request merged**
