### PR TITLE
Handle dynamically adding sortable fields after table render (fixes #5520)

### LINKED ISSUE #5520: Clicking on a sortable table column header not working (not sort) when 'sortable' value is dynamic
### Describe the bug

Clicking on a sortable table column header not working (not sort) when 'sortable' value is dynamic. 
Like example below when default **fields** no sortable or sortable is false, then switch `enableSortAble` to true, column header is changed (there are arrow sort icon) but clicking the header column is not sorting the column. 

### Steps to reproduce the bug
```
<template>
  <div>
    <b-form-checkbox switch v-model="enableSortAble">
      <span :class="enableSortAble ? 'font-weight-bold text-primary' : 'text-secondary'">Sortable</span>
    </b-form-checkbox>

    <b-table :items="items" :fields="fields" responsive="sm"></b-table>
  </div>
</template>

<script>
export default {
  data() {
    return {
      enableSortAble: false,
      fields: [
        { key: "last_name" },
        { key: "first_name" },
        { key: "age" },
        { key: "isActive" }
      ],
      items: [
        {
          isActive: true,
          age: 40,
          first_name: "Dickerson",
          last_name: "Macdonald"
        },
        { isActive: false, age: 21, first_name: "Larsen", last_name: "Shaw" },
        { isActive: false, age: 89, first_name: "Geneva", last_name: "Wilson" },
        { isActive: true, age: 38, first_name: "Jami", last_name: "Carney" }
      ]
    };
  },
  watch: {
    enableSortAble(newVal) {
      this.fields = this.fields.map(el => {
        return { ...el, sortable: newVal };
      });
    }
  }
};
</script>
```

### Expected behavior
When click switch button to enable sortable, then clicking on a sortable column header will sort the column.

### Versions
**Libraries:**

- BootstrapVue: 2.15.0
- Bootstrap: 4.5.0
- Vue: 2.6.11

**Environment:**

- OS: Windows 10
- Browser: Chrome 83.0

### Demo link
[https://codesandbox.io/s/bvtable-sortable-g6lyz-g6lyz?file=/App.vue](https://codesandbox.io/s/bvtable-sortable-g6lyz-g6lyz?file=/App.vue)

### PR DESCRIPTION
**Pull request by Hiws**
### Describe the PR

Fixes the issue where dynamically adding a sortable field after the table has been mounted wouldn't be sorting on click.

It appears that if the handlers aren't present when mounted the first time, they can't be added later on a re-render. Even if they're present in the render data.
I personally don't think this is a proper solution, but I'm opening the PR to welcome discussion about a better one.

Before: https://codesandbox.io/s/bvtable-sortable-g6lyz-18rid?file=/App.vue
After: https://codesandbox.io/s/bvtable-sortable-g6lyz-m5q52?file=/App.vue

Closes: #5520

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix (fixes a boo-boo in the code) - `fix(...)`, requires a patch version update
- [ ] Feature (adds a new feature to BootstrapVue) - `feat(...)`, requires a minor version update
- [ ] Enhancement (augments an existing feature) - `feat(...)`, requires a minor version update
- [ ] ARIA accessibility (fixes or improves ARIA accessibility) - `fix(...)`, requires a patch or minor version update
- [ ] Documentation update (improves documentation or typo fixes) - `chore(docs)`, requires a patch version update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe since breaking changes require a minor version update)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [ ] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [ ] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type (patch or minor).**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates
- [ ] Includes component package.json meta section updates (prop, slot and event changes/updates)
- [ ] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (required for new features and enhancements)
- [ ] Existing test suites are passing
- [ ] CodeCov for patch has met target (all changes/updates have been tested)
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

### CODE REVIEW

**Comment by alfianwahid** [comment]
Hi @Hiws 
How if the key in mixin-thead.js  dynamically with combination `isSortable`. It's working too for this case.

https://github.com/bootstrap-vue/bootstrap-vue/blob/abc7aef068e93b7c1ab2190ba44e3756bebdb479/src/components/table/helpers/mixin-thead.js#L124

like key: key+isSortable

**Comment by Hiws** [comment]
> Hi @Hiws
> How if the key in mixin-thead.js dynamically with combination `isSortable`. It's working too for this case.
> 
> https://github.com/bootstrap-vue/bootstrap-vue/blob/abc7aef068e93b7c1ab2190ba44e3756bebdb479/src/components/table/helpers/mixin-thead.js#L124
> 
> like key: key+isSortable

That looks to work as well.
But feels dirty like the other solution.

Will keep looking to see if i can find the actual issue

**Comment by Hiws** [comment]
After looking into it a bit more, it looks like the changes made in this #4825 PR, broke it.

Changing this line back to `on: $listeners`, looks to fix it.
https://github.com/bootstrap-vue/bootstrap-vue/blob/e4d271a58a0c7c36e6333a40e9ecfc9ca933d8b4/src/components/table/td.js#L197

Which, based on my guess means there's something wrong with the cache mixin
https://github.com/bootstrap-vue/bootstrap-vue/blob/v2.15.0/src/utils/cache.js

However, i can't figure out *how* to fix it.
Perhaps @jackmu95 has an idea.

**Comment by jackmu95** [comment]
> After looking into it a bit more, it looks like the changes made in this #4825 PR, broke it.
> 
> Changing this line back to `on: $listeners`, looks to fix it.
> https://github.com/bootstrap-vue/bootstrap-vue/blob/e4d271a58a0c7c36e6333a40e9ecfc9ca933d8b4/src/components/table/td.js#L197
> 
> Which, based on my guess means there's something wrong with the cache mixin
> https://github.com/bootstrap-vue/bootstrap-vue/blob/v2.15.0/src/utils/cache.js
> 
> However, i can't figure out _how_ to fix it.
> Perhaps @jackmu95 has an idea.

Yeah, I noticed that the `$attrs`/`$listener` cache mixins have some problems with reactivity in some cases.
I hope I find time to look into it by the end of next week.

Further investigations are always welcome :)

**Comment by Hiws** [comment]
Gonna close this for now as i can't find a good solution.
Might be worth coming back to after Vue 3 support has been added to see if it has changed anything.

**Pull request closed without merging**
