### PR TITLE
Issue/431

### PR DESCRIPTION
**Pull request by alexsasharegan**
Add support for the v-model as an array with the checkbox component. I would say that supporting this is optional, but it does land directly in the vue docs here: https://vuejs.org/v2/guide/forms.html#Checkbox.

### CODE REVIEW

**Comment by alexsasharegan** [comment]
This is for issue #431

**Comment by tmorehouse** [comment]
Looks like it should work (I think)

**Comment by alexsasharegan** [comment]
Here is the dev fiddle: https://jsfiddle.net/s0Lafhrk/5/

**Comment by pi0** [comment]
Will test locally before next release ;) BTW seems awesome improvement.

**Pull request merged**
