### PR TITLE
Navbar extra components

### PR DESCRIPTION
**Pull request by tmorehouse**
Added two new components for navbar usage:

- `b-nav-text` Creates  `.nav-text` container
- `b-nav-form`  Creates an `.inline-form` form container (using `b-form`)

Addresses components mentioned in #419

### CODE REVIEW

**Comment by tmorehouse** [comment]
Yeah, they are pretty basic components. ;-)

All the content would be placed into the default slots of these components.

**Comment by alexsasharegan** [comment]
Do you even need to pass the `id`? Shouldn't all the normal html props pass along just fine? Like so:

```html
<b-nav-form id="b-form" method="POST" action="https://example.com/api" />
<!-- should render -->
<b-form id="b-form" method="POST" action="https://example.com/api"></b-form>
<!-- and on down to a plain form element -->
```

**Comment by alexsasharegan** [comment]
Take a look at what I mean here: https://jsfiddle.net/gfqucs0z/52/

I didn't even bother with the id prop declaration. Maybe that's bad because of the docs, but maybe not?

**Comment by tmorehouse** [comment]
For things that need an ID for ARIA stuff, it should definitely be placed on the root element.  But not all components required IDs for ARIA.  In all cases, supplying an ID is optional.  ID prop isn't probably needed on the `b-nav-form` component through

**Comment by alexsasharegan** [comment]
Right, all I was trying to demonstrate that when placing an id on the `b-nav-form`, it propagates to the root component. Thus making it superfluous.

**Pull request merged**
