### PR TITLE
fix(b-dropdown): handle issue with touch devices on MacOS using Safari/Firefox (Fixes #4328, #4344)

### LINKED ISSUE #4328: b-dropdown does not close when clicking on the dropdown button (Safari & Firefox Only)
### Describe the bug
When you click on the dropdown button to open the dropdown menu and then you click on the dropdown button again, the dropdown does not close.

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.js.org/docs/components/dropdown
2. Click on **Dropdown Button** in the first example
3. Click on **Dropdown Button** again
4. Note the dropdown menu quickly closes and reopens

### Expected behavior
The dropdown menu should stay closed when the **Dropdown Button** is clicked the second time.

### Versions
**Environment:**
- Device: Mac
- OS: macOS Mojave
- Browser: Safari 12.1.1 & Firefox 70.0

### Additional context
This bug also occurs when `b-dropdown` is used within `b-tabs`. It can be reproduced by copying one of the examples from [Dropdown](https://bootstrap-vue.js.org/docs/components/dropdown) and pasting it into one of the examples in [Tabs](https://bootstrap-vue.js.org/docs/components/tabs).

### LINKED ISSUE #4344: Cannot use color inputs in b-dropdown with Chrome
Hi, first, thanks for a great package! We've got a color input inside a b-dropdown that has stopped working in Chrome since updating to the 2.0.x version. The reason appears to be that Chrome's colour picker opens a new window, which triggers a loss of focus to the dropdown and it, therefore, closes before the user can 

### Steps to reproduce the bug

1. Go to [the JSFiddle example](https://jsfiddle.net/1xkv45nh/)
2. Click on 'Dropdown'
3. Click the color input
4. Choose a color
5. The chosen colour will not be reflected next to 'selected color:' or if you reopen the drodown

### Expected behavior

The dropdown should remain open while the user chooses a colour.

### Versions

**Libraries:**

- BootstrapVue: 2.0.4#
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: 10.14.6
- Browser: Chrome
- Version: 78

### Demo link

[https://jsfiddle.net/1xkv45nh/](https://jsfiddle.net/1xkv45nh/)

### PR DESCRIPTION
**Pull request by tmorehouse**
### Describe the PR

Fixes #4328 
Fixes #4344

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Enhancement
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [ ] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by tmorehouse** [comment]
Awaiting on feedback from issue #4328

**Comment by jackmu95** [comment]
@tmorehouse Tested it in Safari on iOS and it doesn't solve the issue. Will look into it soon.

**Comment by tmorehouse** [comment]
@jackmu95 I wonder if this s a timing thing (or order of events) issue... maybe related to the lick outside handler closing the menu, and then the subsequent button click re-opening the menu

**Comment by tmorehouse** [comment]
Hmmm I just checked, and the clickout (focusout) handler tests for focus moving to the toggler (and ignores it)... so I don't think it is a race condition between the toggle handler and the focusOut handler.

**Comment by jackmu95** [comment]
The problem was that we listened for the `focusout` event of the menu to close it when the element gaining focus wasn't the toggle, the menu or an element inside it.
The detection of the element gaining focus was based on the `relatedTarget` given by the `focusout` event. Safari and some other browsers don't implement that properly and return `null` instead.

I've moved the close detection back to a document-wide `click-out` and `focusin` listeners.

@achen116 Can you confirm that the new deploy preview works for you?

**Comment by tmorehouse** [comment]
@jackmu95 still need to wait for the deploy-preview to build... for some reason it didn't get triggered

**Comment by tmorehouse** [comment]
@achen116, can you try out the deploy preview again now? https://deploy-preview-4329--bootstrap-vue.netlify.com/

**Comment by achen116** [comment]
@tmorehouse @jackmu95 Confirming it works in both Safari & Firefox on Mac! Thanks for resolving that issue so quickly 🎉

**Comment by tmorehouse** [comment]
@achen116 could you test out https://deploy-preview-4340--bootstrap-vue.netlify.com/ as well?

It has a slightly different fix for the issue

**Comment by achen116** [comment]
@tmorehouse Sure, I just tested it and am experiencing the bug again on https://deploy-preview-4340--bootstrap-vue.netlify.com/ on both Safari & Firefox; the dropdown will not close.

**Comment by tmorehouse** [comment]
@achen116 good to know.  Thanks!

**Comment by achen116** [comment]
No problem! 👍

**Comment by jackmu95** [comment]
Closed in favor of #4340.

**Comment by tmorehouse** [comment]
@jackmu95 we're back to a navbar issue now.... with nav-item's after a dropdown menu not running their click handler:

```html
  <b-navbar toggleable="" type="dark" variant="info">
    <b-navbar-brand href="#">NavBar</b-navbar-brand>
    <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>
    <b-collapse id="nav-collapse" is-nav>
      <b-navbar-nav>
        <b-nav-item href="#" @click="console.log('Top Navlink clicked')">Top Link</b-nav-item>
      </b-navbar-nav>
      <!-- Right aligned nav items -->
      <b-navbar-nav class="ml-auto">
        <b-nav-item-dropdown text="Lang" right>
          <b-dropdown-item href="#">EN</b-dropdown-item>
          <b-dropdown-item href="#">ES</b-dropdown-item>
          <b-dropdown-item href="#">RU</b-dropdown-item>
          <b-dropdown-item href="#">FA</b-dropdown-item>
        </b-nav-item-dropdown>

        <b-nav-item-dropdown right text="User">
          <b-dropdown-item href="#">Profile</b-dropdown-item>
          <b-dropdown-item href="#">Sign Out</b-dropdown-item>
        </b-nav-item-dropdown>
        <!-- this click handler will not run if any of the above dropdowns are open -->
        <b-nav-item href="#" @click="console.log('Bottom Navlink clicked')">Bottom Link</b-nav-item>
      </b-navbar-nav>
    </b-collapse>
  </b-navbar>
```

If you have one of the dropdowns opened, and click the bottom link, you will see it's click handler doesn't run due to the menu closing an changing the position of the navlink before the click happens

**Pull request merged**
