### PR TITLE
[generate-id.js] Remove mixin

### PR DESCRIPTION
**Pull request by tmorehouse**
Remove unused mixin generate-id.js

### CODE REVIEW

**Comment by tmorehouse** [comment]
Yay!  Nothing complained when it was removed :-)

**Comment by alexsasharegan** [comment]
A good test is to just run `npm run docs-dev` and see if the nuxt app loads without any errors.

**Comment by tmorehouse** [comment]
I'll leave the branch around just in case.... :wink:

**Comment by alexsasharegan** [comment]
The only "error" I got 😉 
image

**Comment by tmorehouse** [comment]
I wonder which file caused that error....

**Comment by alexsasharegan** [comment]
No, that's because I was testing the deprecation warnings in the playground!

**Comment by alexsasharegan** [comment]
Went through and loaded every docs page—it all looks good!

**Comment by tmorehouse** [comment]
We'll probably need to update some of the fiddles...

**Comment by alexsasharegan** [comment]
We should try and open up issues for that as a help wanted newcomers contrib

**Comment by alexsasharegan** [comment]
Open source that 💩 !

**Pull request merged**
