### PR TITLE
Add Vuelidate form validation example

### LINKED ISSUE #171: Integration with form validation plugins (Example)
Planing a validation mechanism in future for form components ? 
It is a questio  !

### PR DESCRIPTION
**Pull request by robcresswell**
This patch adds a new document that suggests form validation plugins for use
with Bootstrap-Vue. Included is a reference to Vuelidate and a basic
example that highlights the interaction between Bootstrap-Vue and
Vuelidate. It's purposefully verbose and basic to show what is
happening, rather than being a complex high level demonstration.

Closes #171

### CODE REVIEW

**Comment by robcresswell** [comment]
This is a WIP. Couple of things I'm unsure on:

- How do the live edit examples work? I looked at https://raw.githubusercontent.com/bootstrap-vue/bootstrap-vue/dev/docs/markdown/reference/size-props/README.md as an example, but I've no idea where `widths.vue` and `heights.vue` come from.

- Is this kind of content layout helpful? I wasn't sure whether it was better like a full example, or a step-by-step. Either way I think what I've proposed is an improvement at least, but I'd like to make it as good as possible.

**Comment by tmorehouse** [comment]
For the live examples, just include a comment with a unique text ending in `.vue`, that triggers the v-play live editor.

**Comment by tmorehouse** [comment]
I'll take a look once i land in a few hours.

**Comment by robcresswell** [comment]
No rush! Enjoy the holidays etc.

**Comment by tmorehouse** [comment]
Might also habe to add the libs to package.json for devDependencies, or add it to the head as a script tag (via nuxt), or a nuxt plugin.

**Comment by robcresswell** [comment]
I'm back from Christmas time now. I'm not familiar with nuxt, so gimme a couple days and I'll figure out how I add these libs and make things work.

**Comment by alexbrand** [comment]
Hey @robcresswell, Thanks for putting this together!

Quick question - I have a bunch of input fields inside a modal, and they come up as red when the modal opens. Ideally I'd like to delay validation until the fields are touched. I have been looking through the Vuelidate docs but nothing jumps out. Any thoughts?

**Comment by alexbrand** [comment]
I was able to work it out using the `dirty` indicator:

```
   <b-form-input id="exampleInput1"
                  type="text"
                  v-model="form.name"
                  :state="($v.form.name.$invalid && $v.form.name.$dirty) ? 'invalid': ''"
                  @input="$v.form.name.touch()"
                  aria-describedby="input1LiveFeedback"
                  placeholder="Enter name" />
```

It's quite verbose though.

**Comment by robcresswell** [comment]
@alexbrand `$error` is a shortcut for `$invalid && $dirty`, you can use: 

```
:state="$v.form.name.$error ? 'invalid': ''"
```

Just as a general note; it's generally preferred to keep questions out of other github issues, so they don't become clogged up and the maintainers don't get spammed with email. The best solution is to try the Bootstrap-Vue slack channel (https://bootstrap-vue.now.sh/), or if you don't feel comfortable with that, open a separate issue.

**Comment by alexbrand** [comment]
@robcresswell Thanks. Sure thing. I think it might be worth including that in the documentation being added in this PR.

**Comment by pi0** [comment]
This is awesome. Thanks for contribution ❤️ We need some tweaks to making it working with docs. Will merge and work on it :)

**Comment by robcresswell** [comment]
@pi0 Sorry I didn't finish getting the docs working for you; wasn't exactly sure how it fit together. Hope I didn't cause you too much extra work. Thanks for looking at it / merging.

**Pull request merged**
