### PR TITLE
feat(b-form-file): add `browse()` method (closes #6577)

### LINKED ISSUE #6577: BFormFile: add browse() method as alias for $refs.input.click()
### Is your feature request related to a problem? Please describe...

I'm migrating from `<input type="file" />` to `<BFormFile />` in a component that sometimes doesn't show the file input (but shows a button instead). So far, clicking the `button` triggers a `click` on the `input`, i.e. opens the `browse` dialog.

### Describe the solution you'd like

It would be nice if the `BFormFile` component would offer a `browse()` method to open the `browse` dialog.

### Describe alternatives you've considered

The method could also be called `click()` to make it easier to migrate from `<input type="file" />`, but `browse()` would be coherent with the `browse-text` prop.

### Additional context

(None.)

### PR DESCRIPTION
**Pull request by caugner**
### Describe the PR

Adds a `browse()` method to `form-file` to open the browse dialog systematically.

Closes #6577.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix (fixes a boo-boo in the code) - `fix(...)`, requires a patch version update
- [ ] Feature (adds a new feature to BootstrapVue) - `feat(...)`, requires a minor version update
- [x] Enhancement (augments an existing feature) - `feat(...)`, requires a minor version update
- [ ] ARIA accessibility (fixes or improves ARIA accessibility) - `fix(...)`, requires a patch or minor version update
- [ ] Documentation update (improves documentation or typo fixes) - `chore(docs)`, requires a patch version update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe since breaking changes require a minor version update)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc.). **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type (patch or minor).**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates
- [ ] Includes component package.json meta section updates (prop, slot and event changes/updates)
- [x] Includes any needed TypeScript declaration file updates
- [x] New/updated tests are included and passing (required for new features and enhancements)
- [x] Existing test suites are passing
- [ ] CodeCov for patch has met target (all changes/updates have been tested)
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by caugner** [comment]
See: https://codesandbox.io/s/bootstrapvue-starter-project-forked-0bijz

**Comment by jackmu95** [comment]
@caugner Could you add a unit test for the new method? :)

**Comment by caugner** [comment]
@xanf This is ready for review (not sure why the tests are still running).

**Comment by caugner** [comment]
Closing, as I'm no longer working for the company that used `bootstrap-vue`.

**Pull request closed without merging**
