### PR TITLE
fix(table): Clear selection when data change

### PR DESCRIPTION
**Pull request by lianee**
## Description of Pull Request:

for array data, change is detected with the items watcher, works ok when changes are huge, added or deleted items for example.
localItems watcher is to be avoided because it is triggered for details
But for remote data (provider function), the watcher is not called, but as we need to call the refresh method anyway, clear selection is made there.
This refresh call could also be used for array data if need greater control.

## PR checklist:

**What kind of change does this PR introduce?** (check at least one)
- [x] Bugfix
- [ ] Feature
- [ ] Enhancement to an existing feature
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)
- [ ] Yes
- [x] No

If yes, please describe the impact:

**The PR fulfills these requirements:**
- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (i.e. `fixes #xxxx[,#xxxx]`, where "xxxx" is the issue number)
- [ ] The PR should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] PR titles should following the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. "fix(alert): not alerting during SSR render", "docs(badge): Updated pill examples, fix typos", "chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**
- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives 
- [ ] ARIA Accessibility has been taken into consideration (does it affect screen reader users or keyboard only users? clickable items should be in the tab index, etc)

**If adding a new feature, or changing the functionality of an existing feature, the PR's description above includes:**
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by tmorehouse** [comment]
Here is the code I was mentioned the other day of for the `computedItems` watcher:

```js
  watch: {
    // ...
    computedItems (newVal, OldVal) {
      // Watch for changes on computedItems and update the v-model
      this.$emit('input', newVal)
      let equal = false
      if (this.selectable && this.selectedRows.length > 0) {
        // Quick check against array length
        equal = isArray(newVal) && isArray(oldVal) && newVal.length === oldVal.length
        for (let i = 0; equal && i < newVal.length; i++) {
          // Look for the first non-loosely equal row, after ignoring reserved fields
          equal = looseEqual(sanitizeRow(newVal[i]), sanitizeRow(oldVal[i]))
        }
      }
      if (!equal) {
        this.clearSelected()
      }
    },
    selectable (newVal, oldVal) {
      // Clear selection if prop selectable changes
      this.clearSelected()
    }
    // ...
  }
```

And this should be the only two places we need to trigger `this.clearSelected()`

**Comment by tmorehouse** [comment]
Was thinking about changes such as show details, or any other dynamic change to the reserved item properties

**Comment by lianee** [comment]
well, there is a good chance that a change in details won't trigger my code, in any case, that's not a performance issue, as your code will run on a few items only, I was just concerned with the length of code, but you surely know better, and if you think it's better, I see no reason for not using that.

PR updated

**Comment by lianee** [comment]
just thinking, even with your checks, there is still a chance that we run into case where changes are not detected (many similar items). In that case, would it hurt to also put a clearSelected in refresh?

**Comment by tmorehouse** [comment]
Was just thinking that it would reduce the number of places that we would need to add in the `this.clearSelected()` call, although it won't hurt to have it in the various watchers (as it will set selectedItems array length to 0, which the computedItems watcher checks first before doing the larger "deep" check)

**Comment by tmorehouse** [comment]
It definitely should be called in the refresh method as you suggest.

**Comment by lianee** [comment]
I'm writing a more comprehensive test case, with details and similar records and I'll play a little with it, and yes, it's likely there are now useless clears, I should tidy it up a bit

**Comment by lianee** [comment]
I also thought at first it is problem, but if the editing produces a sort change (change the last name while sorting on that value), that might goes awok.
need more tests

**Comment by lianee** [comment]
ok, so potential problem is only in array items, since provider always clears.
the edit case I observed was when there was no sorting on the table, with sorting, the selection is cleared (I couldn't find a case when it did not)
so, it seems it is not that big a problem

**Comment by tmorehouse** [comment]
Ok, we can merge, and if any edge case issues crop up, we can create a new issue.

**Comment by tmorehouse** [comment]
In the edge case where there are multiple identical rows, we should suggest that the users include a unique row ID to ensure uniqueness.

**Comment by lianee** [comment]
not even sure of that, when the user will make a change at one of these identical rows, it'll will then be different. I couldn't break it that way

**Comment by tmorehouse** [comment]
I was just thinking of when a row is not edited and sorting changes (or possibly an identical row is deleted), but results in an identical computed items due to the duplicates, the selections may not get cleared.

**Comment by lianee** [comment]
I think I tried these cases already, but I might be wrong:
- identical row deleted: selection is cleared if the resulting rows are different, selection not cleared otherwise, but it is an identical row
- sort change: didn't find a way when that fails
About sorting, I found an interesting thing in my tests: if you try to sort on an object item (like name in the complete table example), that won't work, because toString of an object is undefined. I know that object order is not stable, but JSON.stringify gives much better results than toString in that case

**Comment by tmorehouse** [comment]
We might need to update out recToString/testing methods

**Comment by lianee** [comment]
I stand corrected: I based this remark on the documentation on "Sort-Compare routine", the actual sort routine is stronger... but still gives incorrect results for objects

**Comment by tmorehouse** [comment]
I'll have to take a look at the stringification method (and maybe make it sort property names first)

**Comment by lianee** [comment]
don't waste your time, seems I need a rest, sort works ok on the complete example, so it must be something on my side.
Above all, this has nothing to do with this PR, I'll get back on that if I have something more serious, sorry.

**Comment by tmorehouse** [comment]
No problem.. if we do need to tweak the stringification, we can open a new issue or pr.

So sage to merge this?

**Comment by lianee** [comment]
yes please, before I think of any other stupid thing. I'll then open a PR if needed

**Comment by tmorehouse** [comment]
Crap... I did a merge commit instead of a squash and merge

**Pull request merged**
