### PR TITLE
fix(b-table): b-table sticky header broken if sortable (fixes #6961)

### LINKED ISSUE #6961: b-table sticky header broken if sortable
### Describe the bug

When using `b-table` with the `sticky-header` prop and sortable columns, the stickyness of those columns is broken. 

Changing the example on https://bootstrap-vue.org/docs/components/table#sticky-headers to this, shows the problem:

```javascript
<template>
  <div>
    <b-table sticky-header :fields="columns" :items="items" head-variant="light"></b-table>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        columns: [{ key: 'heading1', sortable: true }, { key: 'heading2', sortable: false }],
        items: [
          { heading1: 'table cell', heading2: 'table cell', heading3: 'table cell' },
          { heading1: 'table cell', heading2: 'table cell', heading3: 'table cell' },
          { heading1: 'table cell', heading2: 'table cell', heading3: 'table cell' },
          { heading1: 'table cell', heading2: 'table cell', heading3: 'table cell' },
          { heading1: 'table cell', heading2: 'table cell', heading3: 'table cell' },
          { heading1: 'table cell', heading2: 'table cell', heading3: 'table cell' },
          { heading1: 'table cell', heading2: 'table cell', heading3: 'table cell' },
          { heading1: 'table cell', heading2: 'table cell', heading3: 'table cell' },
          { heading1: 'table cell', heading2: 'table cell', heading3: 'table cell' },
          { heading1: 'table cell', heading2: 'table cell', heading3: 'table cell' },
          { heading1: 'table cell', heading2: 'table cell', heading3: 'table cell' },
          { heading1: 'table cell', heading2: 'table cell', heading3: 'table cell' }
        ]
      }
    }
  }
</script>
```

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.org/docs/components/table#sticky-headers
2. Double click the live code section
3. Paste in above code
4. Scroll table down to see only one header being sticky

### Expected behavior

All headers should be sticky.

### Versions

**Libraries:**

- BootstrapVue: 2.22.0
- Bootstrap: 4.6.1
- Vue: 2.6.14

**Environment:**

- Device: Any
- OS: Windows, Android
- Browser: Chrome
- Version: 100.0.4896.127

### Demo link

See description above.

### PR DESCRIPTION
**Pull request by m-mohr**
### Describe the PR

My naive approach at fixing #6961 so that b-table sticky header is sticky again.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix (fixes a boo-boo in the code) - `fix(...)`, requires a patch version update
- [ ] Feature (adds a new feature to BootstrapVue) - `feat(...)`, requires a minor version update
- [ ] Enhancement (augments an existing feature) - `feat(...)`, requires a minor version update
- [ ] ARIA accessibility (fixes or improves ARIA accessibility) - `fix(...)`, requires a patch or minor version update
- [ ] Documentation update (improves documentation or typo fixes) - `chore(docs)`, requires a patch version update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe since breaking changes require a minor version update)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc.). **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type (patch or minor).** - Done through GitHub Web so can't change the commit message anymore.

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates
- [ ] Includes component package.json meta section updates (prop, slot and event changes/updates)
- [ ] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (required for new features and enhancements)
- [ ] Existing test suites are passing
- [ ] CodeCov for patch has met target (all changes/updates have been tested)
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by m-mohr** [comment]
Could anyone have a look at this?

**Comment by m-mohr** [comment]
Any news on this? This fixes a regression....

**Comment by VividLemon** [comment]
You should include a test case for this

**Comment by m-mohr** [comment]
I'm not sure how I can cover this with tests, sorry.

**Comment by adsonvinicius** [comment]
I tested here and it's broken when sortable. I had to downgrade to 2.21.2 to make it work again.

**Pull request merged**
