### PR TITLE
feat(compat): add Vue 3 support via @vue/compat, round 2 (fixes #5196) 

### LINKED ISSUE #5196: Vue 3 support
Hi

What is the status of bootstrap-vue and Vue 3? I know Vue 3 is just in beta now. But I see no statement or other on your page if/how/when you are going to support Vue 3.

With kind regards, Johan

### PR DESCRIPTION
**Pull request by xanf**
image

# :question: What is it?
Version of Bootstrap-Vue which works for Vue 2 and Vue 3 (using `@vue/compat`)
Helps people with #5196 

[Demo using Vue 2](https://bootstrap-vue-3.netlify.app/vue2/)
[Demo using Vue 3](https://bootstrap-vue-3.netlify.app/vue3/)

Additionally, it passes all (well, almost all, tiny fraction of tests are disabled because they are irrelevant for vue 3) tests in the test suite (it would be literally impossible to do this migration without a test suite)

This package uses **vue 3 by default**. If you want to run tests, build, etc. using **vue 2** pass `USE_VUE2=1` environment variable

# :exclamation: How is this possible?

The heart of this PR consists of two parts:
* new [vue-test-utils-compat package](https://github.com/xanf/vue-test-utils-compat) which allows us to run old test suite using new Vue (it's like `@vue/compat` but for tests
* Additional [compatibility layer](https://github.com/xanf/bootstrap-vue/blob/vue3-compat-build/src/vue.js#L39-L121) for Vue3 crafted specifically for `bootstrap-vue`

# :wrench: How could I run it?

If you want just to play around - you can clone https://github.com/xanf/bootstrap-vue3-demo which has all required setup. If you want to try it on your own project, there is some setup required.

I'm skipping setup of `@vue/compat`, it is described in [migration guide](https://v3.vuejs.org/guide/migration/migration-build.html#preparations)

You will need to monkey patch your Vue 3 a bit somewhere early in your app: 
```js
  const originalVModelDynamicCreated = Vue.vModelDynamic.created;
  const originalVModelDynamicBeforeUpdate = Vue.vModelDynamic.beforeUpdate;
  Vue.vModelDynamic.created = function (el, binding, vnode) {
    originalVModelDynamicCreated.call(this, el, binding, vnode);
    if (!el._assign) {
      el._assign = () => {};
    }
  };
  Vue.vModelDynamic.beforeUpdate = function (el, binding, vnode) {
    originalVModelDynamicBeforeUpdate.call(this, el, binding, vnode);
    if (!el._assign) {
      el._assign = () => {};
    }
  };
```

See https://github.com/vuejs/vue-next/pull/4121 for details

If your intention is to run your app in `{ MODE: 2 }` (default @vue/compat) you're done. 
If you want to have `{ MODE: 3 }` (so all compats are disabled by default), additional setup is needed:

* if https://github.com/vuejs/vue-next/pull/4974 is not yet merged - you need to build `@vue/compat` build with this fix included. https://github.com/xanf/bootstrap-vue3-demo already has patch inside `patches` folder for that, installed by [patch-package](https://www.npmjs.com/package/patch-package)
* Certain compat flags required to be enabled globally ATM and can't be disabled in this release (which maintains Vue 2 and Vue 3 compatibility): 
  * `GLOBAL_EXTEND`, `GLOBAL_MOUNT` - for using `new Vue` inside `bootstrap-vue`
  * `COMPONENT_FUNCTIONAL`, `RENDER_FUNCTION` 
  * `CUSTOM_DIR` (anywhere where you use bootstrap-vue directive)

If you use `portal-vue` (which is still used for tooltips, etc.) you will need:
  * `GLOBAL_SET`

If you use old (for Vue 2) version of vue-router you will need:
  * `CONFIG_OPTION_MERGE_STRATS`
  * `GLOBAL_PRIVATE_UTIL`
  * `GLOBAL_PROTOTYPE`
  * `INSTANCE_EVENT_HOOKS`
  * `OPTIONS_DESTROYED`
  * `INSTANCE_EVENT_EMITTER`

# :bomb: What might not work

* Docs. I've tried to make `Nuxt` run using newer Nuxt 3, bridge, etc. but it was very problematic. So I wrote a script, which extracted demos from docs and generated https://github.com/xanf/bootstrap-vue3-demo with all demos
* Build. It might or might not work, I didn't have an opportunity to test it yet

# :arrow_upper_right: What's next?
Let's treat this one as "bridge" version
Based on this branch I will create another one, which will be focused solely on full vue 3 compatibility (without using @vue/compat). While this will definitely take time, right now I do not see any major obstacles in gradual migration

# :hugs: That's cool, how could I say "thank you"?
You're welcome, it's all about opensource. However, there are certain things, where your help will be appreciated:

* Help me spread the word about [vue-test-utils-compat](https://github.com/xanf/vue-test-utils-compat). You can [retweet me](https://twitter.com/xanf_ua/status/1461914150897164292) or just drop a link to your friend who could be interested
* Check deployed versions of https://github.com/xanf/bootstrap-vue3-demo (links inside) and report about any issues you find out in Vue 3 version (it is very time consuming to test all possible scenarios)

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix (fixes a boo-boo in the code) - `fix(...)`, requires a patch version update
- [x] Feature (adds a new feature to BootstrapVue) - `feat(...)`, requires a minor version update
- [ ] Enhancement (augments an existing feature) - `feat(...)`, requires a minor version update
- [ ] ARIA accessibility (fixes or improves ARIA accessibility) - `fix(...)`, requires a patch or minor version update
- [ ] Documentation update (improves documentation or typo fixes) - `chore(docs)`, requires a patch version update
- [x] Other: major update

**Does this PR introduce a breaking change?** (check one)

- [x] No (I know it's hard to believe)
- [ ] Yes (please describe since breaking changes require a minor version update)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc.). **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type (patch or minor).**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates
- [ ] Includes component package.json meta section updates (prop, slot and event changes/updates)
- [ ] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (required for new features and enhancements)
- [x] Existing test suites are passing
- [x] CodeCov for patch has met target (all changes/updates have been tested)
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by mariusa** [comment]
What does this need to be merged? Looking forward to restart using bootstrap-vue with vue 3!

**Comment by jd-0001** [comment]
If you visit b-popover-advanced demo and click on button then we get below error:
Screenshot from 2022-02-17 18-19-26


I am also getting the same error in few others area in my project.

Thanks.

**Comment by ankurk91** [comment]
Please merge and publish this PR to npm but with `next` channel, everyone should be able to install and test it.

**Comment by sadeghbarati** [comment]
https://6253cfb04272251095ef217a--clever-dasik-1a4bcc.netlify.app/

just update `@vue/compat`, `@vitejs/plugin-vue` and `@vue/compiler-sfc` and only use vue3 mode
and only use this patch code, not `patch-package` module for patch `@vue/compat`

```js
 const originalVModelDynamicCreated = Vue.vModelDynamic.created;
  const originalVModelDynamicBeforeUpdate = Vue.vModelDynamic.beforeUpdate;
  Vue.vModelDynamic.created = function (el, binding, vnode) {
    originalVModelDynamicCreated.call(this, el, binding, vnode);
    if (!el._assign) {
      el._assign = () => {};
    }
  };
  Vue.vModelDynamic.beforeUpdate = function (el, binding, vnode) {
    originalVModelDynamicBeforeUpdate.call(this, el, binding, vnode);
    if (!el._assign) {
      el._assign = () => {};
    }
  };
```


**Some components are still not run properly**
I did not check most of the components, I only saw these problems

- toast-advanced
- popover-advanced
- bootstrap 5.0.0 (current version 5.1.3 and 5.2.0 is coming) use @popper/core not popper.js is deprecated

**Comment by xanf** [comment]
@sadeghbarati thank you for givin this a try and catching couple bugs!
I'm going to take a look ath them soon

However, rewrite to `bootstrap v5` is totally separate topic

**Comment by sadeghbarati** [comment]
@xanf 

one thing I forgot to mention:
I think the `portal-vue` force this project to use `@vue/compat`? so no point for using vue-demi?
`@vue/compat` performance is same as vue2&3 ?
>Although there is a small performance/size overhead

---

If your team separate vue 2&3 of __bootstrap-vue__ would be so better
because first time I use compat version and [Compatibility ](https://github.com/vuejs/core/tree/main/packages/vue-compat#compatibility-types) table seem
 have many incompatibles and caveats even ssr problem for this project


I do not expect much from you at this time because I am a little aware of the situation you are in now in Ukraine


These are my thoughts ppl can easily contribute and help ur team along:

1. bootstrap-vue & vue 2 & portal-vue & bootstrap 4
2. bootstrap-vue & vue 2 & portal-vue & bootstrap 5
3. bootstrap-vue & vue 3 & builtin Teleport & bootstrap 4
4. bootstrap-vue & vue 3 & builtin Teleport & bootstrap 5

**Comment by sdwru** [comment]
Seems to me that it would be easier to create a separate project for vue3+bootstrap5 instead of creating this frankenstein thing trying to update existing code and be cross compatible.  Leave the current project as is and don't worry about the new project being backwards compatible.  That's my 2 cents anyways.

**Comment by ultimaweapon** [comment]
> Seems to me that it would be easier to create a separate project for vue3+bootstrap5 instead of creating this frankenstein thing trying to update existing code.  Leave the current project as is and don't worry about cross compatibility.  That's my 2 cents anyways.

What about the people that are already using this on their project?

**Comment by sdwru** [comment]
> > Seems to me that it would be easier to create a separate project for vue3+bootstrap5 instead of creating this frankenstein thing trying to update existing code.  Leave the current project as is and don't worry about cross compatibility.  That's my 2 cents anyways.
> 
> What about the people that are already using this on their project?

What about them?  They can keep on using it.

**Comment by ultimaweapon** [comment]
That mean they are going to stuck with Vue 2 forever. They can't upgrade to Vue 3 due to Bootstrap Vue is not compatible and they can't switch to that new library too due to it is Vue 3.

**Comment by sdwru** [comment]
> **That mean they are going to stuck with Vue 2 forever.** They can't upgrade to Vue 3 due to Bootstrap Vue is not compatible and they can't switch to that new library too due to it is Vue 3.

No it doesn't.  It will most likely be just as much work upgrading an existing project to a separate fork of this project than it would be if this project tried to create some frankenstein that tries to be cross compatible.  As it stands now there hasn't been much progress going down the current path for over 2 years now.  People are moving on.  Nobody starting a new project is going to use this.

**Comment by ultimaweapon** [comment]
Well I'm one of the affected users. My current application is large and deeply integrated with Bootstrap Vue and switching it to another framework + Vue 3 in a single shot is a tremendous task. I need this compatible build in order to upgrade my project to Vue 3 as a first step.

**Comment by sdwru** [comment]
> Well I'm one of the affected users. My current application is large and deeply integrated with Bootstrap Vue and switching it to another framework + Vue 3 in a single shot is a tremendous task. I need this compatible build in order to upgrade my project to Vue 3 as a first step.

Like I said, it will be just as much work either way.   Believe it or don't.  If you think that you will be able to just type 'npm upgrade' and your project will magically upgrade to Vue3+Bootstrap 5 or even just Vue3, you are sadly mistaken.

**Comment by ultimaweapon** [comment]
Yes it much work but it can be splitting. Just dealing with Vue 2 to Vue 3 is already a huge amount of task. If we don't have this compatible build it need to fix both Vue 3 and framework compatibility issue in a single upgrade. But if we have this compatible build we can just dealing with Vue 3 first without worrying with framework issues.

**Comment by xanf** [comment]
Let me jump into this discussion and explain my rationale

This "frankenstein" has the only purpose: to allow people iterate while we're [rewriting](https://github.com/bootstrap-vue/bootstrap-vue/issues/6872) `bootstrap-vue` to Vue3 (bootstrap 5 will be addressed later)

This frankenstein also serves second, not-so-obvious support - this potentially will be "reference" rendering which will be used to check that rewrite renders the same HTML as original version

I've heard  "it's easier to do it from scratch" multiple times in my career (and initiated it multiple times). Unfortunately success rate of such efforts was lower than I wanted.  So my strategy is definitely to stand on the shoulder of giants for this rewrite

Let me explain my rationale:

* rewriting Vue2 -> Vue 3 + bootstrap-vue -> `put your favorte alternate implementation here` basically violates main rule "touch one thing at once", because it involves three (Vue3, bootstrap v5 and js). This is pure insanity for any mid- to large-scale project
* `bootstrap-vue` is feature rich. And implementing all these features is identical in terms of complexity no matter if it is rewrite or "from scratch". But keeping compatibility is far more easier if considered from early start
* `bootstrap-vue` has quite good codebase. It might look insane and weird, but it is pretty high quality. I've understood a lot of nuances while working on this MR and now utilizing this knowledge on rewrite

I'm planning to work on this MR release as `bootstrap-vue@compat` within next 3 days, right now deep into `BTable` vue3 version 

Thanks everyone for patience!

**Comment by sdwru** [comment]
Sigh....nobody is suggesting a rewrite from scratch.   (－‸ლ)

There is no reason you can't reuse code when it makes sense to do so.  There is also no reason current projects can't be ported to the new code.  I am simply saying that people should drop this notion of cross-compatibility because I don't see that ending well.  It is just slowing development down even more and making the code that much more of a mess.  There is no reason to believe dropping cross-compatibility will make porting an existing project to new code more difficult either.  It's going to be lots of work regardless.

Vue3 + Bootstrap 5 have too many changes.  People have been asking for an update for over 2 years now and it's just not happening.  Now the current project is far too old for anyone to consider it for new projects.  The project is dying regardless of what happens.

**Comment by xanf** [comment]
@sdwru thank you for taking time to explain your position. I believe the biggest opensource strength (and, well, sometimes, flaw) is that there are many aprroaches, so people can choose the best one for them

Like I said, I see the bootstrap-vue as powerful library with no match between other clones, so I will continue working on bringing Vue3 and Bootstrap5 to it

**Comment by sadeghbarati** [comment]
423c375c2e12c1a708ecc1694e472ff1

**Comment by ultimaweapon** [comment]
Please be patient. @xanf is living in Ukraine, which is currently attacked by Russia.

**Comment by mattsteve** [comment]
There appears to be an incompatibility with how Vue 3 handles template refs.

https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/tabs/tabs.js#L420
https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/tabs/tabs.js#L592

`this.$refs.buttons` ends up pointing to a single button (it's not an array as expected) with the Vue 3 compat, specifically when the title slot is used.

```html
<b-tabs>
    <b-tab active>
        <template #title>
            Test
        </template>
        Hello World
    </b-tab>
</b-tabs>
```

image

**Comment by jakedolan** [comment]
> There appears to be an incompatibility with how Vue 3 handles template refs.

The [v-for Array Refs migration strategy](https://docs.w3cub.com/vue~3/guide/migration/array-refs) seems to work, [for my fork of this branch](https://github.com/jakedolan/bootstrap-vue/tree/vue3-compat-build), with the b-time component which relies on using `ref` in `v-for` similarly to b-tabs. 

It is pretty straightforward to implement, but not sure if there are any pitfalls to the approach. I haven't yet tested this in a build.

**Comment by mattsteve** [comment]
The `getInstanceFromVNode` method requires a development build of Vue 3 compat in order to work. Otherwise, you'll run into issues like popovers not closing.

https://github.com/bootstrap-vue/bootstrap-vue/blob/vue3-compat-build/src/utils/get-instance-from-vnode.js#L4

The library will need to be reorganized to not rely on this function.

**Comment by xanf** [comment]
@mattsteve whoa, thank you. I was considering that, but probably failed in my testing (I'm about `getInstanceFromVNode`)

regarding inherited attributes - that should be easy fixable

## Status update

I understand there is not that much movement here. It's hard for me to find balance between war-related activities (sigh), work and opensource. However I hope to release this MR this month (huge cudos for everyone who is testing)

Also I'm working on finalizing `BTable` (entire one with all features). No code to share yet, just a spoiler:

image

I will release this as soon as BTable will be functional (hope to do this month also). I estimate this as one of the hardest (not the biggest, hello calendar, but hardest) component for rewrite :)

**Comment by see** [comment]
@xanf Is there any progress? If not, I plan to use my spare time to develop a new version for vue3 based on this repository

**Comment by xanf** [comment]
@see https://github.com/bootstrap-vue/bootstrap-vue/pull/6905#issuecomment-1149083451 is from vue3 version of BTable :), not compat one :)

**Comment by chirumist** [comment]
Hi there,
How much time for the beta version Or the Alpha version to come out?

**Comment by plenartech** [comment]
@xanf - any updates on releasing the compat branch?

**Comment by Scoottykun** [comment]
Would it be possible to get a release of this even without a fully working BTable component (or any other complex component) ?
I'm so eager to try out this Vue3 version (and i won't need the BTable component in my futur app...).

Thank you so much for your work !

**Comment by xanf** [comment]
x-post for visibility: https://github.com/bootstrap-vue/bootstrap-vue/issues/6872#issuecomment-1194566772

**Comment by ankurk91** [comment]
*P.S. - This PR has been released as `bootstrap-vue@^2.23`*

I am not an expert but I published this package under my name including this PR.

```bash
pnpm install bootstrap-vue@npm:@ankurk91/bootstrap-vue
```
Browse here https://unpkg.com/browse/@ankurk91/bootstrap-vue/

I will be testing this in my project (migrating to vue 3). I will still wait for official release.

**Comment by dword-design** [comment]
@ankurk91 Happily using this publish, thanks!

**Comment by xanf** [comment]
> The `getInstanceFromVNode` method requires a development build of Vue 3 compat in order to work. Otherwise, you'll run into issues like popovers not closing.
> 
> https://github.com/bootstrap-vue/bootstrap-vue/blob/vue3-compat-build/src/utils/get-instance-from-vnode.js#L4
> 
> The library will need to be reorganized to not rely on this function.

Done! Thank you for reporting @mattsteve

**Comment by dword-design** [comment]
Hey guys, thanks for the great work on Vue 3 integration! Here is another small finding which looks like an easier fix (at first ^^):

In `BButtonClose` the x char is not showing up. I already did some downtracking and it looks lie the reason is that `hasNormalizedSlot(SLOT_NAME_DEFAULT, $scopedSlots, $slots)` returns true although it shouldn't. Would be great to have a fix for this.

**Comment by xanf** [comment]
> In `BButtonClose` the x char is not showing up. I already did some downtracking and it looks like the reason is that `hasNormalizedSlot(SLOT_NAME_DEFAULT, $scopedSlots, $slots)` returns true although it shouldn't. Would be great to have a fix for this.

@dword-design Thank you! You've helped to catch a way more bigger issue! Fix pushed

> And this.$bvModal is undefined, not sure if this is known already?

Works for me. Could you provide a bit more context? I believe this requires `GLOBAL_PROTOTYPE` compat flag if you are using `{ MODE: 3 }`

**Comment by xanf** [comment]
@dword-design It should. Did you ran `Vue.use(BootstrapVue)` ?

**Comment by dword-design** [comment]
@xanf Yes I did. Some debugging here: `$bvModal` is set in `Vue.prototype` and `app.config.globalProperties` but undefined. When I artificially set it before, it is also available where it should. Is it maybe related to how it is calculated in `get()`? Or the mixin that creates the instance that is returned?

**Comment by ankurk91** [comment]
@dword-design 
I have published this branch on npm util we get official one.

```bash
pnpm add bootstrap-vue@npm:@ankurk91/bootstrap-vue@^3.0.1
```
Everything is working fine (including $bvModal), using MODE 3. :rocket:

**Comment by xanf** [comment]
@ankurk91 Thank you for confirmation!

I've pushed another change which should not affect anything, however, who knows (previously I was patching `Vue.extend` which is **very** dirty). You might want to publish another version

For everyone watching this issue, this is coming to finish line. Pipeline is still red because of required fixes to @vue/test-utils (they are already in `master` but not yet merged, I'm lucky to be `@vue/test-utils` maintainer)

**Comment by VividLemon** [comment]
@xanf I have been discussing with pi0 about merging bootstrap-vue-3 with this library. But have been noticing that you have been putting in work here to get this library in use with Vue3. You may have not been in contact with pi0 about any of this, but as a member, how do you feel about a potential merge? It seems that your commits here revolve solely around migrating Vue, and not to Bootstrap v5? Perhaps that is where the most benefit would come from, in migrating to a more Vue3 and Bootstrap v5 specific between the two? Though, plans slow as organization members and owners tend to not respond back quickly 🙄

**Comment by xanf** [comment]
@VividLemon feel free to reach me in discord `xanf#9946`. However, I've discussed before the war started plans with pi0, and that was the vision I've presented:

* The future of `bootstrap-vue` is definitely Vue3+Bootstrap 5. However, I do not want to work on these two things simultaneously - I simply do not believe it could be executed in **proper** fashion.

So, let's define **proper fashion**. Based on example of `vue2 --> @vue/compat` migration and example of multiple component libraries I'm keeping an eye of - doing "iterative changes" is **very hard**. Theoretically `@vue/compat` should include all the information you need to do migration, however there are so many nuances (hello, my patches in `vue.js` file in this branch)

The same applies to `bootstrap-vue`. I'm working for [GitLab](https://gitlab.com) and we're the heavy users of `bootstrap-vue` underneath of `gitlab-ui` - our UI library. Any migration of such scale project is slow, complex and problematic. That's why I'm spending my time on this work, which might look useless theoretically at first glance - this is **top 1** importance for me in terms of backwards compatibility

Now I'm able to run tests (in this branch) for **same codebase** with Vue 2 and Vue 3. I even could compare render results to check that we're still rendering the same. Rewriting code to Vue3+Bootstrap v4 allows me to:

* reuse same tests
* compare rendering which should be **precisely the same**
* maintain the same API

I really appreciate the work done on `bootstrap-vue-3` - it is well designed, but if we think about merge, we need to discuss how we could work on maintaining maximum possible compatibility for current `bootstrap-vue` users. I've tried `bootstrap-vue-3` as drop-in replacement for `bootstrap-vue` and obviously there were too many minor nuances here & there... Death from a thousand cuts as it is

Since English is not my mother tongue, I would like to clarify - I'm not saying "hey, this will not happen" or "this should not happen at all" - I see both benefits and downsides having two libraries :) I'm just voicing my concerns - it's mostly not the problems of bootstrap-vue users developing new apps, but bootstrap-vue users who want to continue bootstrap-vue story on Vue3

**Comment by VividLemon** [comment]
> I really appreciate the work done on `bootstrap-vue-3` - it is well designed, but if we think about merge, we need to discuss how we could work on maintaining maximum possible compatibility for current `bootstrap-vue` users. I've tried `bootstrap-vue-3` as drop-in replacement for `bootstrap-vue` and obviously there were too many minor nuances here & there... Death from a thousand cuts as it is

At the time there is no migration guide between the two. Considering there are still things to implement, it is quite pointless to create a guide, then update major parts within a few weeks. I believe that most of the breaking changes between the two are related to TypeScript, Vue 3, and Bootstrap v5 changes. If one copied and pasted a bootstrap-vue code, it could hypothetically have quite a few bugs appear from TS, but that's to assume it's because they're code was incorrect in the first place. If you're trying to push a prop into a component that's expecting a breakpoint class, (sm, md, lg, etc), then of course, it's a "breaking change", but it's the result of breaking code, really. That's where most of the issues will come from, especially if there was a bootstrap v5 breaking change, I can't think of any, but say if alert removed it's fade affect, it would be a breaking change. 

Despite those, the only _true_ breaking changes that I can think of came from odd behavior I found within bootstrap-vue. Thinks like slot names prepending their component name, "modal-backdrop, modal-header", etc. It's an odd creative choice that I've tried to remove, though, there are not a large number of these. Card components do this _a lot_

How would you foresee a merge to happen? To not have someone's time wasted, I think your work on this PR is especially good for those that want a simple migration to Vue 3, but would stay limited within bootstrap v4. Whereas, a bootstrap-vue-3 migration would require more work, but with bootstrap v5 payoffs, and in my view, TypeScript payoffs that are of immense benefit. In addition, my work in moving components off of render functions (4 left), in my view, definitely help new contributors.

**Comment by dword-design** [comment]
@xanf I fixed the `$bvModal` issue. Reason was that BootstrapVue was registered after `createApp` but it had to be registered before, otherwise global mixins registered via `Vue.mixin` won't be available in the app. Interestingly it worked for components and directives.

**Comment by septatrix** [comment]
> How would you foresee a merge to happen? To not have someone's time wasted, I think your work on this PR is especially good for those that want a simple migration to Vue 3, but would stay limited within bootstrap v4. Whereas, a bootstrap-vue-3 migration would require more work, but with bootstrap v5 payoffs, and in my view, TypeScript payoffs that are of immense benefit. In addition, my work in moving components off of render functions (4 left), in my view, definitely help new contributors.

I definitely agree with you here in both aspects. Currently we are using bootstrap-vue in a project where we would like to use Vue 3 but for now still stay with the v4 Bootstrap styles. So for this I very much welcome this PR and appreciate the time invested into this so far despite the ongoing war.
Additionally I think that TS and the transition to SFC instead of render functions is greatly beneficial. We are currently in the process of converting the same project to Typescript and it has been a joy to work with so far (and also uncovered a few potential bugs). And render functions have always repelled me from contributing. They seem somewhat arcane and with Vue 3 they do not yield any performance benefit anymore. So the switch to SFC definitely makes the code easier to maintain and understand.

Definitely keep up the work to both of you. I hope that none of your efforts go to waste and that there is a reasonable way to move forwards with merging the projects!

**Comment by ryleyb** [comment]
Have people had success running the bootstrap-vue3-demo? I tried it and this was the result: https://github.com/xanf/bootstrap-vue3-demo/issues/2

What I'm actually trying to do is run this branch in my own Vue 3 app.  Vue 3.2.40 seems to have the patch integrated, so no need to patch the compat any more nor to patch Vue.vModelDynamic. 

My code looks more like this:

```javascript
import { createApp, configureCompat } from 'vue';
import App from './App.vue';

async function buildApp() {
    configureCompat({
        MODE: 3,
        //all these are required for bootstrap-vue
        GLOBAL_EXTEND: true,
        GLOBAL_MOUNT: true,
        COMPONENT_FUNCTIONAL: true,
        RENDER_FUNCTION: true,
        CUSTOM_DIR: true,
        GLOBAL_SET: true
    });
    const app = createApp({
          components: { App },
       //...
    });
    await addBootstrapVue(app);
    app.mount('#el');
}

async function addBootstrapVue(app) {
  const { default: BootstrapVue, BootstrapVueIcons } = await import(
    'bootstrap-vue/src'
  );
  const PortalVue = await import('portal-vue');
  PortalVue.Portal.options.compatConfig = {
    MODE: 2,
    RENDER_FUNCTION: 'suppress-warning',
    INSTANCE_SCOPED_SLOTS: 'suppress-warning',
    OPTIONS_BEFORE_DESTROY: 'suppress-warning',
  };
  PortalVue.PortalTarget.options.compatConfig = {
    MODE: 2,
    RENDER_FUNCTION: 'suppress-warning',
    WATCH_ARRAY: 'suppress-warning',
    OPTIONS_BEFORE_DESTROY: 'suppress-warning',
    INSTANCE_SCOPED_SLOTS: 'suppress-warning',
  };
  PortalVue.Wormhole.$.type.compatConfig = {
    MODE: 3,
    INSTANCE_SET: 'suppress-warning',
    INSTANCE_DELETE: 'suppress-warning',
  };

  app.use(BootstrapVue);
  app.use(BootstrapVueIcons);
}

buildApp();

```
I end up seeing a bunch of errors very similar to the ones shown in the bug I filed for bootstrap-vue3-demo.

**Comment by xanf** [comment]
Sorry for replying on the run, give a try https://github.com/xanf/temp-bv

чт, 13 окт. 2022 г., 23:24 ryleyb ***@***.***>:

**Comment by xanf** [comment]
that's npm magic. when you allow npm to do it it runs prepare npm script
which builds it automatically

пт, 14 окт. 2022 г., 00:30 ryleyb ***@***.***>:

**Comment by VividLemon** [comment]
> feel free to reach me in discord `xanf#9946`

I sent you an friend request on discord. Upon that, I would like to discuss some things in a private dm if you don't mind

**Comment by VividLemon** [comment]
@xanf Hey there, I just wanted to let you know that I'd still like you're input on a merger if you don't mind. A few members have been in a discord dm, but I would like you're approval on some possible ideas, if you don't mind.

**Comment by xanf** [comment]
> @xanf Hey there, I just wanted to let you know that I'd still like you're input on a merger if you don't mind. A few members have been in a discord dm, but I would like you're approval on some possible ideas, if you don't mind.

I've added you on discord, sorry, too many things on the table, feel free to DM me

**Comment by dword-design** [comment]
Hey, one small report: Icons defined locally in components do not work. They only work when registered globally.

**Comment by xanf** [comment]
@dword-design thank you. May I ask you to create a reproduction in https://stackblitz.com/edit/bootstrap-vue-with-compat?file=components/HelloBootstrap.vue if possible?

**Comment by xanf** [comment]
@dword-design Got it. Unfortunately this is an upstream issue - https://github.com/vuejs/core/issues/6950

**Comment by xanf** [comment]
A single "Merge" for a human, a step forward for entire `bootstrap-vue` community

:rocket:

**Comment by bobvandevijver** [comment]
Great work @xanf! 🎉

**Comment by ultimaweapon** [comment]
Awesome! Thank you so much for your hard work @xanf!

**Comment by davidwessman** [comment]
Amazing! @xanf

**Comment by dword-design** [comment]
That's great, thanks for the good work! @xanf

Just one remark: I tried to upgrade to 2.23 for a Vue 2 project and there were some errors (e.g. this.$store undefined). I could imagine that the release breaks in some ways for Vue 2 projects. Probably all related to @vue/compat.

**Comment by xanf** [comment]
@dword-design that's super weird, I will be happy to see issues because there should be no major changes when you're **not** using @vue/compat.

**Comment by dword-design** [comment]
@xanf It was actually not possible for me find a minimal working example for me because it worked at other places. So I'd say let's wait what is happening the next days.

**Comment by jeffsta9** [comment]
The current version of Popper being used (1.16.1) is depreciated. Will it be updated eventually? JC

**Comment by mrts** [comment]
Really awesome, thank you, thank you, @xanf for your hard work in these difficult circumstances!

**Comment by Scoottykun** [comment]
That's great ! Thank you so much for your hard work !

**Comment by jeffsta9** [comment]
The current version of Popper being used (1.16.1) is depreciated. Will it be updated eventually? Just curious if that's something that's on the table. Not sure if it's possible w/ Bootstrap 4.

**Pull request merged**
