### PR TITLE
chore: Bootstrap-Vue v2.0.0.rc12 Release

### PR DESCRIPTION
**Pull request by tmorehouse**
Preparation for release v2.0.0-rc.12 of **Boostrap-Vue** using Boostrap v4.3.1 SCSS and Vue v2.6.x

See feature/issue tracker #2173 for a list of noted enhancements, features and fixes.

Live Preview: https://deploy-preview-2315--bootstrap-vue.netlify.com/

TODO:
- [x] Bump Package version
- [x] Update changelog (and edit format)

**Releasing on Feb 14, 2019**

### CODE REVIEW

**Comment by jackmu95** [comment]
@tmorehouse Wouldn't it be better to wait for the Bootstrap v4.2 release which is already [in preparation](https://github.com/twbs/bootstrap/pull/27867)?

Some v4.2 components are already present in the `dev` branch and the only one that's missing is the Toast component.

**Comment by TitanFighter** [comment]
> Wouldn't it be better to wait for the Bootstrap v4.2 release which is already in preparation?

In this case I can get time to prepare updates for the docs regarding how to use such events as `bv::popover::show` which is discussed here #2253 (I need about 3-4 days to close current tasks to become a bit free to make PR).

**Comment by tmorehouse** [comment]
I noticed the 4.2 PR at twbs/bootstrap.  I wonder if they have a specific release date in mind.

**Comment by tmorehouse** [comment]
There are a few changes in V4.2 that may affect layout for some...

**Comment by tmorehouse** [comment]
We can leave this PR open, and add in any V4.2 changes (assuming it is released in the next week or so).  Toasts will have to wait until early next year though (although I do have toasts somewhat working on one of my servers, but need to wait for Portal-Vue 2.0)

**Comment by jackmu95** [comment]
@tmorehouse No I don't but I would predict this week.

Is there any reason you want to release v2.0.0 that quickly?
IMHO it would be better wo wait until Bootstrap v4.2 is released and all components are present and stick with some more RC releases until then.

**Comment by jackmu95** [comment]
There have been a lot of awesome changes in the past weeks and months but there are some issues I would like to see fixed until v2.0.0 lands.

The `vue-portal` changes you have in the pipeline sound also very promising and should fix some of those issues.

**Comment by tmorehouse** [comment]
I was just eager to get a release out to keep everyone from getting too restless waiting for a release. ;)

Plus I'm heading off on holidays in a couple of days... and then again the second half of January.. 

I'm fine with pushing out a new release candidate as an interim release, which would be good to weed out any new bugs.

Before I found out about Bootstrap V4.2 coming soon,  I was imagining v2.1 of bootstrap vue would have switched over to v4.2 of bootstrap. But the new PR at bootstrap has changed my opinion.

We can keep this PR open for the full release of v2.0.0, and/or leave it open for the live preview where people can try out features in the docs.

**Comment by tmorehouse** [comment]
The utils I'm working on for Toasts with portal-vue are reusable, and would fit well with modal and tooltips/popovers. And would eliminate the z-index stuff needed for modal stacking as well (as modals would be always in open order sequence in the portal target)

**Comment by tmorehouse** [comment]
2.0 of portal-vue should be released around Dec 24th, and it has some fixes/features needed to make things work right for toasts (right now I have a customized version of the portal component that works around the issues)

**Comment by tmorehouse** [comment]
I would also like to get more of the component testing switched over to vue-test-utils and bump our coverage up a lot more

**Comment by jackmu95** [comment]
I should have some time in the Christmas week to port some more components to `vue-test-utils` 👍

**Comment by tmorehouse** [comment]
Most of the functional components will be good targets, as they are not as complex to test compared to some of the bigger components (i.e. b-table and b-modal)

**Comment by jackmu95** [comment]
What was my plan to concentrate on those ;)

**Comment by jackmu95** [comment]
Bootstrap [v4.2](https://github.com/twbs/bootstrap/releases/tag/v4.2.0) is now released.

**Comment by jackmu95** [comment]
Found another one: `_form-file.scss`.

**Comment by DM2489** [comment]
It would be great to see support added for:
- [ ] Spinners - https://getbootstrap.com/docs/4.2/components/spinners/
- [ ] Toasts - https://getbootstrap.com/docs/4.2/components/toasts/
- [ ] Switches - https://getbootstrap.com/docs/4.2/components/forms/#switches

**Comment by tmorehouse** [comment]
@DM2489 spinners and switches are included. Toast will be in a future release.

See #2173 mentioned above.

**Comment by tmorehouse** [comment]
`PortalVue 2.0.0` looks to be delayed a bit, so will wait on it before introducing `b-toast` until it is released

**Comment by tmorehouse** [comment]
We will be releasing v2.0.0-rc.12 on February 14, 2019.

**Pull request merged**
