### PR TITLE
docs: minor tweaks

### PR DESCRIPTION
**Pull request by tmorehouse**
### Describe the PR

A few minor tweaks to docs

- [x] updated footer
- [x] add footer to `/docs/*` pages layout
- [x] style adjustments to TOC sidebar
- [x] minor style updates for playground
- [x] updates to tooltip/popover docs

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Enhancement
- [ ] ARIA accessibility
- [x] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] New/updated tests are included and passing (if required)
- [ ] Existing test suites are passing
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by jackmu95** [comment]
@tmorehouse Why don't we shoe the footer in the docs too?
The active state of the footer nav is also missing.

**Comment by tmorehouse** [comment]
There were issues with the footer on the docs pages because of the sticky sidebars. but it would be nice to get it to appear on those pages too.

The active class isn't really needed on the links in the footer (as they don't have styles for active state (unlike the navbar at top).

**Comment by tmorehouse** [comment]
@jackmu95 even bootstrap site doesn't use a footer on the docs pages: https://getbootstrap.com/docs/4.3/components/alerts/

**Comment by tmorehouse** [comment]
We might be able to make a version of footer that fits between the sidebars and place it in the docs layout (or slugs for the docs pages)

**Pull request merged**
