### PR TITLE
[dropdown] support click event on dropdown menu item

### PR DESCRIPTION
**Pull request by makkrnic**

### CODE REVIEW

**Comment by cynecx** [comment]
Wouldn't it be better if we could support the click event with every components which uses the b-link component? I am not sure but it worked before but upgrading to a newer release, everything broke, and not to support the click event with basic components seems ridiculous.

Is it possible for you, if you could also add this for b-nav-item component?

**Comment by pi0** [comment]
It is already fixed in Blink (https://github.com/bootstrap-vue/bootstrap-vue/commit/3e9b860d05d8dec8b7f91eb530e9949866dc1966) Sorry for inconvenience releasing new changes soon.

**Comment by cynecx** [comment]
@pi0 I am using master and it doesn't seem to work.

**Comment by pi0** [comment]
@click event is emitted up so it should be working if you currectly build. Please tests against 0.15.7 and open a Issue with JSFiddle so i can check it.

**Comment by pi0** [comment]
Should be fixed by 650799f @0.15.8

**Comment by makkrnic** [comment]
Hello, sorry for not responding sooner, and thank you for such a prompt response (and fix).

**Pull request closed without merging**
