### PR TITLE
Fix bug of tab component removing 'show' css class prematurely

### PR DESCRIPTION
**Pull request by valexiev**
Fixing issue #207.

### CODE REVIEW

**Comment by valexiev** [comment]
The case:
A text input in a tab. When you start typing in the input, the tab content disappears because the CSS class "show" is removed.

This happens because after typing in the text input Vue reapplies classes, but uses only the initial class ("tab-pane") and the value of :class. Vue doesn't know anything about "show" and doesn't reapply it together with the other classes.

**Comment by pi0** [comment]
@mosinve Please merge if you approve. LGTM :)

**Comment by mosinve** [comment]
@valexiev Have you tested? Tabs transition works?

**Comment by mosinve** [comment]
Merged

**Pull request merged**
