### PR TITLE
fix(toast): accessibility - prevent duplicate toast announcements for screen readers (closes #3322)

### LINKED ISSUE #3322: Toast accessibility issue
### Describe the bug

The toast is read multiple times.

### Steps to reproduce the bug

You can use buttons on toast page
https://bootstrap-vue.js.org/docs/components/toast/
On Mac with VoiceOver turned on, it reads twice on Safari, 3 times on Chrome. 
On Windows FF/NVDA, it only reads when there are two toasts.

### Expected behavior

It should read once

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.20

### Demo link

https://bootstrap-vue.js.org/docs/components/toast/

### PR DESCRIPTION
**Pull request by tmorehouse**
### Describe the PR

Better handling of aria-live region by moving aria-live/aria-atomic and role to outer b-toast wrapper.

This allows the live region to be inserted into the dom before the toast is shown, making it easier for screen readers to detect the insertion of the toast content.

To do:
- [x] Adjust the ARIA attributes on the b-toaster to prevent duplicate reading of toasts
- [x] Update test suite
- [x] Dynamically remove the `aria-live` and `aria-atomic` attributes when the toast is about to be closed (which prevents the duplicate read)
- [x] default aria attributes on b-toaster to `null`
- [x] Set `tabindex='0'` on toast to allow users of assistive technologies to reach the toast if needed

Duplicate read issue appears to be related to when the content is Portall'ed over to the toaster target and transition interaction.

Closes: #3322

**Note:** IE11 still has issues with screen readers not voicing toasts (NVDA and JAWS)

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Enhancement
- [x] ARIA accessibility
- [ ] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [x] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [x] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives
- [x] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by tmorehouse** [comment]
@Shemetiuk could you try this PR out using the different screen readers you have?

https://deploy-preview-3329--bootstrap-vue.netlify.com/docs/components/toast/

**Comment by Shemetiuk** [comment]
Sure. Thank you. I'll have ability to try it only on Monday.

**Comment by tmorehouse** [comment]
@Shemetiuk I have added an extra `$nextTick(`) delay to the showing of the toast content in the aria-live region. If you get a chance, could you try the deploy preview again with IE?

**Comment by tmorehouse** [comment]
**Note:** IE11 still has issues with screen readers not voicing toasts (NVDA and JAWS)

There appears to be no easy way to accommodate IE 11 and screen readers cleanly (not without too many hacks and conditionals)

**Pull request merged**
