### PR TITLE
feat(table): Add option to use drag-and-drop reordering with Vue.Draggable #873

### PR DESCRIPTION
**Pull request by sschadwick**
Adding drag and drop functionality to table. Passing in the `:draggable='true'` property does not currently work with `top-row` or `row-details`, as it will skew the internal `<draggable>` counter and move incorrect items.

### CODE REVIEW

**Comment by tmorehouse** [comment]
This adds an extra dependancy to the Bootstrap-Vue library (and weight to the final compiled javascript).

It might be better suited to be created as a `components-extra` (which extends the `b-table` component) that does not get compiled into the main library

**Comment by tmorehouse** [comment]
There are a few caveats with this PR:

One is that items is not always an array.  It can be an items-provider function (there is no check for this in your code).

Items should technically not be mutated (which is why we create  shallow copy of items before paginating, sorting, filtering in the `computedItems` computed prop).  Displayed data (the visible rows) are available via the `v-model` interface.

b-table also slices the items array when paginating.  This PR doesn't take that into account, so the items list you are passing to `dragable` is not always the same as the list of items that is passed to the v-for loop (which is shallow sliced copy of the original items after pagination, sorting and filtering are applied. (i.e. it is a new array instance). Not to mention that the props `items` could be a function reference.

One would have to disable any pagination, sorting and filtering, and disabled the user of providerFunctions internally to prevent issues (and bug reports), not to mention changing how `computedItems` is calculated.

B-Table is already one of the more complex/large components in Bootstrap-Vue, and this would just increase that complexity (dealing with all the _what-ifs_).

Which is why I'll recommend that this not be applied as a patch to `b-table`, and recommend that it be created as a `components-extra` add-on.

**Comment by tmorehouse** [comment]
You could easily wrap `b-table` in a `dragable` component, based on this from the vue-dragable docs:

image

You can specify a CSS selector to target a specific thing that is being drag sorted:

```html
<dragable v-model="myItems" :options="{draggable:'tbody > tr'}">
  <b-table :items="myItems" />
</dragable>
```

The key here is telling dragable what you want _dragable_ via the `dragable` option, which accepts a CSS selector.

This is without the need to embed dragable within the `<b-table>` component.  This targets the rendered `<tr>`'s within `<tbody>` (the CSS selector `tbody > tr`).  If your table isn't empty, and doesn't specify any top or bottom static rows, not user pagination, filtering or storing on b-table (since you are now incontrol, and don't specify ny of these on teh `<b-table>` markup. 

This would work without the need of a PR.

**Comment by tmorehouse** [comment]
Also to mention that Vue-Draggable is not currently SSR friendly (ses issue https://github.com/SortableJS/Vue.Draggable/issues/242), which would make b-table not SSR friendly (which it is today).

**Comment by sschadwick** [comment]
Thank you for the quick response and the well thought-out response. You make several great points that I overlooked while writing the PR. I wasn't able to get the `:options="{draggable:''}"` prop working and ended up building a close approximation of the table in my code and using the Draggable element as `tbody`.
```html
<draggable v-model='obj.items' element='tbody'>
  <tr class='row' v-for='item in obj.items' :key='item.id'>
  ...
  </tr>
</draggable>
```

Upon further thought, I think there are too many obstacles and the use case is too specific to move into `extra-components`. I do however look forward to contributing in the future, and would like to thank you for such an awesome project.

**Comment by tmorehouse** [comment]
I still think vue-draggable could be tweaked a bit to be able to handle an "alternate" root element (via CSS query selector), which would allow it to be wrapped around a "deeper" component, such as `<b-table>`.

I might open a PR against it in the next week or so :-)

**Comment by Kostecki** [comment]
> I still think vue-draggable could be tweaked a bit to be able to handle an "alternate" root element (via CSS query selector), which would allow it to be wrapped around a "deeper" component, such as `<b-table>`.
> 
> I might open a PR against it in the next week or so :-)

Do you ever do in regards to this? :-) I'm trying to get vue.draggable to work with b-table and your quick solution of using the draggable option doesn't seem to work. I don't see why though?

Any other suggestions for how it could be done without rewriting a bunch of things?

**Pull request closed without merging**
