### PR TITLE
[WIP] fix(alert): use v-model to update show value

### PR DESCRIPTION
**Pull request by tmorehouse**
Fix for issue #718

Alex's  initial work on the idea of using v-model to address issue #718

See PR #721 for discussion.

### CODE REVIEW

**Comment by mosinve** [comment]
its about this bug report:
1.) Click on the "Show alert with count-down timer" button
2.) Click the X mark quickly (less than a second after clicking the button above)
3.) Clicking the button again will not display the alert anymore.

Problem in that case is that show value doesn't actually changed, and for all next clicks, watcher don't fire

**Comment by mosinve** [comment]
as a solution, we can emit value=false, or completely destroy alert on close, but then we must create it again at open.

**Comment by tmorehouse** [comment]
So it must be because the time is in the middle of being in first SetTimeout, and when value changes (dismissed, counter isn't being cleared in time... or maybe countdown time should check to see if show has been changed and cancel itself?

**Comment by mosinve** [comment]
No, the problem exactly in not resetting value, used for show.

**Comment by mosinve** [comment]
if to wait at least a 1 sec, for this value changed, the all works fine.

**Comment by tmorehouse** [comment]
What if the first countdown happened immediately (i.e. setTimeout iof 0), and then subsequent countdowns happened 100ms later?

**Comment by mosinve** [comment]
on other hand, maybe it not quite correct example...

**Comment by mosinve** [comment]
having v-model show, i think we dont need to emit `dismiss-count-down` as we can return this countdown back by v-model

**Comment by mosinve** [comment]
And i have Vue warning about direct mutate prop `show`

**Comment by alexsasharegan** [comment]
I'll have to look into this deeper. I also see that I left a straggler in the data @ `vm.dissmissed`. It's no longer being used to compute anything.

**Comment by tmorehouse** [comment]
We can probably delete this PR and branch, now that we have a "fix" (hiding the close button on auto-dismissing alerts)

**Pull request closed without merging**
