### PR TITLE
Tmorehouse modal docs

### PR DESCRIPTION
**Pull request by tmorehouse**

### CODE REVIEW

**Comment by tmorehouse** [comment]
Re-doing again dev branch

**Comment by pi0** [comment]
@tmorehouse I've updated default branch to `dev` if you prefer :))

**Comment by tmorehouse** [comment]
I was also in another branch when I made the first PR... which had other changes in it...  went back to a clean branch and remade the changes.

**Comment by pi0** [comment]
That's a much better idea working on `dev` indeed. Also as a suggestion why don't you make single fixes with direct commits without working on your fork? I think this would save you lots of time :)

**Comment by tmorehouse** [comment]
Using temp branches on this repo, rather than temp branches on my clone.

**Pull request closed without merging**
