### PR TITLE
docs: add some pizazz to index page

### PR DESCRIPTION
**Pull request by tmorehouse**
### Describe the PR

Adds a few cards to index page highlighting features, and minor adjustments for layout and style

Also reduces docs vendor bundles by importing only the `highlight.js` languages needed, and turning off eval-source-maps in prod mode (now enabled for dev mode only)

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Enhancement
- [ ] ARIA accessibility
- [x] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] New/updated tests are included and passing (if required)
- [ ] Existing test suites are passing
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by jackmu95** [comment]
@tmorehouse I like the idea with the V-like section but I think they need a bit more angle and padding.
Currently the look a bit weird to me. Other than that I like the recent chnages a lot.

**Comment by tmorehouse** [comment]
@jackmu95 so a deeper dip in the angle of the V ?

**Comment by jackmu95** [comment]
@tmorehouse Yeah, exactly.

**Comment by tmorehouse** [comment]
Will figure out the docs asset sizes later.

**Pull request merged**
