### PR TITLE
feat(devtools config): add .eslint.config.js and .editorconfig

### PR DESCRIPTION
**Pull request by mosinve**
In order to bring some unification to dev process and minify ESlint errors at build add  .eslint.config.js and .editorconfig.

need to review .eslint.config.js by team members in order to enable necessary rules.

### CODE REVIEW

**Comment by alexsasharegan** [comment]
Hooray tools! 🔧 ⚙️ 🔨

**Comment by tmorehouse** [comment]
Can we just forgo indent altogether? :stuck_out_tongue_winking_eye:

**Comment by mosinve** [comment]
it's not only for us, there are 280 forks, and any of them can make PR... and this is possibly 280 different development enviroments.

**Comment by mosinve** [comment]
merged

**Pull request merged**
