### PR TITLE
[collapse][nav-toggle] Ensure $root event listeners are removed on unmount

### PR DESCRIPTION
**Pull request by tmorehouse**
Ensure that our state listeners get removed before unmounted.

Possible fix for issue #569 

I'm not positive about the move from `created` to `mounted` for initializing the event listeners though.  Thoughts?

### CODE REVIEW

**Comment by tmorehouse** [comment]
Also, wondering if "modal" also has this issue or not?

**Comment by tmorehouse** [comment]
@pi0 and @alexsasharegan 

Could you take a look at this PR? Is enabling the listeners on mounted instead of created OK?

**Comment by alexsasharegan** [comment]
So listening to root events could easily be done on either created or mounted since it's not a dom event. If the event listener makes a dom related change, I saw use the mounted hook instead. Why listen for an event when you haven't even rendered yet?

**Comment by tmorehouse** [comment]
It might be possible that state is issued by another element/component before the component is mounted. that would be my only concern.

**Comment by alexsasharegan** [comment]
Ultimately, I have a gut feeling this isn't a bug (or at least not the bug we think it is), but something else about how the issue creator has the vue app setup.

**Comment by tmorehouse** [comment]
And I was under the understanding that when a component is "taken down", that any component event listeners are also removed.  But I could be wrong

**Comment by alexsasharegan** [comment]
You're not wrong:
https://github.com/vuejs/vue/blob/07a37264c3b56952435331983adcf4081390b400/src/core/instance/lifecycle.js#L130

**Comment by alexsasharegan** [comment]
Let me pull that from master branch: https://github.com/vuejs/vue/blob/master/src/core/instance/lifecycle.js#L127

**Comment by tmorehouse** [comment]
so does `vm.$off()` remove only `mv.$on(...)` events, or does it include `vm.$root.$on(...)` events as well?

**Comment by alexsasharegan** [comment]
I think you just figured it out!

**Comment by alexsasharegan** [comment]
https://github.com/vuejs/vue/blob/master/src/core/instance/events.js#L69-L103

**Comment by alexsasharegan** [comment]
If this is in fact the problem (and it sounds rather promising), I think a mixin might even be warranted. This could allow for a special root event creator method that would manage root events and unbind them so nobody else makes this mistake.

**Comment by tmorehouse** [comment]
so a collapse state listener mixin...

**Comment by alexsasharegan** [comment]
Potentially like this:
```js
export default {
    data() {
        return {
            bv_root_listeners: []
        }
    },

    methods: {
        listenOnRoot(event, callback) {
            this.bv_root_listeners.push({ event, callback })
            this.$root.$on(event, callback)
        }
    },

    destroyed() {
        let listener = undefined
        while ((listener = this.bv_root_listeners.shift())) {
            this.$root.$off(listener.event, listener.callback)
        }
    }
}
```

**Comment by alexsasharegan** [comment]
Or maybe tweak the destroyed loop:
```js
destroyed() {
    while (this.bv_root_listeners.length) {
        let listener = this.bv_root_listeners.shift()
        this.$root.$off(listener.event, listener.callback)
    }
}
```

**Comment by alexsasharegan** [comment]
This is just a different target from something I did previously for binding events outside the component's dom:
```js
export default {
    data() {
        return {
            vmListeners: []
        }
    },

    methods: {
        registerListener(target, event, fn) {
            if (target instanceof EventTarget) {
                this.vmListeners.push({ target, event, fn })
                target.addEventListener(event, fn)
            } else {
                throw TypeError(`Expected an instance of EventTarget interface.`)
            }
        },

        _removeListeners() {
            this.vmListeners.forEach(({ target, event, fn }) => target.removeEventListener(event, fn))
        }
    },

    destroyed() {
        this._removeListeners()
    }
}
```

**Comment by tmorehouse** [comment]
Should we implement the mixin maybe for release v0.17.1?

**Comment by tmorehouse** [comment]
Modal also listens for events on $root as well, and may need a tweak.

**Comment by alexsasharegan** [comment]
I don't think we need to stuff anything else in `v0.17.0`. And with modals, this is exactly why a mixin seems like a good idea to me.

**Comment by tmorehouse** [comment]
Yeah, v0.17.0 has a lot of changes

**Comment by alexsasharegan** [comment]
So, if my latest PR looks good, you could merge that into here and use it for the collapse. I would say do separate PR's for modal & any other affected components.

I think you could keep the calls to register the listeners in the `created` hook. Probably best not to change what ain't broken.

**Pull request merged**
