### PR TITLE
[dropdowns] Allow hover to focus item

### PR DESCRIPTION
**Pull request by tmorehouse**
To emulate the way `<select>` focuses/highlights current menu item on mouse hover.

See discussion at #399

### CODE REVIEW

**Comment by mosinve** [comment]
Seems working to me, did you test it locally?

**Comment by tmorehouse** [comment]
I tested in a fiddle where I loaded the menu, and then manually added a listener event on the `dropdown-menu` div that grabbed the dropdown items and focused the hovered one.

**Comment by tmorehouse** [comment]
Hmmm. Actually this conflicts with the hover styling, which hides to focus ring while the item is hovered, but does indeed focus the item.

**Comment by tmorehouse** [comment]
I'm not sure if I like how this works visually, as the hover style overrides the focus style, when the item is hovered.

Moving the mouse out of the menu does indeed show that the hovered item was focused:
https://jsfiddle.net/ckrcbk5h/1/

**Comment by tmorehouse** [comment]
If we were to set the `.active` class on the focused/hovered item (and remove it from the others), it actually emulates a select menu more closely.

**Comment by tmorehouse** [comment]
Check out this fiddle using `active` on the focused item: https://jsfiddle.net/ckrcbk5h/5/

image

The item with the blue background has the active class when focused (note this is only on hover at the moment)

**Comment by pi0** [comment]
Thats so nice @tmorehouse  🙌 Thanks @mosinve for helping :)

**Comment by mosinve** [comment]
I'm glad I could be useful. ;)

**Comment by mosinve** [comment]
I like dropdown now )) Thanks @tmorehouse 👍

**Pull request merged**
