### PR TITLE
feat(card): functional components for card 🎴

### PR DESCRIPTION
**Pull request by alexsasharegan**

### CODE REVIEW

**Comment by pi0** [comment]
@alexsasharegan What's your idea moving `examples` ~> `tests/fixtures` as they are really fixtures now :))

**Comment by tmorehouse** [comment]
Yeah.. they aren't really examples, and we wouldn't want people fiddling with them which would interfere with tests.

**Comment by alexsasharegan** [comment]
Perfect! That seems right to me. Let me make that change once I get home!

**Comment by tmorehouse** [comment]
Should `fixtures` be under the `tests` directory (i.e. `tests/fixtures/`)

**Comment by alexsasharegan** [comment]
@tmorehouse I'll fix that on the next PR

**Pull request merged**
