### PR TITLE
[WIP] Better Tables

### PR DESCRIPTION
**Pull request by pi0**
This is work-in-progress (and still not working!) attempt to decouple table data from its presentation component. I've just opened this so if anyone has ideas on this we can work/discuss here.
This allows users to have complete control over data and make it possible to server side operations.

### CODE REVIEW

**Comment by mosinve** [comment]
Just thoughts...
What if we expose events to allow user bind callbacks to them, providing custom contol of getting data, filtering, sorting, pagination control...
and we can provide built-in out-of-the-box table controller just to make component work.

**Comment by pi0** [comment]
Using events callback is a good idea! :) Biggest problem is with async data, we need to somehow update component after pagination and other operations and Vue don't seem to support this. Also table component is getting bigger and bigger as we are adding more features to it.
If you see changes I've moved pagination and other props to the adapter. You think keeping them here would be better?

**Comment by mosinve** [comment]
I just think that we build an UI element, which doesn't need to know where data come from and how it processed, it's job is to display that data the way we need. 
So table will need some support code to make it work.

**Comment by pi0** [comment]
@mosinve That is the exact reason I am extracting that process logic outside of component, so we have tow solutions: 
- Implement and keep a bare-bone event based API inside component which sends callbacks when needs new data. (Component requests to be controlled from outside world via events)
- Allow users passing an `Adapter` which provides anything that component needs. (Outside world provides  an api that component can use to retrieve data)

**Comment by mosinve** [comment]
I think that event based API will be more flexible.
And i agree that table component getting more complex.  It's already not just a table from bootstrap, it's on the way to be like jQuery Datatable.

**Pull request closed without merging**
