### PR TITLE
[tables] Allow slots for empty result sets

### PR DESCRIPTION
**Pull request by tmorehouse**
added two slots:
- `empty` to be shown if no items (`items.length === 0`)
- `emptyFiltered` to be shown if a filtered result has no records

and one prop
`showEmpty` to enable showing the empty slots

One method to address issue  #385

There might be better ways to do this though.  comments/changes welcome.

### CODE REVIEW

**Comment by bastones** [comment]
It is not very clear [in the documentation](https://bootstrap-vue.js.org/docs/components/table/#items-record-data-) that the `showEmpty` prop MUST be set on the `b-table` component in order for the `empty` and `emptyFiltered` slots to work. Is this the case?

I'll be happy to update the documentation to make this clearer for others, but just want to double-check this is the intended behaviour.

**Comment by emanuelmutschlechner** [comment]
I think documentation is fine. `show-empty` is listed in the "Component Reference" of `<b-table>` and it's usage is shown in the "Complete Example".

**Comment by bastones** [comment]
Is it too much hard work to add a few words to the row in the table under the "Slots" heading to make developers aware the `empty` and `emptyfiltered` slots won't work if the `show-empty` prop is not set?

I will even do this myself if I know the pull request will be accepted, but I stand by what I said - it is not clear and good documentation should be clear about technical behaviour. It is only after using the component and wasting time tracking down why the slot wasn't working that I now know why this happens: it's because I can see there is a default message that gets displayed which the `empty-text` prop or `empty` can replace, but again only if the `show-empty` prop is set.

**Comment by arippberger** [comment]
+1 for @bastones comment on adding info to the documentation. It doesn't make it clear `show-empty` needs to be set to true.

**Pull request merged**
