### PR TITLE
feat(b-sidebar): add prop `backdrop-variant`

### PR DESCRIPTION
**Pull request by Hiws**
### Describe the PR

This PR adds an additional property `backdrop-variant`.
You can use the `backdrop-variant` prop to control the theme color variant of the backdrop.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix (fixes a boo-boo in the code) - `fix(...)`, requires a patch version update
- [ ] Feature (adds a new feature to BootstrapVue) - `feat(...)`, requires a minor version update
- [x] Enhancement (augments an existing feature) - `feat(...)`, requires a minor version update
- [ ] ARIA accessibility (fixes or improves ARIA accessibility) - `fix(...)`, requires a patch or minor version update
- [ ] Documentation update (improves documentation or typo fixes) - `chore(docs)`, requires a patch version update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe since breaking changes require a minor version update)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type (patch or minor).**

**If new features/enhancement/fixes are added or changed:**

- [x] Includes documentation updates
- [x] Includes component package.json meta section updates (prop, slot and event changes/updates)
- [ ] Includes any needed TypeScript declaration file updates
- [x] New/updated tests are included and passing (required for new features and enhancements)
- [x] Existing test suites are passing
- [x] CodeCov for patch has met target (all changes/updates have been tested)
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by jackmu95** [comment]
When thinking a bit about it we should have gone for the same logic as `<b-modal>`.
Render a backdrop by default and add `hide-backdrop` and `no-close-on-backdrop` props.

**Comment by tmorehouse** [comment]
@jackmu95 although the majority of side bar usages I have seen in the wild are non-modal (i.e. don't show a backdrop by default, and allow user interaction with the page)

**Comment by Hiws** [comment]
> When thinking a bit about it we should have gone for the same logic as `<b-modal>`.
> Render a backdrop by default and add `hide-backdrop` and `no-close-on-backdrop` props.

Possible. I remember the first time i opened the sidebar i tried clicking outside of it to close it, and was confused why nothing happened.
I've might just have grown used to that behavior from mobile. 
So this was more to add back that behavior without having to have a visible backdrop.

**Comment by tmorehouse** [comment]
There is actually an example of using a bootstrap modal as a `side-modal` https://github.com/twbs/bootstrap/pull/27035 via some additional CSS/Classes

**Comment by tmorehouse** [comment]
Perhaps the click-out handler could be used to close the modal when clicking outside (although it requires a click listener to be instantiated on the document body when the component is visible, and removed when hidden).

**Comment by jackmu95** [comment]
> @jackmu95 although the majority of side bar usages I have seen in the wild are non-modal (i.e. don't show a backdrop by default, and allow user interaction with the page)

This is a solid point.
I'am also fine with the the current solution.

**Comment by Hiws** [comment]
Alternatively a `backdrop-class` prop could be made to pass classes to the backdrop, which might be more flexible in the long run, while still allowing the result that this PR produces.

But it would be less obvious that it's possible for the users, but that might not be the biggest issue.

**Comment by tmorehouse** [comment]
Or a `backdrop-variant` prop (defaulting to `dark`).  Opacity it set via SCSS to make it transparent.

**Pull request merged**
