### PR TITLE
Couple of fixes

### PR DESCRIPTION
**Pull request by gpyh**
I had to make some fixes for a project I'm working on. I'm sharing them back upstream.
In details :

- Uses directly the bLink components by importing it. I'm using Vue without the template compiler and it rightly complained about not knowing `b-link`. This fixes that issue.
- ~~Slight code improvement for bFormInput: it uses `is` instead of `v-if` to switch between input and textarea. If found this cleaner.~~
- Blur and focus events from input and textarea and propagated up to chain in bFormInput.

### CODE REVIEW

**Comment by pi0** [comment]
@gpyh Hello and thanks for your contribution :) Some improvements where actually done in `inputs` branch. I'll merge them now. rebase your PR before merging.

**Comment by gpyh** [comment]
Rebased and force-pushed. The code improvement has already been made.

**Comment by pi0** [comment]
lib/components/nav-item.vue:10:23
  ✖  10:23  Unable to resolve path to module ./link.       import/no-unresolved
  ✖  10:31  Missing semicolon.                             semi
  ✖  14:11  Expected indentation of 8 spaces but found 6.  indent

Have you some time fixing small ESLint problems too ?

**Comment by gpyh** [comment]
Sorry, I didn't lint it. Will do shortly.

**Comment by gpyh** [comment]
Done.

**Comment by pi0** [comment]
@gpyh Thanks body :)

**Pull request merged**
