### PR TITLE
feat(b-media): improve aside right handling

### LINKED ISSUE #5117: Bootstrap Customization breaks component UI
### Describe the bug

Hi, It's been 2 weeks I am using bootstrap vue for my project. It's very good. However, recently I came up with few issues.

**Spacing Utilities:**
In bootstrap-vue, we get some spacing utilities used in components like `mx-1` or `p-1`. This is good for users but adding this to framework will break component styles if someone customizes bootstrap's spacer according to their needs. Below is some examples:
  
*Toast*
rsz_toast
*calendar*
rsz_calendar-full

**Icons:**
As I have just started exploring bootstrap-vue I haven't explored all components and flexibility they provide. But I have an issue with changing icon of calendar component's action buttons. So, providing an option for using custom icons will be beneficial for everyone.

### Steps to reproduce the bug

Change bootstrap **spacer** utility.
e.g.
```
$spacer: 1rem;
$spacers: ();
$spacers: map-merge(
  (
    0: 0,
    25: (
      $spacer * 0.25,
    ),
    50: (
      $spacer * 0.5,
    ),
    75: (
      $spacer * 0.75,
    ),
    1: (
      $spacer,
    ),
    2: (
      $spacer * 1.5,
    ),
    3: (
      $spacer * 3,
    ),
    4: (
      $spacer * 3.5,
    ),
    5: (
      $spacer * 4,
    ),
  ),
  $spacers
);
```

### Expected behavior

I have checked other library before creating this issue and I found that [reactstrap](https://reactstrap.github.io/) don't use any spacing utilities. So, even if someone changes bootstrap's customization UI doesn't look weird.

### Versions

**Libraries:**

- BootstrapVue: 2.11.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

Not required

### Demo link

None

### Additional context

None

### PR DESCRIPTION
**Pull request by jd-0001**
### Describe the PR

This PR is a follow-up to #5121 and removes the usage of utility classes `<b-media>`.
It also introduces a new `right` prop on `<b-media-aside>`.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix (fixes a boo-boo in the code) - `fix(...)`, requires a patch version update
- [ ] Feature (adds a new feature to BootstrapVue) - `feat(...)`, requires a minor version update
- [x] Enhancement (augments an existing feature) - `feat(...)`, requires a minor version update
- [ ] ARIA accessibility (fixes or improves ARIA accessibility) - `fix(...)`, requires a patch or minor version update
- [ ] Documentation update (improves documentation or typo fixes) - `chore(docs)`, requires a patch version update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe since breaking changes require a minor version update)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc.). **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type (patch or minor).**

**If new features/enhancement/fixes are added or changed:**

- [x] Includes documentation updates
- [ ] Includes component package.json meta section updates (prop, slot and event changes/updates)
- [ ] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (required for new features and enhancements)
- [ ] Existing test suites are passing
- [ ] CodeCov for patch has met target (all changes/updates have been tested)
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Review by jackmu95 — CHANGES_REQUESTED** [review]
I would prefer to generally add add `media-aside` class and a `right` prop to `BMediaAside`.
Based on the `right` prop, the `media-aside-right` class would be added.
This could then reset the the default `margin-right` on `media-aside` and set the `margin-left`.

The tests need also some adjustments.

**Review by jackmu95 — APPROVED** [review]

**Comment by zhnoah** [comment]
how to add 'mr-3' class when using aside slot.

**Comment by jd-0001** [comment]
Hi, @zhnoah mr-3 is added using CSS so you no longer need to add this class. Please check the latest docs and inspect the component to find the new class.

Regards

**Comment by jd-0001** [comment]
Hi, @zhnoah mr-3 class is converted into style. You can check the latest docs and inspect the component for new style.

Regards.

**Pull request merged**
