### PR TITLE
[file-input] drop and multi files support + improvements #167

### PR DESCRIPTION
**Pull request by pi0**

### CODE REVIEW

**Comment by pi0** [comment]
@mosinve ping!

**Comment by mosinve** [comment]
Seems to work.... but feels like it's a one big cheat)))) 
found some more info about webkitdir
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitEntries
https://developer.mozilla.org/en-US/docs/Web/API/File/webkitRelativePath

**Comment by pi0** [comment]
Yes somehow workaround but at least we keep API consitansy and users can use easier. The only problem as you mentioned in links is when user drags directory in directory mode. This case was not handled...

**Comment by mosinve** [comment]
yeah... there are left things to work on.
one more addition - IMHO we need to add most of the props of standart input file el.
i found that missing accept and disabled props...

**Comment by mosinve** [comment]
if listen to native dragover event on label, then drag-n-drop directories works, but doesn't work 'drop here target' ;(

**Comment by pi0** [comment]
I'm going to start working on it in few minutes later :)

**Comment by pi0** [comment]
@mosinve Finally working :)) Also there is an almost rewrite for all input elements. props are refactored to a single mixin. so we can maintain it better in future especially on v4 release.

**Pull request merged**
