### PR TITLE
chore(deps): Add Vue as a peer dependency

### PR DESCRIPTION
**Pull request by tmorehouse**
### Describe the PR

Adds Vue as a peer dependency, to let webpack know that BootstrapVue is to use the same Vue as people's projects.

May address #3040 

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [x] Enhancement
- [ ] ARIA accessibility
- [ ] Documentation update
- [x] Other (please describe): dependancies

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by pi0** [comment]
This will force nuxt module users to be required installing vue too

**Comment by tmorehouse** [comment]
Should Nuxt maybe include Vue as a peerDependency as well?

What happens if someone is using Element-UI or Vuetify, which also include Vue as a peerDependency?

https://github.com/vuetifyjs/vuetify/blob/75739d9f64c44e31552fd209c96231590459759d/packages/vuetify/package.json#L85-L87

https://github.com/ElemeFE/element/blob/01a4118c513cd7fb13cbaabeaff57a97d5facab7/package.json#L68-L70

**Comment by tmorehouse** [comment]
And Portal-Vue has Vue as a peerDependency as well:

https://github.com/ElemeFE/element/blob/01a4118c513cd7fb13cbaabeaff57a97d5facab7/package.json#L68-L70

**Comment by tmorehouse** [comment]
Actually it may not force them to install Vue... it will give them a warning that a peer dependency is not met

**Comment by pi0** [comment]
Despite our babel transpiled `es/` dist both [vuetify](https://unpkg.com/vuetify@1.5.11/dist/vuetify.js) and [element-ui](https://unpkg.com/element-ui@2.7.2/lib/element-ui.common.js) are compiled with webpack which has its own internal mechanism for duplicate prevention.

Nuxt uses implicit dependency installation for easier usage. If we require manually doing it for vue, users have to install `vue`, `vue-server-renderer` and `vue-template-compiler` packages (and all with exactly same version) which is at least anti-pattern for nuxt.

Adding `vue` to `peerDependencies` of BV does not improve or change the behavior of newer package managers. (see [npm docs](http://npm.github.io/using-pkgs-docs/package-json/types/peerdependencies.html)) neither webpack has not any mechanism to assume about `peerDependencies` of BV so is not a solution for current problem.

Also adding `vue` to the `dependencies` section of `bootstrap-vue`, when incompability happens (between `nuxt` and `bootstrap-vue`) a duplicate version of `vue` will be installed in `node_modules/bootstrap-vue/node_modules/vue` or `node_modules/@nuxt/vue-app/node_modules/vue` which is making this worst.

For our `Vue.extend` we may need a solution to use the same instance of Vue which is also globally used for webpack. This can be possible by keeping a global reference of Vue within nuxt module plugin. And we need a proper reproduction to verify all of this.

**Comment by tmorehouse** [comment]
We could create a utility module that performs the Vue.extend needed for various components (specifically modal message boxes, and toasts, since we need to be able to create dynamic instances of the BToast component on the fly.

This would make a single point of contact for the Vue reference within BootstrapVue, and then we can work with that single file to get the correct Vue instance (i.e. checking for it on Globals, elsewhere, etc)

**Comment by tmorehouse** [comment]
Closing, as we may have a better way to handle this.

**Pull request closed without merging**
